### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by DOOMMARINE117** [schellingb/dosbox-pure#1]
Hoe do you load this?

**Comment by Mah0uPh0x** [comment]
First, download the correct zip for your operating system from the releases section. Then, unzip and drag dosbox_pure_libretro.dll into your RetroArch/cores folder and drag dosbox_pure_libretro.info into your RetroArch/info folder. Launch RetroArch.exe, load the core, drag in a zipped dos game or launch it through load content and you should be good to go.

**Comment by Quest79** [comment]
This might need a wiki or something to stem the coming flood of this question and ones like it here

**Comment by fragmental** [comment]
I assume it will be added to the core downloader eventually, which will allow it to be installed like any other core.

**Comment by DOOMMARINE117** [comment]
so im guessing this pretty much just for retroarch? will it be available separately or no?

**Comment by schellingb** [comment]
Thanks Mah0uPh0x for the detailed instructions.
The README also contains a brief [explanation about how to install](https://github.com/schellingb/dosbox-pure#install).

This core should be available in the core downloader sometimes after the new build system has been finished by the libretro folks. Looking forward to that myself as that hopefully means lots of different platforms, not just the 4 I'm building manually now :-)

@DOOMMARINE117 For now this runs best in RetroArch, yes. It might run in other libretro frontends, but I have not tried any. The idea of making a standalone version has crossed my minds but DOSBox Pure enjoys quite a lot of the RetroArch UI features (core options, disc loader, control options, save state selection, ...) so it would be a lot of work to make it useful.
