### ISSUE TITLE
Save states don't save with Vulkan/GL

### ISSUE THREAD

**Issue by trostboot** [schellingb/dosbox-pure#101]
Current RA nightly, latest dosbox-pure core from the RA updater as of today.
Windows 10 20H2, GTX 1080 (driver 461.09). 
Tested with Prince of Persia and Lotus: The Ultimate Challenge.

Save states don't save at all when using Vulkan or GL as output driver in RA. No OSD messages, nothing is written to disk. 
Nothing I can see in the log files aside from RA itself throwing an error that automated save states (on exit/load for undo) didn't save.

Creating a save state using the d3d11 driver does work, and said save state also loads correctly when using vulkan or gl.
This happens both on my normal install, as well as a fresh and otherwise untouched RA install.

**Comment by sweatypickle** [comment]
I'd been meaning to open this. It started somewhere after the 11/17/20 Nightly but I haven't been able to narrow it further.

**Comment by Tasosgemah** [comment]
I had a similar issue when Hard GPU Sync was ON. Disabling it fixed it for me.

**Comment by trostboot** [comment]
I was aware of your issue.
1) Hard GPU sync is a GL only option, unrelated to Vulkan.
2) The option has no effect on savestates when using GL (with newer versions of RA/the core).

**Comment by n1ghttrap** [comment]
Confirming this.  Doesn't work in GL/Vulkan but works in D3D11/12, where vsync is broken. :/

**Comment by schellingb** [comment]
I just tried the last official nightly build of RetroArch on Windows and with both Vulcan and GL video drivers states save and load fine for me. Is this only affecting this core or other cores as well?

**Comment by n1ghttrap** [comment]
> I just tried the last official nightly build of RetroArch on Windows and with both Vulcan and GL video drivers states save and load fine for me. Is this only affecting this core or other cores as well?

I'll try again today.

**Comment by trostboot** [comment]
Reconfirming it still happens on latest RA nightly and core. Similarly, it's not an issue in all other cores I'm using. Rewind is off, and the core option is set to enable save state support only.

**Comment by n1ghttrap** [comment]
Will test with an Intel + igpu + Win7 laptop soon to see if it's my setup.

**Comment by n1ghttrap** [comment]
Additionally, ran a completely fresh RA, no settings altered from stock.  Also disabled anything that might remotely mess with the screen like VNC and MSI Afterburner.  Downloaded your core, failed to save states in GL.

**Comment by schellingb** [comment]
Hmm, can you try to download the core from the GitHub [releases page of this project](../releases/latest)?
Also can you go to Settings -> Logging and set "Logging Verbosity" to "ON" and both "Frontend Logging Level" and "Core Logging Level" to "0 (Debug)" and see if and what gets logged during both saving and loading.

**Comment by trostboot** [comment]
Using the core from the Github page doesn't change anything.
Here's the log output. This is after starting the game, successfully loading the savestate created in D3D, then trying to save to state 2, loading the (non-existent) state 2, then quitting.
[Full log if you want to have a more thorough look.](https://github.com/schellingb/dosbox-pure/files/6121540/retroarch__2021_03_11__09_25_20.log)


> [INFO] [State]: Loading state "D:\Games\DOS\Lotus3\VirtualHD\Lotus3\LOTUS.state1", 1015562 bytes.
[INFO] [State]: Saving state "RAM", 597936 bytes.
[INFO] [Vulkan]: VSync => ON
[ERROR] [State]: Failed to save state to "D:\Games\DOS\Lotus3\VirtualHD\Lotus3\LOTUS.state2".
[INFO] [Vulkan]: VSync => ON
[INFO] [Vulkan]: VSync => ON
[INFO] [Vulkan]: VSync => ON
[INFO] [State]: Loading state "D:\Games\DOS\Lotus3\VirtualHD\Lotus3\LOTUS.state2", 0 bytes.
[ERROR] [State]: Failed to load state from "D:\Games\DOS\Lotus3\VirtualHD\Lotus3\LOTUS.state2".
[INFO] [Vulkan]: VSync => ON
[ERROR] [State]: Failed to save state to "D:\Games\DOS\Lotus3\VirtualHD\Lotus3\LOTUS.state.auto".
[INFO] Auto save state to "D:\Games\DOS\Lotus3\VirtualHD\Lotus3\LOTUS.state.auto" failed.

**Comment by trostboot** [comment]
> I've noticed now that it also doesn't work in D3D12. Saving states will only work in D3D10 and 11. My Nvidia driver is 456.71.

I can't confirm this. Saving states works for me in D3D12, driver 461.72.

I'd like to test it with my AMD GPU, but unfortunately the Vulkan driver included with the driver version that crt_emudriver is based on is too old and will crash modern Vulkan apps, and I've not seen any way to specify a GPU with GL, unlike Vulkan and D3D. It saves states fine in D3D12, but as that's also working for me on Nvidia, that doesn't help much.

**Comment by gamerk2** [comment]
I have a similar problem when using savestates with Vulkan, but made an additional discovery: Savestates work fine when doing so manually through the Retroarch menu:

"[INFO] [State]: Saving state "G:\Roms\Retroarch\states\DOSBox-pure\A10.state", 547387 bytes."
[INFO] [Vulkan]: VSync => ON

If I use the keyboard shortcut, I instead get:

"[ERROR] [State]: Failed to save to "G;\Roms\Retroarch\states\DOSBox-pure\A10.state".

Using D3D11 works as expected: Keyboard shortcut works and saves load fine.

Also a NVIDIA user, so can't test if this is a NVIDIA specific issue or not.

**Comment by mrmatteastwood** [comment]
Guys, this seems to be fixed in 0.12 according to sweatypickle (see mention above). Can you check? (I can't, I'm on Linux Mint. Just posting here to nudge y'all ;-)).

**Comment by trostboot** [comment]
Can confirm that savestates save correctly now on Vulkan for me. Good work.
