### ISSUE TITLE
Support for booter games

### ISSUE THREAD

**Issue by TheDatadrainer** [schellingb/dosbox-pure#102]
Hi,
For now booter games (games on floppy with boot sector and custom boot code) are not recognized and cannot be launched from the menu.
Do you plan to add some support for them in the coming versions?
Thanks.

**Comment by schellingb** [comment]
The startmenu in [0.9.0 beta](../releases/tag/0.9.0) can now directly boot from disk images and swapping disks at runtime with RetroArch's "Disc Control" menu and hotkeys is also supported.

Booting of a PCjr game:
![DOSBox_Pure_RiverRaid](https://user-images.githubusercontent.com/14200249/164047889-6b239386-da5b-4d7c-a2ea-69f8d538ce9b.gif)

Please try it out! As usual, any feedback is welcome.

**Comment by TradeDraft** [comment]
President Choice is now Working.

Thanks for Fixing That

**Comment by TheDatadrainer** [comment]
@schellingb
Thank you very much for this feature!
I tested a dozen of games and every one of them was working. I can now play to the original Wizadry & Zork games under RetroArch in there former glory :)
Good continuation on the development of this Core.

**Comment by TradeDraft** [comment]
Tried the President Choice today seems to be Broken Again.

I select to use CGA and just Freezes and does not go back to the Menu.

Am I do something wrong or is something that has Changed in the Core?

**Comment by TradeDraft** [comment]
Found a Work Around for the Moment.

Set the Video Graphics to CGA then when Start President Choice it works.

Just have to set it back to SVGA after Finishing Playing Game

**Comment by TradeDraft** [comment]
> Found a Work Around for the Moment.
> 
> Set the Video Graphics to CGA then when Start President Choice it works.
> 
> Just have to set it back to SVGA after Finishing Playing Game

Tried it just now and again it's not Loading

**Comment by schellingb** [comment]
Can anybody try the latest release with booter games? Issues should be fixed.

**Comment by TradeDraft** [comment]
> Can anybody try the latest release with booter games? Issues should be fixed.

I Tried President Choice from eXoDOS and as long I press CGA when Booting Disk and then after that Press the PC Fix file then press Boot Image it Worked
