### ISSUE TITLE
dosbox_pure_libretro.dll

### ISSUE THREAD

**Issue by fizzletoe** [schellingb/dosbox-pure#103]
This file is not in the zip as indicated in the README.md ## Install section

**Comment by sweatypickle** [comment]
sure it is... [https://github.com/schellingb/dosbox-pure/releases](url)

**Comment by fizzletoe** [comment]
I apologize for being 'slow', can you point me to the exact location of the file?
Thank you so much

**Comment by sweatypickle** [comment]
https://github.com/schellingb/dosbox-pure/releases

I'm not sure what you mean. Go to that location, download the zip for the system you want (I'm assuming Win64) and the dll is in the zip.

**Comment by fizzletoe** [comment]
I was going to:  https://github.com/schellingb/dosbox-pure
Couldn't find it

**Comment by sweatypickle** [comment]
Glad you got it figured out! Please close this if there's nothing else.

**Comment by fizzletoe** [comment]
Found
