### ISSUE TITLE
DOSBox Pure 0.10 heats up graphics card [edit: also 0.9 and possibly previous]

### ISSUE THREAD

**Issue by mrmatteastwood** [schellingb/dosbox-pure#107]
Hey @schellingb, I noticed that the graphics card on my laptop (an RTX 2070) heats up to around 72°C when playing games in DOSBox Pure 0.10 while playing YouTube videos on my other screen.

I tried Jazz Jackrabbit and Hocus Pocus. Running the same games in DOSBox SVN results in temps around 55-60 degrees, the same temps I get when playing e.g. Cool Spot SNES using SNES9x - Current. For the other cores, it makes no big difference (perhaps 1-2 degrees) whether anything happens on my other screen or not.

It seems like the temps stay cooler in DBP, too, when not running YouTube videos on the other screen.

I know that in RA, you can disable Vsync and Hard GPU Sync to avoid overheating, and I haven't had either of those options on in years.

So it seems like something in DBP puts more strain on the graphics card than other cores, and having videos playing at the same time in other software seems to compound the issue. Or perhaps it's really just Chrome, which uses hardware acceleration on my Linux Mint 21 system? Can you think of any reason why this issue might happen in DBP specifically?

**Comment by mrmatteastwood** [comment]
Quick update, this also happens when I hide Chrome behind RA on the same screen that I use to play, meaning I can't see the video.

I'm also pretty sure I played Jazz Jackrabbit using DBP 0.9 last week while I was at my parents', with YouTube stuff running in the background (again on the same screen, the laptop's internal one), and the cooling fans never spun up.

**Comment by mrmatteastwood** [comment]
I have another quick follow-up. I tried the same thing again today playing Hocus Pocus on the same laptop, but with no extra screens connected, only the laptop's own integrated screen. Again, I had Chrome open in the background with a whole bunch of tabs open, including 1-2 YouTube tabs. But they weren't active.

The graphics card still heated up, but more slowly, and when it reached around 65°, the fans had less trouble cooling it back down to around 58°, though they then kept running all the way until I closed RA again.

**Comment by mrmatteastwood** [comment]
Some more quite interesting findings! I ran the following this morning right after booting my PC, without anything else running at all:

Heretic in GZDoom
Cool Spot in RetroArch using Snes9x - Current
Hocus Pocus in RetroArch using DBP 0.10
Darktable

While doing this, I set the PowerMizer mode in Nvidia Settings to Auto (i.e. Adaptive). Normally, I have it set to "Prefer Maximum Performance", but I turned that off for testing:

![image](https://user-images.githubusercontent.com/22120259/106855996-1fe73e80-66be-11eb-9dce-7d4aeb965b68.png)

GPU temperatures were barely affected by GZDoom, Darktable or Cool Spot, they stayed at around 50-55°C. While playing Cool Spot, they consistently stayed at 50. The power levels in Nvidia-Settings always hopped around between 0-4 during those programs.

**Now the kicker:**

When running Hocus Pocus in DOSBox Pure 0.10, the PowerMizer power level immediately jumped to 4 and stayed there throughout, while the temperature slowly, but steadily climbed from 50 to 63°C, where it then plateaued.

**Comment by mrmatteastwood** [comment]
Heya, so I went ahead and tested this with 0.9 as well, watching both GPU/CPU temps and the PowerMizer panel in Nvidia settings. Turns out 0.9 behaves the exact same way. In fact, I played a little longer this time and the temps kept climbing steadily, up to 68°, which was when I stopped.

![image](https://user-images.githubusercontent.com/22120259/106858670-4effaf00-66c2-11eb-9900-1f42acd6b759.png)

I've been forgetting to mention that CPU temps also tend to climb.

When I find time later today, I'll test this again with DOSBox-Core.

**Comment by schellingb** [comment]
Can you enable `Settings` -> `On-Screen Display` -> `On-Screen Notifications` -> `Notification Visibility`  -> `Display Statistics`
And then post screenshots of something running in DBP and something running in Snes9x?

**Comment by mrmatteastwood** [comment]
Fo sho!

![Screenshot from 2021-02-05 16-05-08](https://user-images.githubusercontent.com/22120259/107051549-de918480-67cc-11eb-84b2-3a5a37618117.png)

![Screenshot from 2021-02-05 16-09-23](https://user-images.githubusercontent.com/22120259/107051557-dfc2b180-67cc-11eb-97e9-da1174098bf2.png)

**Comment by mrmatteastwood** [comment]
Hey, I think I found a solution! Reading through these stats, I noticed that the DOSBox Pure framerate went through the roof (170ish FPS), while the SNES one was at 50. So I enabled Vsync in RA Settings > Video > Synchronization > Vertical Sync and now it's capped at 60. I tried for a few minutes and the GPU temp stayed at around 49°.

I would guess that was the problem! Without RA's vsync, there's no limit on DBP's FPS, so it goes up as high as the graphics card allows... I guess?

**Comment by schellingb** [comment]
Aha, this actually is a bug!
DOSBox Pure has some code to throttle a frontend that requests frames faster than the core asks it to but that was a bit broken.
Up until now it was intended to aim at 100 FPS while due to the bug it ended up reaching 170+ FPS.
But thinking about this some more, I don't think it ever needs to submit more than 70 frames per second (for DOS games that have a display resolution with a 70 Hz refresh).
So I'll fix the frame rate limiting code to limit it to the current emulated display refresh rate. That should help your case, hopefully it doesn't break things for others :-)
Thanks for not giving up on this issue and sorry for the late reply!

**Comment by mrmatteastwood** [comment]
Oh, cool! Well, I'm glad I helped discover the bug. :-) Yeah, I'd agree 70 FPS max. makes sense. And no worries, I had no doubt you were gonna reply whenever you could get around to it. Thanks to you for the continued awesome work!

**Comment by schellingb** [comment]
Finally got around to push this and version 0.11. Hopefully things are better with this now.
