### ISSUE TITLE
Keyboard double input (Issue)

### ISSUE THREAD

**Issue by aorin1** [schellingb/dosbox-pure#11]
I've tried 3 games so far, the first one being Duke Nukem 3D, in the pop up menu, pressing up or down makes the cursor scroll two times, so I can't select "uneven" options, the same happened in Blood, Alien Rampage ran fine, no issues in the arrow keys.
Ingame on Duke Nukem 3D, pressing up, it also pressed the map button which is Tab, so I figure there's some issues regarding input that need to be checked.
I couldn't get Blood to start since Blood.exe couldn't be selected due to the doubled input issue.

**Comment by schellingb** [comment]
Check the readme -> https://github.com/schellingb/dosbox-pure#playing-with-keyboard-and-mouse

**Comment by aorin1** [comment]
I should have read it, thanks a lot, the only reason I'm trying the keyboard is that I'm waiting for my gamepad, which should be coming soon, then I'll totally dig this core and its user friendly controls etc.
