### ISSUE TITLE
Request: support for Audio CD mounting

### ISSUE THREAD

**Issue by sergiou87** [schellingb/dosbox-pure#117]
Some games, like Little Big Adventure 2, rely on mounting game CDs as audio CDs. For that, as far as I know, the only thing needed is to include the [SDL Sound](https://www.icculus.org/SDL_sound/) dependency: 

https://github.com/schellingb/dosbox-pure/blob/16d93652b6909d07522077d1a7a22fdedffc00f1/src/dos/cdrom_image.cpp#L627-L644

The standalone DOSBox includes it, but not the Retroarch core (neither this or the [original](https://github.com/libretro/dosbox-libretro)).

**Comment by sergiou87** [comment]
Is there any way I can help with this? Can I contribute to your CI scripts where the core is built?

**Comment by sergiou87** [comment]
Related issue: libretro/dosbox-libretro#123

**Comment by evillurker** [comment]
LBA CD music both 1 and 2 works fine for me, you just have to make the right cue/bin files using cdmage and set the right audio settings in dosbox pure.

**Comment by schellingb** [comment]
I think this is a duplicate of #94
As I've mentioned in that repo it's not that easy to add OGG and MP3 support. First would be WAV support.
This core does not use SDL and even if, adding all the dependencies like sdl_sound, libogg, libvorbis, liblame etc. is not a road I would go down. For OGG I could see myself using stb_vorbis but support for MP3/FLAC I just don't know that a decent solution exists.

**Comment by sergiou87** [comment]
Ouch, sorry! Thanks for your quick answer, I'll close this in favor of #94
