### ISSUE TITLE
[Android] Blood FPS problems (Works fine with SVN)

### ISSUE THREAD

**Issue by evillurker** [schellingb/dosbox-pure#118]
Hello, thank you first of all for fixing previous problems that I mentioned (Like the start menu not showing right on android)

Today I fiddled with multiple settings while playing Blood and it keeps having huge fps problems (works fast, but then slows down severely to around 20 fps randomly)

Now you can say its a game problem but when testing using DOSBox SVN with default settings, the game runs smoothly with no problem - hence its a core problem.

If you can look into it i'll appreciate it as Dosbox pure is my go-to option for android emulation.

Thanks for your time <3

**Comment by schellingb** [comment]
It's a bit hard to say what is causing this with just this description. But it almost sounds to me like the phone is overheating and has to clock itself down which then would cause the FPS to go down. There is a chance that the (not yet released) fix I made for #107 would also help in this case.

**Comment by evillurker** [comment]
hey thanks for the fast response. Phone is not overheating, it's a galaxy a71 so its pretty capable of running anything.. DOSBOX SVN has 0 framerate drop but its controls are not the same and not as convenient as pure, this is why I am writing this.. it must be something with the core. I'll check what you posted

**Comment by mrmatteastwood** [comment]
Hey @evillurker, #107 is a bug where DBP's FPS go very high, which causes the graphics card to work much harder than necessary (for DOS games, more than 60 or 70 FPS is pretty much unnecessary).

That might be putting a lot of strain on your Android device as well, causing the stuttering.

Never used RA or DBP on Android, but on my PC, I worked around this problem by enabling vsync in RA's settings, which limits the FPS to 60, while waiting for DBP 0.11.

**Comment by evillurker** [comment]
> 
> 
> Hey @evillurker, #107 is a bug where DBP's FPS go very high, which causes the graphics card to work much harder than necessary (for DOS games, more than 60 or 70 FPS is pretty much unnecessary).
> 
> That might be putting a lot of strain on your Android device as well, causing the stuttering.
> 
> Never used RA or DBP on Android, but on my PC, I worked around this problem by enabling vsync in RA's settings, which limits the FPS to 60, while waiting for DBP 0.11.

Hey there, thanks for the help but I already got vsync set to on in my android retroarch and the problem still persists.
Will wait for a fix.

**Comment by schellingb** [comment]
@evillurker Can you retry this on your device with the latest version of the core? With the big changes regarding timing/video/audio synchronization and performance done through #184 this might have been resolved as well. Thanks.

**Comment by evillurker** [comment]
> @evillurker Can you retry this on your device with the latest version of the core? With the big changes regarding timing/video/audio synchronization and performance done through #184 this might have been resolved as well. Thanks.

Sadly I sold my android and no longer have the option to test things out. Maybe in the future when I get back to android emulation. Thanks for all the help!

**Comment by schellingb** [comment]
Haha, that's fine. I'll close this then for now. If someone has something similar, open a new issue or comment to #184. Thanks.
