### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by evillurker** [schellingb/dosbox-pure#119]
Is there a discord for dosbox pure support? would be very handy.

**Comment by schellingb** [comment]
I think the github issues is all the support I can give (and even that isn't easy to keep up) :-)
I am on the libretro discord and there is a chance other people could help there as well. Similarly the libretro subreddit and the libretro forums seem good places to ask for help, too.

**Comment by evillurker** [comment]
I am using it daily, if u need feedback or maybe direct bug reports i'd be happy to help.
EvilLurker#3059
