### ISSUE TITLE
No Glide API support?

### ISSUE THREAD

**Issue by paivaleonardo** [schellingb/dosbox-pure#12]
The games on Glide don't run, is a future implementation planned?

**Comment by schellingb** [comment]
At some point I want to evaluate the software rendering 3Dfx voodoo patch that is floating around.

Anything beyond that like converting this core to use hardware accelerated 3D rendering is probably not going to happen or a bit far off. There is another patch that uses external platform specific libraries seems too much of a hassle both for the implementation as well as the user so I'm not very interested in it.

**Comment by Darknior** [comment]
For sure 3D implementation will be complicated :(
And most of Dos games are in 2D :D 
But for the last one ... some are in 3D, and there are great games ... on a little hardware like a Raspberry PI it will be impossible to use. 3D rendering by using video card is important ... maybe some one specialist in 3D graphics can help you for this feature ?

**Comment by paivaleonardo** [comment]
I just thought it could be something like the Dosbox ECE, which supports 3DFX cards ... hardware rendering is kind of complicated, I didn't mention it itself, it was only support for games with a patch for Voodoo ... like Tomb Raider....
