### ISSUE TITLE
Cannot access Android storage in dosbox pure

### ISSUE THREAD

**Issue by 71knight** [schellingb/dosbox-pure#123]
When I run a game, dosbox pure puts me in the games directory. But I need to copy a file from my Android storage to the games install directory.  What command do I need to type to see my Android storage in dosbox so I can copy a file to the games directory?

**Comment by schellingb** [comment]
I have not tried this but maybe you could go to the command line and enter something like
```
mount S: /sdcard
S:
dir
copy <somefile> C:\<somewhere>
```
And see if you can access the Android storage that way.

**Comment by 71knight** [comment]
> I have not tried this but maybe you could go to the command line and enter something like
> 
> ```
> mount S: /sdcard
> S:
> dir
> copy <somefile> C:\<somewhere>
> ```
> 
> And see if you can access the Android storage that way.

Yes those commands worked very well... thank you!  

> I have not tried this but maybe you could go to the command line and enter something like
> 
> ```
> mount S: /sdcard
> S:
> dir
> copy <somefile> C:\<somewhere>
> ```
> 
> And see if you can access the Android storage that way.

Yes those commands worked very well.... thank you!

**Comment by 71knight** [comment]
> I have not tried this but maybe you could go to the command line and enter something like
> 
> ```
> mount S: /sdcard
> S:
> dir
> copy <somefile> C:\<somewhere>
> ```
> 
> And see if you can access the Android storage that way.

Yes those commands worked very well.... thank you!
