### ISSUE TITLE
Warning message will not go away!

### ISSUE THREAD

**Issue by 71knight** [schellingb/dosbox-pure#126]
When I run game a message comes up saying emulated CPU is overloaded please reduce cycles.  It's also makes this message when I simply run install.exe  program.  I have settings at 486 dx2 66 MHz at 100%.  My phone has 1.4 GHz octa core CPU.  Is my phone not powerful enough to run dosbox pure at these settings.

**Comment by schellingb** [comment]
Yes. if this warning pops up it means the emulation is not able to keep up with the setting. It means also that internal system like sound and video emulation are not correct to their targeted timing and especially sound can be very distorted. There isn't much to do than to lower the performance.
You can try to use the "Performance > Performance Scale" to find the perfect max setting for your hardware. Although in my testing it seems like different games can stress the emulation in different ways so it might work fine in one game but the warning can still appear in another one.
The Emulated Performance options "AUTO" and "MAX" should never show the warning (unless the hardware is extremely underpowered or there is a bug in either the core or the frontend).
I changed that the warning is only shown once per minute so it isn't an endless stream of popups.

**Comment by 71knight** [comment]
> Yes. if this warning pops up it means the emulation is not able to keep up with the setting. It means also that internal system like sound and video emulation are not correct to their targeted timing and especially sound can be very distorted. There isn't much to do than to lower the performance.
> You can try to use the "Performance > Performance Scale" to find the perfect max setting for your hardware. Although in my testing it seems like different games can stress the emulation in different ways so it might work fine in one game but the warning can still appear in another one.
> The Emulated Performance options "AUTO" and "MAX" should never show the warning (unless the hardware is extremely underpowered or there is a bug in either the core or the frontend).
> I changed that the warning is only shown once per minute so it isn't an endless stream of popups.

That's what I thought.  Okay thanks!
