### ISSUE TITLE
How to get smooth scrolling?

### ISSUE THREAD

**Issue by 71knight** [schellingb/dosbox-pure#128]
Cannot get stutter free smooth scrolling in games like jazz jackrabbit.  In my SNES9x and Sega Genesis GX cores, I have perfect smooth scrolling forever in games like final fantasy 2 and phantasy star 4.  Yes I tried all kinds of combinations of machine type and cycles, dynamic and interpreter.  I even tried fiddling with the refresh rate settings and latency settings in retroarch (those settings have a big effect on whether the game crackles or stutters).  Also tried audio sync and video sync on/off.  Is my Snapdragon 1.4 gigahertz CPU fast enough to emulate the 386 DX 33 Mhz? Does dosbox pure have vsync mode settings set such as host, internal, external timings?  I don't think that dosbox pure is interacting nicely with retroarch front end timing (Dynamic rate control and timing skew).

**Comment by n1ghttrap** [comment]
Using a high refresh (120hz+) monitor is pretty much the only way to brute-force achieve this in Dosbox Pure at the moment, and even then it's not perfect.

**Comment by 71knight** [comment]
> Using a high refresh (120hz+) monitor is pretty much the only way to brute-force achieve this in Dosbox Pure at the moment, and even then it's not perfect.

Well I guess I'm going to have to wait to play it on a G-sync  monitor on a computer instead of my phone.  I thought that my CPU being underpowered was the cause of the rough scrolling.

**Comment by iconoclusterdotexe** [comment]
The stuttering scrolling is caused by Threaded Video = on. It's helpful for low specs devices or PCs because it helps to speed up, but it causes a lot of latency, audio crackling and video stuttering. On a lot of cores there isn't any substancial difference when is ON, except for micro-stuttering video (especially with PAL games or PAL systems like C64 or Amiga, with using correct monitor refresh rate too).
When deactivated, you can notice a low latency and a perfect scrolling without any issues. Try it.

**Comment by 71knight** [comment]
> The stuttering scrolling is caused by Threaded Video = on. It's helpful for low specs devices or PCs because it helps to speed up, but it causes a lot of latency, audio crackling and video stuttering. On a lot of cores there isn't any substancial difference when is ON, except for micro-stuttering video (especially with PAL games or PAL systems like C64 or Amiga, with using correct monitor refresh rate too).
> When deactivated, you can notice a low latency and a perfect scrolling without any issues. Try it.
> Anyway, Dosbox-pure is still under public testing and i believe we can see a full support later.

I didn't have threaded video enabled when playing dosbox pure.  The video jerking appears every three or four seconds like when the scan line would reach the top of the screen during v blank on a crt.  But this is happening on my Android phone.

**Comment by iconoclusterdotexe** [comment]
> > The stuttering scrolling is caused by Threaded Video = on. It's helpful for low specs devices or PCs because it helps to speed up, but it causes a lot of latency, audio crackling and video stuttering. On a lot of cores there isn't any substancial difference when is ON, except for micro-stuttering video (especially with PAL games or PAL systems like C64 or Amiga, with using correct monitor refresh rate too).
> > When deactivated, you can notice a low latency and a perfect scrolling without any issues. Try it.
> > Anyway, Dosbox-pure is still under public testing and i believe we can see a full support later.
> 
> I didn't have threaded video enabled when playing dosbox pure. The video jerking appears every three or four seconds like when the scan line would reach the top of the screen during v blank on a crt. But this is happening on my Android phone. So this must be a frame pacing issue of some kind.

Hmm, for Android i cannot help you. I'm using it on pc and rpi4, i'm sorry 🙁

**Comment by redmist77** [comment]
I've been testing Pinball Fantasies and with G-sync, DOSbox Core scrolling is perfectly smooth but DOSBox Pure has stuttering.  Threaded Video is turned off in both cases.  I'm loving the zip system of Pure but jerky scrolling is a deal-breaker.

**Comment by dj5927** [comment]
In sync settings
When G-SYNC is turned on, it becomes very smooth.

However, many problems occur with other cores, so use only with PURE cores.

**Comment by n1ghttrap** [comment]
That is not advisable.  Gsync can be used everywhere in retroarch and is
recommended.

**Comment by n1ghttrap** [comment]
It's because the core doesn't run in the content's native framerate.  It
runs at your refresh rate but fits the frames into them.  Hence, it looks
better if you run at a high refresh rate like 120hz+ but still judders a
bit, and looks like complete trash at 60hz because there the refresh rate
isn't high enough to display the usual 70.  It still needs to be fixed.
Issue has been ongoing and noted for months and it works fine in the
original core and standalones.

**Comment by WarlockSVG** [comment]
Try this
At "video" "output" use the option "Set Display-Reported Refresh Rate" to set "Vertical Refresh Rate" to the reported frame rate.
At "video" "synchronization" I have "Vertical Sync" and "Sync to Exact Content Frame rate" On

This gives me a decent "smooth" result for "jazz jackrabbit" did not tried others.

**Comment by handlolo** [comment]
You can't just because computers under msdos didn't either, almost all games didn't have smooth scrolls, I just remember turrican 2 with decent scrolling. Msdos pure is possibly the best core in all of Libretro.

**Comment by handlolo** [comment]
> > You can't just because the computers under msdos didn't either, almost all the games didn't have smooth scrolling, I just remember turrican 2 with decent scrolling. Msdos pure is possibly the best core in all of Libretro.
> > Also keep in mind that many developers disabled vsync and that games had decent performance by software. The pc under msdos did everything by software and was pessimus for these tasks.
> 
> Pinball Fantasies is perfectly smooth in DOSBox Core but not in DOSBox Pure. As mentioned above, DOSBox Pure does not currently support external timing which is needed for GSync/Freesync/VRR support. Many DOS games run at ~70Hz so they stutter quite badly without GSync/Freesync/VRR.

im getting perfectly smoth in pinball fantasies, epic pinball and Turrican 2 in a Linux system in 15 khz by example, but Jazz Jackrabbit never get smooth scroll, because in the original ms-dos havent it

**Comment by schellingb** [comment]
Closing this old issue for now. Please open a new ticket if new issues along these lines come up. Thanks.
