### ISSUE TITLE
Alien Carnage not work

### ISSUE THREAD

**Issue by ToniBC** [schellingb/dosbox-pure#140]
Everything tested with Dosbox Pure 0.12, Windows 10 x64 and everything Nightly, cores and RA. I update it every day.

The Alien Carnage game does not work, the game loads, shows the menus, but when you start Mission 1 it stays loading in a loop and does not advance, with dosbox SVN and Core in Retroarch, the game does load.

![Alien Carnage (1993)-210425-103734](https://user-images.githubusercontent.com/45365478/115986880-be46ba00-a5b2-11eb-84d4-715fc97771f5.png)

It could be something related to saving, because before it starts, it exits to save, but in Pure it loops loading.

![CARNAGE-210425-103835](https://user-images.githubusercontent.com/45365478/115986889-c7378b80-a5b2-11eb-88d6-dea3406b5c27.png)

And tried with various combinations in the options, to no avail.

Thanks.

**Comment by WarlockSVG** [comment]
I just tested this... and I have the same problem.

**Comment by WarlockSVG** [comment]
I just tested this... and I have the same problem.
I can see an error msg when the loading screens loops. runtime error 203 at 14C8:0011

Same game runs fine on DOSBox-X.

**Comment by schellingb** [comment]
Wow this game has lots of issues that don't occur in real DOSBox at all, huh.

For me, besides the problem mentioned, I can't watch the entire intro. The screen after the lady turns green glitches out and then the game hangs while some red graphics bug keeps scrolling across the screen. Also the instructions screen crashes after turning the page a fourth time. Opening and closing the instructions screen crashes the third time.

I'm very curious to what is causing this. This game runs fine in real DOSBox which this core should be very similar in terms of emulation support/behavior. As for now I don't really have an idea what's wrong but it's easily reproducible so it's only a matter of having the time to compare the behavior of DOSBox Pure to real DOSBox or the DOSBox-SVN core.

**Comment by WarlockSVG** [comment]
"Real DOSBox"
... sound like DOSBox Pure is not "REAL" :-(

I would refer to DOSBox as "DOSBox" or "The original DOSBox", "DOSBox" Pure is also REAL. It exists so it's real ;-)

**Comment by mrmatteastwood** [comment]
Hey guys! The game works perfectly for me. I remember it took some tinkering when I first set it up though. Here are my Core Options for this one:

![ra-settings-001](https://user-images.githubusercontent.com/22120259/116882712-0c983080-ac25-11eb-86cb-615c7db8717c.jpg)
![ra-settings-002](https://user-images.githubusercontent.com/22120259/116882715-0d30c700-ac25-11eb-9fe5-0546f79e4007.jpg)
![ra-settings-003](https://user-images.githubusercontent.com/22120259/116882716-0dc95d80-ac25-11eb-9115-c7cc9ea48ada.jpg)
![ra-settings-004](https://user-images.githubusercontent.com/22120259/116882718-0dc95d80-ac25-11eb-8a33-c19a9098cea5.jpg)

**Comment by schellingb** [comment]
@WarlockSVG I mean original standalone DOSBox, which this libretro core is based on :-) But I guess you got that.

Anyway, good news I found out what was wrong and fixed it in c18c4dd 🎉. Hoping to make a new release tomorrow.

@mrmatteastwood I'm surprised it works for you 😮 It was a bug/complication how the game depends on creating and deleting swap files and then checking the file handle of deleted files... Seems to me a rather weird behavior but good that it is corrected now.

**Comment by mrmatteastwood** [comment]
Hey, glad it's fixed! :-)

**Comment by WarlockSVG** [comment]
@schellingb Do you have sound as wel... With "DOSBox Pure" there is no sound, even at startup of the game... With DOSBox-X I have sound.

**Comment by schellingb** [comment]
@ToniBC @WarlockSVG The fix is now in the new released 0.13. Please give it another try, thanks.

**Comment by ToniBC** [comment]
Everything seems to be working properly. Thanks.
