### ISSUE TITLE
"Custom keyboard + Mouse on left/right stick" control device profiles, lack mouse bindings.

### ISSUE THREAD

**Issue by Denshadego** [schellingb/dosbox-pure#142]
It's awesome that now we have the options "Custom keyboard + Mouse on left/right stick" for games that use both mouse and specific keyboard inputs, however, only custom keyboard bindings can be assigned to buttons, with no option for assigning mouse axis and buttons to the control.
This would be useful for example, if one wants to use the mouse on a dpad/digital only game-pad and/or be able to assign the mouse buttons to other buttons on it as it can be done on the "Mouse with right/left analog stick" presets, but those sadly lack a lot of keyboard buttons.

**Comment by demodanza** [comment]
I should add, the same profiles, "Custom keyboard + Mouse on left/right stick", also lack the option to set "onscreen keyboard" to any button. Not all gamepads have L3/R3 buttons, so the option to map it to, let's say, select, should be available.

**Comment by williambroad** [comment]
Hello there.
I have just recently stumbled over this awesome RetroArch core and have been testing the hell out of my DOS games. So far a lot of stuff just works perfectly out of the box, but trying out a game like Lands of Lore I discovered the above mentioned issue and was wondering if I overlooked anything - and here I am...
Is this still something that will be able to be resolved or possibly has already been put into the controls setting? I looked for it and couldn't find anything that provides a fully emulated mouse (with left and right mouse button) AND a fully customizable keyboard mapping. That would be just great!

**Comment by Enemby** [comment]
I am also searching for this. My idea was to have a .COM program in the autoexec for my dosbox install that allows you to hold a button and turn the arrow keys (dpad on my device) into a mouse axis. I've found that an option might exist, but is so poorly documented it'll be hard to use. It was called "KME_BETA.ZIP", and seemed to imply keyboard mouse emulation support. But hard to say.

If this kind of option came native in Dosbox Pure, suddenly almost every libretro device has full gameplay support for most dos games.

**Comment by schellingb** [comment]
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.
