### ISSUE TITLE
[Windows] Restarting or closing a game will cause Retro Arch to hang when on the DOS prompt screen

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#143]
With any game i try (over 15 so far) DOSBox Pure will cause Retro Arch to permanently hang/freeze when i'm on the DOS command prompt screen, simply by pressing F1 and going on 'Restart' or 'Close'. RA will immediately hang and the only way to get out of it is to hit CTRL+ALT+DEL and force close RA. Task Manager will also say that RA is not responding.

But so far this only seems to happen when starting a game with a .BAT/batch file. For example, like many DOS games, Doom comes with a run.bat file. If you run this file with DOSBox Pure it will display options for starting Doom (e.g "Press 1 for Sound Canvas. Press 2 for Sound Blaster" and so on). While on this options screen, if you press F1 and try to restart or close, RA will hang.

The DOSBox SVN core doesn't hang though. I can restart/close any game without issue.

So far i've tried:
Vulkan, GLcore and GL display drivers
RA 1.9.1
A separate clean install of RA 1.9.1
Latest RA nightly build
Latest core updates

I've attached the Doom batch file, but any similar batch file will also cause the hang.

[run.zip](https://github.com/schellingb/dosbox-pure/files/6378798/run.zip)

**Comment by schellingb** [comment]
Thanks for reporting this.
Yes totally during the CHOICE command (the one that presents 1,2,3,... options) it won't react to the shutdown request and will hang indeed. Fixed in code, will be in the next release.

**Comment by PoloniumRain** [comment]
Speedy fix! Nice.

Thanks for your work on this amazing core btw. Best way to play DOS games by a mile.
