### ISSUE TITLE
Restarting any game will stop the CD audio from playing

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#144]
Any game that plays audio/music from a CD will stop playing that music once i press F1 and go on 'Restart'. The sound effects will still play (probably because they're not on the CD) but the CD music no longer works. It's as if the CD drive is no longer mounted, but DBP says the drive is still mounted. I'm also guessing that video _might_ not work as well, being as that is often stored on the CD too, but i haven't tested that yet.

So far i've tried the below games because they all use CD music, and every one of them will stop playing music after a restart.

Quake
Mortal Kombat 3
Mortal Kombat Trilogy
Blood
Screamer 1/2
Screamer Rally
Wipeout
Earthworm Jim 1/2
FX Fighter
Fatal Racing/Whiplash

I'm using Windows and have tried:
RA 1.9.1
Latest RA nightly build
Latest DBP core update

The problem occurs on all of them.

Edit: Forgot to mention that the CD audio will work again if i just close and run the game again. It's only when restarting a game that the music stops. Quake is a good game to use to replicate this issue as the CD music will immediately play after starting the game. If you then restart it will no longer play.

**Comment by schellingb** [comment]
Should be fixed in 0.13, please check it out.

**Comment by PoloniumRain** [comment]
> Should be fixed in 0.13, please check it out.

Yep it's working. I've tried all the games listed in my first post and the CD audio always plays after a restart. Thanks once again for yet _another_ fast fix.
