### ISSUE TITLE
Keyboard unusable

### ISSUE THREAD

**Issue by WarlockSVG** [schellingb/dosbox-pure#146]
I'm unable to use my keyboard.
I'm running Windows 10 and have a Belgium ( period ) keyboard.
Retroarch 1.9.1 DOSBox-pure (0.12)

When I'm in dosbox pure my keyboard is totally unusable. Most of the keys appear to do nothing and the ones that do something are not "producing" the key (character) I pressed on.

I tried all different "input / control" settings nothing helps.
I'm using "France" as the Keyboard Layout at the options for DOSBox-pure because Belgium ( BE ) is not available.

This is a quick overview for the keys a to z 0 to 9 ( the ones not listed appear to do nothing )

When game focus is off
a = &
z = é
s = "space"
d = "esc" (most likely not 100% sure)
g = "home" (most likely not 100% sure)
J = -
k = arrow left
m = arrow right
n = +

When game focus is on

r = 0
i = 9
o = 1
p = 2
q = 3
s = .
d = "esc" (most likely not 100% sure)
g = 7
h = 8
j = -
k = 4
l = 5
m = 6
n = +
esc = $a

When game focus is "on" or "off"
"top" row of the keyboard ( not the num keypad )

1 = n
2 = ,
3 = ;
4 = :
5 = !
7 = *
9 = "space"
0 = b

And keys like "CTRL" "ALT" "ALT Gr" "shift" "page up" "page down" "home" "end"... and the arrow keys are also not working the way they should.

**Comment by PoloniumRain** [comment]
Same problem here. It happens with all games, and i'm also using Windows 10, RA 1.9.1 and DBP 0.12, but with a UK keyboard and layout. I've also tested this with the latest Retro Arch nightly build using completely default settings and it happened with that.

Here's one example: 
Run Doom, then press the Enter key at the main menu screen - It does nothing.
Switch to 'Game Focus' mode (Scroll Lock key) - Enter still does nothing.
Get the DBP on-screen keyboard up with my Xbox controller (press left analog stick), then close the on-screen keyboard. Now my keyboards Enter key will finally work.

As WarlockSVG already mentioned, some keys might work but they have incorrect inputs. For example, the down arrow key changes the screen size in Doom (it shouldn't), but with Game Focus enabled it will then correctly move you backwards. Basically Game Focus can get most keys working and working with the correct input, but not **all** keys (like the Enter key in the Doom example).

To get everything working i need to enable Game Focus and get the on-screen keyboard up, then close it. That seems to fix everything for each game i've tried so far.

**Comment by WarlockSVG** [comment]
> To get everything working i need to enable Game Focus and get the on-screen keyboard up, then close it. That seems to fix everything for each game i've tried so far.

This does not work for me :-(

**Comment by PoloniumRain** [comment]
> > To get everything working i need to enable Game Focus and get the on-screen keyboard up, then close it. That seems to fix everything for each game i've tried so far.
> 
> This does not work for me :-(

Hmm keyboard seems to work with Retro Arch 1.9.0, although i've only had time to try 2 games so far so can't say for certain yet. Maybe give 1.9.0 a try?

**Comment by WarlockSVG** [comment]
> Hmm keyboard seems to work with Retro Arch 1.9.0, although i've only had time to try 2 games so far so can't say for certain yet. Maybe give 1.9.0 a try?

Tried it and AR 1.9.0 seem to work when "game focus" is on.
Tried also AR 1.9.2 but that does not work either like AR 1.9.1

**Comment by mrmatteastwood** [comment]
fwiw, just tried RA 1.9.2 and DBP 0.12, Colonization, everything worked swell regardless of whether Game Focus was on or off. German keyboard.

**Comment by PoloniumRain** [comment]
> Tried it and AR 1.9.0 seem to work when "game focus" is on.
> Tried also AR 1.9.2 but that does not work either like AR 1.9.1

Same here. I tried RA on a old laptop as well and get the same problem as my desktop PC. Both are Win 10 and UK keyboard. But i noticed that DOSBox SVN and DOSBox SVN CE don't work properly unless Game Focus is on, it's similar to the DBP problem and i think DBP is based on SVN? Looks like RA 1.9.1 onwards has messed something up with DOSBox or SVN based cores. No other cores have keyboard problems.


> fwiw, just tried RA 1.9.2 and DBP 0.12, Colonization, everything worked swell regardless of whether Game Focus was on or off. German keyboard.

Did you try any other games?

**Comment by mrmatteastwood** [comment]
Also tried Lemmings, Boppin' and Crazy Drake, no problems.

Shot in the dark, but what happens if you guys reset your RA config to "factory settings"? Just move the retroarch.cfg from its folder to somewhere else, then start RA, you'll have a completely fresh config. Same issue then?

**Comment by WarlockSVG** [comment]
> Also tried Lemmings, Boppin' and Crazy Drake, no problems.
> 
> Shot in the dark, but what happens if you guys reset your RA config to "factory settings"? Just move the retroarch.cfg from its folder to somewhere else, then start RA, you'll have a completely fresh config. Same issue then?

Did a quick test with a clean RA 1.9.2 setup and it looks like this works when game focus is on.
Only the key with "backslash" "is greater than" and "is smaller than" ( \ &gt; < ) is not working. Need to use the "ALT+092" code to produce the backslash it.

... why did this slip my mind... it's one off the basics to trouble shoot.

Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble. Start clean if run in to trouble.

;-)

**Comment by PoloniumRain** [comment]
Glad ya fixed it @WarlockSVG.

I still have the Enter key problem mentioned in my first post, even with clean Retro Arch installs on separate PC's, but after doing further testing it seems unrelated to your problem and it only happens under very specific conditions. It's really odd. I don't have time to write a fat long post explaining it now though and i'll probably just open a new issue/thread when i have time.

**Comment by WarlockSVG** [comment]
> Glad ya fixed it @WarlockSVG.
> 
> I still have the Enter key problem mentioned in my first post, even with clean Retro Arch installs on separate PC's, but after doing further testing it seems unrelated to your problem and it only happens under very specific conditions. It's really odd. I don't have time to write a fat long post explaining it now though and i'll probably just open a new issue/thread when i have time.

I got the same thing with the enter... but the enter key from the num pad works straight away.
... is there a way to remap keyboard keys in DOSBox Pure like in the classic DOSBox by using the mapper to remap keys?
