### ISSUE TITLE
"Screen shot" "save state" / crashing problem.

### ISSUE THREAD

**Issue by WarlockSVG** [schellingb/dosbox-pure#148]
Whenever I "make" a save state, AR crashes.

The save state file is created and can be loaded. The problem is with the screen shot that is made along with the save state. Making just a screen shot ( pressing F8 ) also does crash AR.

The following error is produced when AR crashes.
Exception code=0xc0000005 flags=0x0 at 0x00007FFA85100551. Access violation - attempting to read data at address 0x00000000000000A8

Did a quick test with the following cores "snes9x_libretro.dll" "mednafen_psx_hw_libretro.dll" and"pcsx_rearmed_libretro.dll" and that works fine taking screen shots of making a save state.

**Comment by WarlockSVG** [comment]
... this is related with the Output mode of the video.
when I have it set to vulkan the crash happens. when set on gl it works to take a screenshot.

**Comment by schellingb** [comment]
Does this still apply to the latest version of RetroArch and this core?
