### ISSUE TITLE
Rewind unreliable

### ISSUE THREAD

**Issue by vvhitecrow** [schellingb/dosbox-pure#150]
Rewind seems to work fine for awhile and then its like it gets stuck on a single frame and stops recording new history. I will be playing for awhile and go to hit rewind and it will instantly jump back to the last time I hit rewind over an hour ago. I can go into the menu and disable\enable rewind again and its starts working fine again for about 20 minutes and then same thing again, jumps back to the last time I hit rewind 10 minutes ago. Been playing mostly Commander Keen series but its happening on all games I try. I tried installing a fresh version of Retroarch and just this core with everything else disabled to see if its something with my setup and its still happening. Rewind is also working fine on the other 14 cores I have setup, any idea what is causing this?

**Comment by vvhitecrow** [comment]
rewind has completely quit working for me now. however I am now getting an error which might be helpful. see attached for logs.
[retroarch-log.txt](https://github.com/schellingb/dosbox-pure/files/6438352/retroarch-log.txt)

[ERROR] [Environ]: SET_MESSAGE_EXT: Load State Error: Unable to load state made while DOS was not running

**Comment by eadmaster** [comment]
same issue here

**Comment by schellingb** [comment]
Did you set the core option "Save States Support" to "Enable save states with rewind"?

Save states in DOSBox are not an easy thing, let alone rewinds. It's a very complex state to save. To be honest, I'm quite surprised I got this running as well as it does. If you get the error "Unable to load state made while DOS was not running" it probably tries to rewind out of the game into the DOSBox Pure start menu or into the command line. Exiting out of a DOS program with save states is not possible - thus the error.

Can I reproduce this by just running Commander Keen for an hour? What are your settings in the rewind settings in RetroArch? Frames, buffer size etc.

**Comment by vvhitecrow** [comment]
I will check my exact settings later today when I get home. if I remember right, this was happening on commander keen after 20 min on default settings.

**Comment by eadmaster** [comment]
i've just tried the [latest build on buildbot](https://buildbot.libretro.com/nightly/linux/x86_64/latest/dosbox_pure_libretro.so.zip), and it seems to work properly only if i disable and re-enable "Rewind Support" from the Rewind menu ([same workaround needed here](https://github.com/libretro/vice-libretro/issues/394)).

**Comment by vvhitecrow** [comment]
Yep, that worked for the first couple times and now even that doesn't seem
to help. I don't know what it is that breaks it.

**Comment by ckeisc** [comment]
@schellingb - I also have experience very similar to what's being reported here. If you need more data point on getting a repro, this is my set up that I tend to repro the problem as early as in the intro cut scene.

Platform: Xbox (Series X) retail, so it's the windows UWP build, 1.9.9, DosBox-pure (0.15), the cores are built into Xbox builds and cannot be upgraded.

Game: Another World
Configuration: 
- Retroarch Rewind Support enabled, default frame/buffer size (1 frame/20 MB). 
- Core Settings "Save States Support" set to "Enable save states with rewind". Restarted the entire Retroarch app after change.

Pretty consistently, the first rewind after the game starts (I usually do it in the intro cut scene where the car stops in front of the lab) would fail with "Load State Error: Unable to load state made while DOS was not running."
After this error message was shown, press rewind hotkey would "rewind" to a fixed point when I initiated the first rewind (more like a restore state). I can recover from this state by turning off Rewind Support in Quick Menu, resume the game and then turning on the Rewind Support again from Quick Menu, and then the rewind would start to work, at least for a little while. Every once a while, it would stuck at a single point in time again.

The behavior seems the same between the core option "Enable save states" and "Enable save states with rewind", meaning that as long as I disable and re-enable "Rewind Support" from Quick Menu, I could get rewind working for a little while whether I chose "Enable save states" or "Enable save states with rewind", and both would stop working after a few minutes and rewind would behave like restore state.

**Comment by schellingb** [comment]
Thanks @ckeisc for the detailed analysis. There is a technical explanation but it's not fun...

The size of a DOSBox Pure save state fluctuates a lot, based on how much of the emulated RAM is in use and what hardware is actively being emulated. It can be 1MB or up to 29MB (on the default 16MB memory size setting).

Now, the RetroArch rewind system, as far as I understand, it initially measures the size of the save state and assumes that is the maximum possible size of a save state. So DOSBox Pure tries to be clever and if it sees the frontend requesting the save state size before the core is fully started, it assumes that is RetroArch measuring the maximum size. So it returns 29MB for that. When RetroArch sees that 29MB being larger than the rewind buffer size it basically gives up on rewinding.

So now we disable and enable "Rewind Support" in the Quick Menu and what happens? It's important to note that DOSBox Pure really has no idea about rewinding. On re-enabling rewind support, RetroArch tries to get the maximum size of the save state again. But now DOSBox Pure just returns the size of the current state. Then once the emulation has advanced a bit further, the size of the state can get bigger, and at that point RetroArch gives up on rewinding again.

So what is the solution? The only way I see out of this is to always returns the maximum possible save state size when setting "Enable save states with rewind". This will also make regular save states much larger but not so much in RetroArch if the setting "Save State Compression" is enabled (which is the default on most platforms).

But it will never work with the default "Rewind Buffer Size" setting of 20MB. I will make sure to add a comment about that into the core option about save states. Should be at least 40MB, but even that will only store a few states.

**Comment by schellingb** [comment]
If someone could try out rewind with the newly released version 0.17 and report back if things have improved. Make sure to set the "Rewind Buffer Size" in RetroArch to at least 40MB.

**Comment by ckeisc** [comment]
Thanks for the detailed info @schellingb. I found that after just dialing up rewind buffer size based on your explanation above, rewind works well for me even on 0.15. I haven’t played for hours but I have gone 30 minutes of rewinding every couple minutes (such as the norm for playing Another World) without problem. The implementation is solid, just the default rewind buffer is too small. I also dialed down the default ram from 16MB to 4MB which is more than enough for games I run. Not sure if that lessens rewind buffer demands.

**Comment by schellingb** [comment]
Good to hear. Thanks for testing!

Reducing RAM by 12 MB will lower the overall size (so rewind might even work for a short amount with a 20MB buffer). But RetroArch compresses the incoming state data so the result doesn't change by much. The unused RAM is all zero bytes so it adds nothing to the actual data stored in the rewind buffer.

During some extended automated testing (automated rewinding 30 milliseconds, forwarding 50 milliseconds) I encountered one weird case where the game in DOS crashed but I'm unable to reproduce it. The problem is as soon as the game process ends, DOSBox Pure by itself is unable to load back into a state where the game is running so a user encountering such a crash can't even rewind. I'm looking for a way to mitigate that by somehow auto restarting the game in case a rewind is requested. But that will have to wait until #184 is complete because that one will change a bunch of internal workings of the core.

I'll ask over at RetroArch if it would make sense to add a warning that pops up if a cores state is more than the rewind buffer. It seems quite unclear to a user as it is currently.

**Comment by vvhitecrow** [comment]
Finally got around to messing with this again today and after bumping up the buffer and then disable\enable rewind its working flawless again, so awesome, thank you so much for putting this out into the world.
