### ISSUE TITLE
The Enter key will not work with many games

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#152]
I've got a weird problem with the Enter key not working and i've spent 2 hours trying to narrow down what causes it because it's annoying. The problem only seems to happen when i use the DOSBox Pure 'Start Menu' screen (where you can browse files and load/mount images and so on). While on this screen if i start a game by pressing Enter then the Enter key will no longer do anything when the game is running.

To replicate the problem i'll use Doom as an example:
First make sure that the DOSBox Pure core shows the Start Menu before a game starts.
Run Doom and at the Start Menu select DOOM.EXE and press Enter.
When Doom is running press Enter and it will do nothing.
Switch to 'Game Focus' mode (Scroll Lock key) and Enter will still do nothing.
Whatever button the Enter key is mapped to on a controller will also do nothing.

This happens with:
RA 1.9.1 (clean install)
RA 1.9.2 (clean install)
Latest RA nightly (clean install)
DBP 0.12 and 0.13
RA in windowed mode and fullscreen
GL, GLcore and Vulkan display drivers
2 different PC's (both have UK keyboards)
Windows 10 (haven't tried another OS)

There's 6 ways i've found to avoid or get around this problem: 
1. Use RA 1.9.0 and not a newer version.
2. Use 'Set Auto Start' to skip the Start Menu screen on subsequent game runs.
3. On the Start Menu use a controller or left mouse button to start a game and **not** the Enter key.
4. **Before** a game is started, enable Game Focus on the Start Menu.
5. After starting a game open the DBP on-screen keyboard and then close it (press the left analog stick twice on a controller). The Enter key will now work.
5. @WarlockSVG also [mentioned](https://github.com/schellingb/dosbox-pure/issues/146#issuecomment-832302545) the numpad Enter key works (but i don't have any keyboards with number pads).

This problem strangely doesn't happen with every game either, but it happens with a large percentage of games, and some are:
Doom
Doom II
Hexen
Quake
Tomb Raider
Screamer 1 and 2
Earthworm Jim 1 and 2
FX Fighter

**Comment by WarlockSVG** [comment]
Try...  Settings --> input --> auto enable 'Game Focus' Mode set to on.
This will turn Game Focus on when you start an "Dosbox pure" emulation. This works for me when 'Game Focus' is on, the enter key works.

Wat does not work for me is shift+F10 ( that is to quit in Norton commander ) ... but when I turn off "Game Focus" it works.

**Comment by schellingb** [comment]
@PoloniumRain  Thank you for the detailed description, really helpful!
The important parts that cause the issue are:
- enter key bound to retropad start button
- game with auto key remapping that maps start button to keyboard enter
- not using game focus in the start menu
- using enter key to confirm start menu selection

The committed fix will be in the next release.

**Comment by PoloniumRain** [comment]
> The committed fix will be in the next release.

Looking forward to it! This has been driving me mad. 

And lol, all my posts are barely up a few hours and you've fixed the issue already. Thanks again.
