### ISSUE TITLE
[Android] Vertical stripes all over Carmageddon

### ISSUE THREAD

**Issue by Denshadego** [schellingb/dosbox-pure#156]
When playing Carmageddon the entire game, menus and ingame, is covered by vertical stripes. Changing the game resolution to high res only reduces it a little ,but there's still lines all over the place. Tried changing every setting and back to default but no luck.

![Carmageddon Max Pack-210511-003853](https://user-images.githubusercontent.com/47835860/117611233-222fbd80-b131-11eb-827b-c98c3a7ad9b1.png)

As it doesn't happen in Windows went to Google and the only place I could find info about the glitch was in this forum:
https://www.linuxquestions.org/questions/linux-games-33/carmageddon-dosbox-vertical-stripes-bad-performance-742334/
Some of the answers say it may be an undesirable effect of using the 64 bits version of dosbox , which made me wonder if the versions of dosbox pure on the windows and Android cores are not the same, as another game Frontier - First Encounters crashes for me on Android only.
 
Beyond that the game runs fine at Pentium II speed, but the lines make it unplayable. Hope something could be done to alleviate this.

My android device:

Mipad 4, MIUI 10.3.2
Android 8.1.0
3 GB ram, Octa-core max 2.20 GHz, Armv8
Latest retroarch stable build, gl driver.

**Comment by toniosj** [comment]
Same problem on Raspberry Pi 4.

**Comment by WarlockSVG** [comment]
![carmageddon (1998)(interplay)(iso)-210523-151316](https://user-images.githubusercontent.com/33853101/119261911-ab3b0000-bbd9-11eb-8767-aaeda873874e.png)
Runs fine on my windows system.
I not sure if it will help you, but I replaced "DOS4GW.EXE" on my disc iso with the one from "DOS32A 9.1.2"

**Comment by demodanza** [comment]
Thanks for the advice, just tried it, but sadly it still happens. And yeah, it works fine on windows, it's on android that the stripes appear.

**Comment by Morphey008** [comment]
Is from 64bit CPU on smartphone. 32bit RetroArch (or other DosBox android application) on 64bit CPU not help for this.
3Dfx Voodoo help for 3D part game. In game folder place correct glide2x.ovl, run carmaV.exe.
See 3Dfx logo on start screen. If crashes in game, replace DOS4GW.EXE and run with carmaV.exe -low

**Comment by Denshadego** [comment]
Hi! Seem this glitch was fixed last week on staging https://github.com/dosbox-staging/dosbox-staging/pull/3151

**Comment by trr** [comment]
Sorry to noise up this issue but just wanted to get clarification if this is presumed fixed or still in progress?  Can confirm I'm having this issue on current dosbox-pure on Android and came here after reading how they fixed it on dosbox-staging @ https://github.com/dosbox-staging/dosbox-staging/issues/1231

**Comment by schellingb** [comment]
The fix is now released in the newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and on the RetroArch online core downloader.
