### ISSUE TITLE
Enable Gravis Ultrasound?

### ISSUE THREAD

**Issue by MrRyuu** [schellingb/dosbox-pure#157]
Hi, Pls, I would like to know how I can enable the Gravis Ultrasound in DOSBox Pure. I have tried to put the “ULTRASND” folder inside the game folder, but it not work.

I would appreciate any help.

THANKS IN ADVANCE.

**Comment by NightSprinter** [comment]
In the Quick Menu, you'll need to go to "Core Options", "Audio", then second-to-last option will be to enable the GUS.  Just remember you'll have to restart the content for the changes to reflect.  
![Retroarch-1](https://github.com/schellingb/dosbox-pure/assets/52381903/c7b96b5b-c78b-45de-b0b0-76f63752640e)
![Retroarch-2](https://github.com/schellingb/dosbox-pure/assets/52381903/0691eef8-0fb2-496c-a9d1-23e8a3c2d007)
![Retroarch-3](https://github.com/schellingb/dosbox-pure/assets/52381903/fba2e65b-9058-477b-9fd0-5fccfa6d66f7)
