### ISSUE TITLE
Double buffering? suffering tearing

### ISSUE THREAD

**Issue by ghost** [schellingb/dosbox-pure#160]
Hi, while dosbox is used to produce tearing, I think we should be able to change some of the dosbox settings from retroarch , some of the settings that plain dosbox have. double buffering would be an excellent feature to have bc the tearing is quite notorious on the rpi4.

another thing, why you do not had chosen an especial extension like .dzip so we dont have to hide the save.zip ones from retropíe/retroetc after we launch a game. 

amazing project.

pd I saw your tip about the extensions . thabks

BC I read already about the not being able.to use a dosbox config.file.. can you emplain me how to force double buffering on compilation. or offer it as an option inside retroarch would be a good option too.

**Comment by schellingb** [comment]
I think this has been resolved by the changes made with #184. Will close this now. If there are still similar related problems, open a new issue or add a comment to 184. Thanks.
