### ISSUE TITLE
[On-screen keyboard] press and hold multiple keys?

### ISSUE THREAD

**Issue by trebrick** [schellingb/dosbox-pure#169]
Is it possible with the onscreen keyboard to press and hold multiple keys at once? Trying to enter a cheat which requires that action and would rather not have to change the input and bind the specific keys. Thanks

**Comment by Xbox-Series-X-User** [comment]
I have an idea on how this would be implemented... just if you long press any key it is held and on exit of the virtual keyboard it ends input like normal

**Comment by trebrick** [comment]
Awesome, works like a charm!

**Comment by mrmatteastwood** [comment]
Hey @schellingb, I added this info to the DOSBux Pure readme doc I've been working on:
https://github.com/mrmatteastwood/docs/blob/DOSBox-Pure-doc-WIP/docs/library/dosbox-pure.md

Let's get this one finished up and submit a pull request to the libretro docs maintainers! It would be awesome if DBP had its own readme in the official libretro docs, and I feel I've gotten really close to that. All that's needed is some final input from you. :-)

**Comment by schellingb** [comment]
@trebrick Thanks for confirming, I'll close this then.

@mrmatteastwood Thanks!! I (finally) replied to #50 👍
