### ISSUE TITLE
Time Commando not working

### ISSUE THREAD

**Issue by aorin1** [schellingb/dosbox-pure#17]
I got this game working on the normal Dosbox core and it was a little trickier to get the .conf file ready for that, but in Dosbox pure, it won't mount the cue/bin/iso file at all. So, trying to start via the exe will just prompt for the mounted CD.

**Comment by schellingb** [comment]
Chances are that was fixed in 0.3, please try again with the latest release.

**Comment by aorin1** [comment]
Working great now, specially after fine tuning the CPU, RAM etc., I also noticed it loaded the .conf file like the normal DOSBOX, this core has a bright future ahead.

**Comment by schellingb** [comment]
Awesome, great to hear!

Don't be mistaken, DOSBox Pure currently does not touch or handle any .conf file, it doesn't even know how to load it :-)

**Comment by aorin1** [comment]
> Awesome, great to hear!
> 
> Don't be mistaken, DOSBox Pure currently does not touch or handle any .conf file, it doesn't even know how to load it :-)

You're right, the fact I thought it loaded via the .conf file is because I had the DosBox Svn core and it loaded the file instead, but when I zipped up the Time Commando folder, it was Dos Box pure, in any case, it's nice to see this tricky game (which I only managed to run under Dos Box following really old (10 years-) posts with the correct commands, since this game won't load like other CD based games, for some reason.
