### ISSUE TITLE
Need more ram

### ISSUE THREAD

**Issue by Xbox-Series-X-User** [schellingb/dosbox-pure#171]
is it possible to increase the ram? 128mb is the minimum for some windows 98 games and getting win98 was hard enough and the other cores don't have a virtual keyboard which i need

**Comment by Milenko7** [comment]
> is it possible to increase the ram? 128mb is the minimum for some windows 98 games and getting win98 was hard enough and the other cores don't have a virtual keyboard which i need

Can you share what settings you used to get w98 to boot?

**Comment by schellingb** [comment]
I have no idea how you are running Windows 98 but I added some more memory options for the next release :-)

**Comment by Xbox-Series-X-User** [comment]
i run it by having a preinstalled win98 on a .img file and mounting it as a  c hdd then boot -l c

**Comment by Xbox-Series-X-User** [comment]
MUCH THANKS! :] maybe 3dfx voodoo emulation next that's the dream
