### ISSUE TITLE
Pagan Ultima VIII Crash on gameplay start Error

### ISSUE THREAD

**Issue by thiagobucca** [schellingb/dosbox-pure#174]
Hi, i'm struggling to get the game Ultima VIII: Pagan to work with dosbox-pure. I tried in latest retroarch version and latest dosbox-pure core version, both on macOS and Windows 10.

Already tried with both XMS on and off and tried a several set of options, but none of them worked, it always crash when the 
game starts, anyone managed to get this game working with dosbox-core?

I'm getting this error: 
https://i.postimg.cc/50b8RYG2/Screen-Shot-2021-07-29-at-20-02-19.png

**Comment by schellingb** [comment]
Are you running the game from a ZIP file or with direct path?
From the error, it sounds like some save game data is corrupt. Has the game ever worked for you? You can maybe try to backup and delete that SAVEGAME\SGHEADER.DAT file to start over (or rename it).

**Comment by thiagobucca** [comment]
deleting SGHEADER.DAT did the trick for me, and it works even better than with dosbox-svn, thank you very much mate :)
