### ISSUE TITLE
Wacraft 2 CD-mounting issue

### ISSUE THREAD

**Issue by dragonchaser** [schellingb/dosbox-pure#176]
Hi I am trying to run warcraft2. Unfortunately I can not get the cd mounted properly.
On old dosbox I ran `mount d "/path/to/dir/on/host/where/cddata/lives" -t cdrom` to get it running.
On dosbox-pure I get `illegal type cdrom`. I can mount the directory without the `-t cdrom` part, but then wc2 does not recognize it as a cd drive and fails to start.
Is there a specific reason why the `-t cdrom` part has been removed? Or am I doing the wrong approach here?

**Comment by Xbox-Series-X-User** [comment]
wrong approach mount an imgfile 2gb fat16 as your c drive with windows 98 and mount an imgfile as your d drive with warcraft preinstalled and boot -l c the run it through windows

**Comment by schellingb** [comment]
For DOSBox-Pure I removed the support to mount physical CDROM drives because it is too platform specific and doesn't make sense in a multiplatform libretro core. In the process I also disabled mounting of local directories as cdrom which I now have re-enabled again. Hopefully it will fix your use-case.
Normally CDROMs are mounted with a disk image file but there is no reason why mounting just a path like you are trying shouldn't work. Please wait for the next release.

**Comment by dragonchaser** [comment]
@Xbox-Series-X-User that does not work on batocera linux.

@schellingb I am not talking about a physical cdrom, it should be mounted as type cdrom, e.g. emulate a cd drive, this is a quite common usecase. Why would I want to repack this as a cd iso again?

**Comment by Xbox-Series-X-User** [comment]
@dragonchaser how is that version different? Fyi I have used dosbox way back in the psp days so if it runs dosbox it should run windows in my experience

**Comment by schellingb** [comment]
@dragonchaser I understand that. I just added some background information on why DOSBox-Pure had support for emulating a CDROM from just a local path disabled. As I said, it will be supported again in the next release.

**Comment by dragonchaser** [comment]
@schellingb that is a relief :) looking forward to that, thank you

**Comment by dragonchaser** [comment]
@Xbox-Series-X-User well for starters, it is the architecture I am running on, my device is aarch64 so windows does not run there... (odroid go super)

**Comment by Xbox-Series-X-User** [comment]
You're not running Windows on Linux you're running Windows on dosbox on Linux which I've done and works

**Comment by Xbox-Series-X-User** [comment]
I don't know if I'm missing something but as far as I know dosbox is an emulator on what you're talking about and on the emulator you can run Windows

**Comment by dragonchaser** [comment]
@schellingb so this is resolved?

**Comment by schellingb** [comment]
It was last August, as of 7feecf4
