### ISSUE TITLE
No way to switch mouse emulation to one of the sticks, players get stuck in many game menus

### ISSUE THREAD

**Issue by ghost** [schellingb/dosbox-pure#179]
3 examples:

* Star Wars Dark Forces: auto mapping does a good job, but I get stuck each time the menu is on.
* Ecstatica: if you dare press the button to call the menu, you are screwed.
* Terminator Future Shock: you need a mouse to select menus.

Every time I have to pause, change controller settings to mouse, then go back, select the button in the game menu, pause and change the controls again.
It would be much simpler to have one of the buttons trigger an emulated mouse, just like the emulated keyboards, when needed.

**Comment by schellingb** [comment]
It's kinda complicated, especially in regards to the automated key mappings but also with the default keyboard bindings, there isn't really a button available for that. Which button did you have in mind?
An idea would be some special button on the on-screen-keyboard (maybe above the numpad) or maybe controlling the mouse while holding down the on-screen-keyboard button?

**Comment by lelecanfora** [comment]
In that case, the best solution is a button on the on screen keyboard: press it, the keyboard disappears and you can control the mouse, to get back to game controls you press the key for the onscreen keyboard again.

**Comment by schellingb** [comment]
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.
