### ISSUE TITLE
Overscan support; Crystal Caves green "all clear" border missing.

### ISSUE THREAD

**Issue by boomercore** [schellingb/dosbox-pure#180]
As seen in DOSbox X with surface rendering + overscan turned on and actual hardware + CRT, there will be a green border upon retrieval of all gems per stage, signifying that the stage can be exited.  Was wondering if this could be implemented at some point, thank you.
![crystal caves border](https://user-images.githubusercontent.com/30274474/128095092-d7fc1597-9d23-4ae6-a28d-42ea665bec80.JPG)

**Comment by schellingb** [comment]
Is DOSBox-X the only variant of DOSBox that does this correctly? If so, there might be slim chance for me to implement this. DOSBox-X is very different from regular DOSBox. The emulation part of DOSBox Pure is 100% based on actual vanilla DOSBox, so compatibility stuff needs to be fixed there to be incorporated into Pure. Unless it is a very small code change that certainly won't break anything else etc.

**Comment by n1ghttrap** [comment]
I do believe it's only in DOSbox-X and maybe a few other variants. I checked both .74 and Staging and the option is in neither conf file. If that's your scope and focus for the project, I understand, it's your show.  If you've got time and the code seems easy enough to implement, perhaps some time down the road.

**Comment by schellingb** [comment]
You have to understand how different DOSBox-X is compared to regular DOSBox (and thus Pure).
- The source code of DOSBox-X consists of 1238 files with 858309 lines of code in a 220 MB github repository
- The source code of DOSBox consists of 290 files with 128479 lines of code in a 7 MB svn repository

DOSBox Pure would 100% not exist if the code base of DOSBox were 6 times the size, 6 times the complexity. Chances that I can find out which of the 700k added lines fix this particular problem are very small.

Compatibility stuff like this is driven by original DOSBox, maybe you can bring it to the attention of the maintainers of that :-)
Realistically I can only fix things that broke in the process of making this derivative of the original code.

I'd rather fix the flickering of Alpha Waves (aka Continuum) first :-)

**Comment by n1ghttrap** [comment]
No worries, it's understandably fringe. Just thought I'd bring it up in case it's something you wanna tackle months if not years from now, haha.

**Comment by schellingb** [comment]
Switching out the entire DOSBox part with DOSBox-X is not possible, but if we can figure out which patch or code part of DOSBox-X can fix this in vanilla based DOSBox then I'd certainly consider it. Figuring out what fixes it might be hard though... did you say that there is a special option in DOSBox-X regarding overscan that needs to be turned on for this to be correct?

**Comment by n1ghttrap** [comment]
I'd have to double-check to see if this is in vanilla or not.

**Comment by schellingb** [comment]
Ah OK, I can probably work backwards then, see what that config setting affects and see how complex (or simple) it would be to copy that functionality over into our code base. I'll see what I can do :-)

**Comment by n1ghttrap** [comment]
Thought I'd see if you'd gotten anywhere with this, thanks.

**Comment by PoloniumRain** [comment]
Tested and working :)

@boomercore The setting is in: 
Core Options > Video > Overscan Border Size.

**Comment by boomercore** [comment]
Works excellently, thank you.
![Crystal Caves (1991)-231210-220600](https://github.com/schellingb/dosbox-pure/assets/30274474/9e52b275-9a6c-45bf-a618-61661f79c30f)
