### ISSUE TITLE
Roland MT32 Integration / Soundfont

### ISSUE THREAD

**Issue by Mitch187** [schellingb/dosbox-pure#181]
Hi,

Is it possible? That was very nice. In Dosbox-X or Dosbox ECE, there is an Integration. But i don't know, If it have Soundfont MT32 Like ScummVM.

Best Regards,
Mitch

**Comment by schellingb** [comment]
Not sure what you mean. MT32 emulation was added in 0.8 (see discussion in #5). Are you asking for something different?

**Comment by Mitch187** [comment]
> Not sure what you mean. MT32 emulation was added in 0.8 (see discussion in #5). Are you asking for something different?

OK, i have installed  Wing Commander 1 and Set ist Up to Roland MT32. I hear the Sound, but not the right Instruments. IT sounds weired.

**Comment by Mitch187** [comment]
Thank you for your Support, now in can User Roland MT32 in Games.
