### ISSUE TITLE
Mortal Kombat Trilogy Control issue

### ISSUE THREAD

**Issue by palmerj** [schellingb/dosbox-pure#183]
I'm not sure what the issue is but when playing MKT on batocera x86 via retroarch and dosbox pure I can't easily do sub-zero's slide move which involves pressing 4 buttons simultaneously. i.e Back (CURSOR LEFT or RIGHT) + Low Punch (NUM 1) + Low Kick (NUM 3) + Block (NUM 5) simultaneously to activate the move. I first have push Back  (CURSOR LEFT or RIGHT) + Block buttons (NUM 5) and then a few frames later the Low Punch (NUM 1) + Low Kick (NUM 3) buttons to activate the move. I don't have this issue under standalone dosbox.

Could this be some control input timing issue within dosbox pure plumbing with libretro?

**Comment by palmerj** [comment]
Note on Batocera v31 (current version) is shipping with v0.12 of DOSBox pure. Could this fix in #152 in v14 resolve the issue?

**Comment by PoloniumRain** [comment]
Never used Batocera, but i can at least say that Sub-Zero's slide move works perfectly with all buttons pressed simultaneously on Windows with DOSBox Pure 0.15.

But i noticed that the DBP automatic key mapping feature doesn't work properly with this game. The block and run buttons on my controller are both run (both mapped to numpad 2). Block is numpad 5, but that key isn't available to map. So i had to set Device Type to 'Custom Keyboard Bindings' to have all the keys available, then manually map each button. Now the move works.

**Comment by palmerj** [comment]
OK this seems ok with 0.16 now.
