### ISSUE TITLE
Backslash key does not work with UK keyboard layout

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#197]
The [backslash and vertical bar/pipe symbol key](https://i.stack.imgur.com/VJEZC.jpg) does not work on both a physical UK keyboard and the on-screen keyboard when using the UK keyboard layout in DOSBox-Pure.

Pressing  \  or  |  on the DOS command line does nothing, but the on-screen keyboard will produce a hash instead of a backslash. Considering that the hash key on a UK keyboard layout is where the backslash key is located on a US layout this issue might have something to do with the UK and US layouts being mixed up. All other keys work fine.

Windows 10
RA 1.9.10
DBP 0.17

**Comment by schellingb** [comment]
Googling "DOS UK keyboard layout" showed me a layout like this:
![DOS UK keyboard layout from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/KB_United_Kingdom.svg/400px-KB_United_Kingdom.svg.png)
This seems to match what I get in DOSBox Pure with the on-screen-keyboard. The \ and | key is located between left shift and Z.

Inside the code of DOSBox, that hardware key is called `KBD_extra_lt_gt` which matches a lot of European keyboard layouts and why I drew a < character there. Ideally the on-screen-keyboard would reflect the keyboard layout but... not high on my priority list.

**Comment by PoloniumRain** [comment]
Now fixed with commit 14f676ac524fd3325bf5b4a266dc2dcd40c82395.
