### ISSUE TITLE
Some keyboard layouts causes retroarch to hangup while starting the core in the latest 0.18 version.

### ISSUE THREAD

**Issue by Razor221** [schellingb/dosbox-pure#200]
When some of the keyboard layouts are selected in the latest version. Dosbox-pure fails to start and retroarch hangs up while starting the core.  This didn't happen in version 0.17.

Here are some of the layouts that cause this behavior: Croatia, Check republic, Denmark, Slovenia, Turkey.

**Comment by schellingb** [comment]
Very good find, thanks so much for reporting this. I did not think about testing keyboard layouts with the big 0.18 change. This is fixed now in the just released 0.19.
Thanks again for posting, quite a crucial issue.
