### ISSUE TITLE
Aspect Ratio Correction no longer works in version 0.18

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#201]
When enabling 'Aspect Ratio Correction' it no longer does anything in 0.18, but when using 0.17 it works fine. For example, try running Doom or Doom 2 and enable 'Aspect Ratio Correction' - both games remain stretched and wont switch to the 4:3 aspect ratio. The DOS command line and the Start Menu are also affected.

**Comment by schellingb** [comment]
Ah, that somehow broke in all the big (internal) changes 0.18 brought...
It should work now again in 0.19. Thanks for testing and posting this issue!

**Comment by PoloniumRain** [comment]
It's doing something now in 0.19 but it's not the correct aspect ratio. The problem is related to the games resolution, so some games look horizontally squished while others are almost fine.

You can see this happening by running Quake, then at the menu screen go to Options > Video Options and toggle through the different resolutions, you'll see the aspect ratio changing even though 'Aspect Ratio Correction' is enabled. For example 320x200 almost looks perfect but 800x600 looks squished. Here's a comparison at 800x600...

![Quake_comparison](https://user-images.githubusercontent.com/50634894/137798394-02fb0df3-67a9-4041-9e69-eab9a6d182d2.jpg)
