### ISSUE TITLE
Mouse not working on Doom (1993)

### ISSUE THREAD

**Issue by daFourch** [schellingb/dosbox-pure#212]
Mouse doesn't seem to be working on Doom. The game is supposed to handle it (as seen on mapping info when F1 is pressed) but nowhere, ingame, there are options to enable it, so I guess it's normally detected by default?

**Comment by schellingb** [comment]
Can you to exit DOOM and then run SETUP.EXE and choose "Select Controller Type" and check if "Keyboard + Mouse" is active and not either of the other modes? Make sure to save the setup configuration after modifying it.

It really should work, if the game is configured properly, make sure that your frontend (RetroArch?) isn't blocking mouse events. Try switching to "Game Mode" by pressing "Scroll Lock" if using RetroArch.

**Comment by daFourch** [comment]
Of course, I forgot each game can be setup via setup.exe...

It worked, thanks again
