### ISSUE TITLE
Mortal Kombat Trilogy Keyboard Mapping is Wrong

### ISSUE THREAD

**Issue by palmerj** [schellingb/dosbox-pure#214]
With the detected automatic key mapping the block key is mapped to keyboard NP-2, when it should be NP-5. Right now both the run and block mappings are the same.

![mkt](https://user-images.githubusercontent.com/580022/143818513-991542e7-6268-4a63-8b37-175bf3996ed2.jpeg)

**Comment by palmerj** [comment]
Documented controls:

```
CONTROLS IN GAME (DEFAULT):

PLAYER 1:                PLAYER 2:
H-PUNCH - NUM 4          H-PUNCH - T
L-PUNCH - NUM 1          L-PUNCH - G
H-KICK  - NUM 6          H-KICK  - U
L-KICK  - NUM 3          L-KICK  - J
BLOCK   - NUM 5          BLOCK   - Y
RUN     - NUM 2          RUN     - H
LEFT    - CURSOR LEFT    LEFT    - A
RIGHT   - CURSOR RIGHT   RIGHT   - D
JUMP    - CURSOR UP      JUMP    - W
DUCK    - CURSOR DOWN    DUCK    - S
SELECT  - NUM 7          SELECT  - Z
START   - ENTER          START   - X
```

**Comment by schellingb** [comment]
Thanks for the report! This should be fixed now in the latest version 0.22. Please try it out.

**Comment by palmerj** [comment]
Thanks for fixing this. I will test it out!

**Comment by schellingb** [comment]
Closing this issue now. With the new gamepad mapper introduced in 0.9.0 (as discussed in https://github.com/schellingb/dosbox-pure/issues/57) it's now possible for the user to fix things like this by themselves.
