### ISSUE TITLE
Create an automated controller mapping?

### ISSUE THREAD

**Issue by gingerbeardman** [schellingb/dosbox-pure#219]
> **Automated controller mappings**
> 
> When a game is loaded, DOSBox Pure will try to detect the game and apply a controller mapping.
> To see the applied mapping, check the Port 1 Controls screen in the RetroArch menu. It will show Detected Automatic Key Mapping: <GAMENAME>. Additionally you can set the core option Input > Advanced > Automatic Game Pad Mappings to Enable with notification on game detection.

I'm playing a game ([Slicks'n'Slide 1.51](https://slicksnslide.com)) and I have to set control mappings every time. Is it possible to create an entry so that control mapping is automatic?

I've tried saving controller profile, but no joy.

I'm running dosbox-pure in RetroArch on:
1. GameForce Chi
2. macOS Big Sur

**Comment by schellingb** [comment]
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.
