### ISSUE TITLE
Core version download

### ISSUE THREAD

**Issue by 71knight** [schellingb/dosbox-pure#221]
I need to download version 0.19 for aarch64 android!  How can I do this?

**Comment by schellingb** [comment]
I compiled the old version for you: [dosbox_pure_libretro-android_arm64-0.19.zip](https://github.com/schellingb/dosbox-pure/files/7792650/dosbox_pure_libretro-android_arm64-0.19.zip)
Can you also post why you are looking for an older version? Hopefully it is to verify something and do a bug report regarding the current version :-)

**Comment by 71knight** [comment]
There appears to be a fraction of a second audio desync with the screen refresh setting in retroarch.  The audio gets garbled for a fraction of a second.  This appears to have occurred in the recent builds after 0.19 when the low latency input settings were added and the old code was stripped.  This is also referenced in #184 in the Doom game.   You can notice this in jazz jackrabbit after some time.
