### ISSUE TITLE
Crash with Japanese Windows 95

### ISSUE THREAD

**Issue by RaouleMenard** [schellingb/dosbox-pure#224]
Hello,

I have a problem with the Japanese version of Windows 95, it crash as seen on the attached screenshot.

![w95j_c-220111-013632](https://user-images.githubusercontent.com/56046612/149025163-c4ec692c-ac0a-49de-8f3f-a2dcc8cb3ea6.png)

The same HDD image works fine on Dosbox SVN.

Any chance you could fix this?

Thanks!

**Comment by schellingb** [comment]
I tried an English Windows 95 HDD image and it did not show that error so I don't think I can fix it unless I can reproduce this locally. Are you a member on the libretro discord? If so, you might be able to help me reproduce this locally.

**Comment by RaouleMenard** [comment]
Thanks a lot. This fixed the issue!
