### ISSUE TITLE
Super Street Fighter 2 Turbo (1995) - Default Controls/mappings issues

### ISSUE THREAD

**Issue by pokeshark** [schellingb/dosbox-pure#229]
**Actual**: G keyboard button is set for both Light Kick and Medium Kick, making it impossible to use Medium Kick in-game with controller.
**Expected**:
G for Light Kick
H for Medium Kick

![ssf2t_1995_default_mapping_overlap_MKick_LKick_G](https://user-images.githubusercontent.com/10551675/150551033-dbe2f290-5e33-4c45-b80f-9777d404bfc0.png)

**Actual**: Heavy Kick set by default to Right Bumper, Heavy Punch by default to Left Bumper
**Expected**: Modern Street Fighter games ports on PC use this layout:
Heavy Punch -> Right Bumper
Heavy Kick -> Right Trigger

![ssf2t_1995_default_controls](https://user-images.githubusercontent.com/10551675/150551029-f004156f-3aec-4bd2-88e4-c93c1202eb61.png)

**Comment by schellingb** [comment]
I'll fix the first part but probably leave the overall assignments as is. The other DOS Street Fighter games (Street Fighter II: The World Warrior and Super Street Fighter II) are mapped like this. I think it's meant to match how it was on other platforms (probably SNES).
The mappings come from the "keyb2joy.pad project" (can be googled) which decided that fighting games should be laid out like this. It might be possible to talk them into changing this :-)

**Comment by pokeshark** [comment]
got it, thanks!
I guess the second point is not really a problem (since you can reconfigure the controls - both in-game and in the frontend).

**Comment by schellingb** [comment]
Closing this issue now. With the new gamepad mapper introduced in 0.9.0 (as discussed in #57) it's even easier to fix issues like this now.
