### ISSUE TITLE
Need separative mouse axises to joystick mapping

### ISSUE THREAD

**Issue by Ever17lab** [schellingb/dosbox-pure#232]
Hey. I tried to play MDK with xinput gamepad.

The main problem is that you can't assign only 2 mouse axis (left and right / X+ X-) for look and Y+- axis for up and down to go forward and backward.

Why mouse? It's more accurate for shooters.

Another problem is that if you choose "Custom Keyboard + Mouse on Left Stick" - Right Stick disappears.

Hot should it look in the end? Available options for mouse moving when you choose 'Generic/Custom Keyboard Binding' or 'Automatic Key Mapping'

**Comment by Ever17lab** [comment]
Haha I even paid for GamePad Phoenix, 'Does it allow play any game? Maybe it's like xpadder?' 
But it's not like xpadder -_-

**Comment by schellingb** [comment]
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.

**Comment by Ever17lab** [comment]
Cool ^_^. I had some problems, but I try again.
Strange thing that you cant assign mouse on sticks from RA interface directly.
