### ISSUE TITLE
(Enhancement propose) Joystick/Mouse switch function for gamepads

### ISSUE THREAD

**Issue by iconoclusterdotexe** [schellingb/dosbox-pure#233]
My request is to implement a Joystick/Mouse switch function, mappable via core settings and showing in virtual keyboard (PUAE has a similar function, for example). It can be useful for some games who use mouse for menu navigation.

**Comment by schellingb** [comment]
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.
