### ISSUE TITLE
[Enhancement] CD ISOs mounting in Windows 9x

### ISSUE THREAD

**Issue by RaouleMenard** [schellingb/dosbox-pure#238]
Hello,

It seems that CD ISOs mounting only work in DOS / Win 3.x and not in Windows 9x.

Any chance implementing CD ISOs mounting similarly to HDDs image mounting for Windows 9x support?

Thanks!

**Comment by esgie** [comment]
That’s rather a Win95 issue as there are no CD-ROM drivers compatibile with DOSBox.
The only known workaround is to install virtual CD drive like Daemon Tools 3.47 or Virtual Clone Drive and provide iso image inside guest system (by injecting it into system hdd image; alternatively, by this may be accomplished by injecting Iso file into new, blank hdd image, mounting it as a slave and booting windows), so it can be mounted into virtual drive. Not a very elegant solution, but at least it works.

**Comment by RaouleMenard** [comment]
Thanks for adding Win9x support! CD mounting works fine now.
