### ISSUE TITLE
Oddworld: Abe's Oddysee doesn't work [0.26]

### ISSUE THREAD

**Issue by toniosj** [schellingb/dosbox-pure#247]
I run the game with ABE.BAT and the screen goes black. With DosBOX Standalone it works.

It is not a problem with the ISO, it is correctly mounted.

**Comment by toniosj** [comment]
Tested on 0.9.0: IT WORKS with dosbox.conf file!

Thanks!

**Comment by PowerageDc** [comment]
> I run the game with ABE.BAT and the screen goes black. With DosBOX Standalone it works.
> 
> It is not a problem with the ISO, it is correctly mounted.

I get the black screen too, tested with v0.9.7.
Unzipping and installing the game works ok with DOSBox-core.
