### ISSUE TITLE
President Choice Images won’t Load

### ISSUE THREAD

**Issue by TradeDraft** [schellingb/dosbox-pure#248]
When It try to mount them I get this Error Message:

Screenshot Error:
https://ibb.co/qWrL1V6

Please Help Me

**Comment by schellingb** [comment]
The startmenu in [0.9.0 beta](../releases/tag/0.9.0) can now directly boot from disk images and swapping disks at runtime with RetroArch's "Disc Control" menu and hotkeys is also supported. Here's the startup of this game:

![DOSBox_Pure_PresidentsChoice](https://user-images.githubusercontent.com/14200249/164047291-7960e86f-9149-44af-a29b-89ed5979af55.gif)
(as you can see it switches to the CGA machine, then runs "PCFIX.EXE" and then finally boots the game)

 Please reply in #102 for feedback on it.
