### ISSUE TITLE
Mapping for Bubble Bobble also featuring Rainbow Islands

### ISSUE THREAD

**Issue by litaniast** [schellingb/dosbox-pure#249]
(This isn't early Bubble Bobble port by Novalogic, but later Bubble Bobble with Rainbow Islands port by Acclaim/Probe)

It's fit for Bubble Bobble, but not for Rainbow Islands.
In Rainbow islands, it needs to map "Enter" key to starting game but didn't mapped for detected control.

**Comment by schellingb** [comment]
I added a mapping for enter. To fully support Rainbow Islands it might also need the arrow keys for menu navigation but the on-screen keyboard will have to be used there.
