### ISSUE TITLE
[Request] Allow full keyboard + mouse remapping in controls

### ISSUE THREAD

**Issue by chinagreenelvis** [schellingb/dosbox-pure#250]
Right now, it seems that the device types are limited two mouse modes, each with left/right variants.

The first mouse mode allows remapping which buttons act as clicks but only has a limited range of available keyboard remaps. The second mode has the full keyboard available, but forces either L/R/X or A/B/X as mouse buttons with no way to remap them.

**I would like to suggest that the first mouse mode be expanded to allow the full range of keyboard maps (or duplicated as an expanded version for users who prefer the limited range).**

**Comment by schellingb** [comment]
Please check [this comment](57#issuecomment-1089242631)
This new full remapping feature is already done and will be in the next release. Can't say right now when that will be out, but should be soon-ish.

**Comment by chinagreenelvis** [comment]
> Please check [this comment](57#issuecomment-1089242631) This new full remapping feature is already done and will be in the next release. Can't say right now when that will be out, but should be soon-ish.

Very cool. Will this also allow remaps to key combinations? Also, will adjustments take immediate affect without having to restart a game?
