### ISSUE TITLE
Mapper - Mapping to Joystick Buttons 1-3 clears the setting

### ISSUE THREAD

**Issue by SeongGino** [schellingb/dosbox-pure#251]
Title. Seems to be no way to map the conventional stick/pad buttons in-games.
Happens regardless of the frontend's control mapping setting (tried `Default`, `Keyboard + Mouse on Right Stick`, and `Disabled`)
I would try to use one of the frontend's Joystick profiles (`First DOS Joystick (2 Axes, 2 Auttons)`), but at least for MDK, it doesn't expose anything except for joy/mouse axis, and _one_ hat direction(?).
![Screenshot_20220424-125133](https://user-images.githubusercontent.com/7321839/164987325-adf91fb2-9d51-400d-8abb-42ff0a395324.png)

Observed on Android RetroArch 1.10.3, Core Version 0.9.0.

**Comment by schellingb** [comment]
The possibilities offered by the frontend are limited, so you have the presets and you can remap between what is available there.
If you need further customization, use the [gamepad mapper](../#gamepad-mapper). If you have issues with the gamepad mapper, report them in its issue #57.

**Comment by SeongGino** [comment]
> The possibilities offered by the frontend are limited, so you have the presets and you can remap between what is available there. If you need further customization, use the [gamepad mapper](../#gamepad-mapper). If you have issues with the gamepad mapper, report them in its issue #57.
> 
> Sorry I might not have correctly understand the problem when I replied but I think this has been corrected by [980d430](https://github.com/schellingb/dosbox-pure/commit/980d43091761f1a22bd4499a3a4cf4b012e7118c) as mentioned in issue 57.

I was about to say, this was **not** about the frontend options and **was** about the in-content mapper (I realize only after the fact that clarifying the lack of alternative mapping in the frontend side might've caused confusion, so apologies).
Also confirm that this issue was fixed in the 0.9.1. Consider this resolved.
