### ISSUE TITLE
gamepad mapper can't map mouse left click

### ISSUE THREAD

**Issue by bulzipke** [schellingb/dosbox-pure#252]
[gamepad mapper](https://github.com/schellingb/dosbox-pure/#gamepad-mapper) is a great feature!!
Everything works perfectly except for the mouse left click.

For example, Nothing happens when I set the X button -> Mouse left click.

This occurred in Windows 10 Retroarch 1.10.3 but I don't know the version of dosbox pure.

**Comment by iconoclusterdotexe** [comment]
Same issue to me. I've tested SkyNET and tried to map the Mouse Left Click, but it looks like ignored.

**Comment by bulzipke** [comment]
I didn't know there was #[57](https://github.com/schellingb/dosbox-pure/issues/57).
And bug fix, thank you!
