### ISSUE TITLE
No detailed description of how to use M3U files with DOSBox Pure

### ISSUE THREAD

**Issue by chinagreenelvis** [schellingb/dosbox-pure#256]
With consoles that play games directly off of a disc, it's easy to understand how pointing RetroArch directly to an M3U file populates the disc-swap menu, but how this is supposed to work with DOSBox Pure, I'm not sure. Where do you place the M3U in relation to the ZIP that DOSBox Pure needs to run? How do you write the contents of that file relative to where the disc images are within the ZIP?

I think the main description page should elaborate on this.

**Comment by PoloniumRain** [comment]
M3U files are not needed for DOSBox-Pure. You can set what disc to mount/unmount within the Start Menu, which will usually appear the first time you run a game. But you can also get to it by holding down the Shift key and going on Restart, or going to Options > Emulation Options > Advanced > Start Menu and setting it to 'Always show' to make it show every time you run a game. Once you've mounted a disc just select the games .EXE file and that disc will run (this is _almost_ always the case for most DOS games anyway).

Or a better but more advanced way is to create a .BAT file and place it inside the ZIP. Then go to the Start Menu and highlight the .BAT file and select 'Set Auto Start' by pressing right. Now every time you run or restart the game it will go to a disc selection screen that immediately runs the chosen disc:

![Disc_Menu](https://user-images.githubusercontent.com/50634894/171313726-862ffcd5-29bb-4945-8516-9f586de9ab64.jpg)

**Comment by schellingb** [comment]
If you have the CDROM images inside the ZIP then there is no need for an M3U file, it will automatically find all CDROM images on startup.

You can have an M3U file with a list of CDROM images and boot that if you want. It will have an empty C: drive where you can install the game onto. I think you can also list a ZIP file in the M3U file which would then get mounted as the C: drive if you happen to have a ZIP with the game but the CD images externally.

Also worth mentioning is that this core is fully compatible with RetroArch's `Disc Control` menu. It's super easy to swap disc or even load new discs while in the game. The trailer of DOSBox Pure shows this off at this time stamp: https://www.youtube.com/watch?v=rHkIz4-SewI&t=41s

**Comment by chinagreenelvis** [comment]
> Also worth mentioning is that this core is fully compatible with RetroArch's `Disc Control` menu. It's super easy to swap disc or even load new discs while in the game. The trailer of DOSBox Pure shows this off at this time stamp: https://www.youtube.com/watch?v=rHkIz4-SewI&t=41s

Aha, this is what I was looking for. I know some multi-disc games will allow you to use the .conf files to mount each disc on a separate drive to circumvent the need for disc-swapping but in case that doesn't always work this solves the issue.
