### ISSUE TITLE
0.9.2 fails to run most games

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#264]
Most games will immediately crash/close with 0.9.2. So for instance, i'll click on 'Run' and nothing will happen for a second, then it just goes back to the RA Run screen. But this **only** happens when downloading DBP 0.9.2 with RetroArch using the Online Updater. If 0.9.2 is downloaded from GitHub then it will work perfectly fine. Maybe the version on RA's server isn't compiled properly?

I don't know if this will be of much help, but here's _some_ games that wont run on the 0.9.2 version used by RA's Online Updater:
Quake
Blood
Decent
Lemmings
Tomb Raider
Mortal Kombat 1/2/3
Screamer 1/2/Rally
Primal Rage
Earthworm Jim 1/2
Stargunner
MegaRace 1/2

But these games run:
Doom
Ultimate Doom
Hexen
Magic Pockets

This is on Windows 10 and i've used a clean install of RA 1.10.3 to confirm this.

**Comment by schellingb** [comment]
It looks like any kind of CDROM or disk image will crash during startup with the builds made by the buildbot. This needs to be addressed ASAP, I'll push a new version with a fix now. Thank you so much for quickly reporting this!!

**Comment by schellingb** [comment]
Pushed the new version 0.9.3 to the buildbot that manages the Online Updater. Hopefully this gets out quick. It might only synchronize new core builds once a day so it might take a few more hours for this to make it out to everyone. Bummer, but thanks again for reporting this.

**Comment by PoloniumRain** [comment]
Just tried 0.9.3 via the Online Updater and all games are working again now! :)

**Comment by PoloniumRain** [comment]
I left this open for a few days incase anyone else came here to report the same issue, but it was fixed quickly and it looks like few people ran in to it. So i'll close this now.
