### ISSUE TITLE
Launching on RetroArch Android crashes immediately

### ISSUE THREAD

**Issue by domportera** [schellingb/dosbox-pure#266]
Every time I try to open DOSBox Pure on RetroArch, it crashes RetroArch immediately whether I open it with or without content (zip file). This is not happening with other cores. 

Core Version: 0.9.2
RetroArch version: AArch64 
Android version: 12
Device: LGV600
Processor: Snapdragon 865
RAM: 8GB
Content: Fallout 1997 (archive.org hosts a copy that matches mine)
Content Location: SD Card

<details>
  <summary>RetroArch Info</summary>
  
![Screenshot_20220531-072728](https://user-images.githubusercontent.com/6530600/171163259-b39183e2-7e67-4d15-a33e-e21674ab6faf.png)
![Screenshot_20220531-072742](https://user-images.githubusercontent.com/6530600/171163261-bc13bcb3-ec27-4f3f-a638-bd04ee0e03de.png)
![Screenshot_20220531-072748](https://user-images.githubusercontent.com/6530600/171163262-1fd6ee88-82a2-4de4-ae4f-ad78422e6fd7.png)
 #![Screenshot_20220531-072754](https://user-images.githubusercontent.com/6530600/171163263-49a6973d-e0a6-4969-a057-bdf19909246b.png)
  
</details>

**Comment by schellingb** [comment]
Thanks for the report, I think this is the same problem as #264 and should be solved in a few hours when the new build lands on the Online Updater. When loading with ZIP, can you confirm that this happens only with games that have some kind of CDROM image in them? The only case that doesn't crash in 0.9.2 is when loading with content that has no CDROM (or floppy or harddisk) image.

**Comment by domportera** [comment]
Yes that fixed it! Thank you. I am still having trouble with it as it seems to have a lot of ghost inputs/strange errors and crashes. i don't know if these are known issues though, if not I can provide more info

**Comment by schellingb** [comment]
Ghost inputs might be mouse inputs? RetroArch isn't really well made on mobile to handle a core that accepts both pad and mouse inputs at the same time. If you don't play mouse-only games, you can try setting the core option `Input Options` -> `Advanced > Use Mouse Input` to OFF to see if that helps.
Otherwise feel free to describe a problem with more details. I don't test Android very much at all so having a concrete example described I can try looking into it.

**Comment by domportera** [comment]
it seems like ghost inputs were mouse inputs! even though i had no mouse plugged in 🤷‍♂️

Now that input seems to be working, rather than describing what i'm experiencing I can show you:
https://www.youtube.com/watch?v=He00F_Zf2To

Watch out for horribly loud static somewhere in the middle there

**Comment by schellingb** [comment]
Fallout from 1997 is a very late era DOS game which needs quite a lot of RAM. Try setting the `System Options` > `Memory Size` to `64MB` and see if it helps.

**Comment by domportera** [comment]
that was it!! thank you for having the patience to help out a DOS newbie.

I'm having some problems with drawn frames being much lower than the game's framerate (in both Ultima Underworld and Fallout), but I'd be deeply surprised if this wasn't also an issue on DOSbox-SVN or the stable core so no need to troubleshoot this with me. Looking forward to the further development of this core!

**Comment by schellingb** [comment]
You can try the core option `Emulation Options` > `Force 60 FPS Output`. I'd be curious to hear if it helps on your Android device!

**Comment by domportera** [comment]
unfortunately that didnt help /: speed and frames are great all the time, but Drawn fps seems over-optimized - 0fps when nothing is happening on screen, and 9-21fps when walking around

**Comment by schellingb** [comment]
Oh you are looking at the display from `Show Performance Statistics` set to `Detailed`?
Then that number shown with "Drawn" is supposed to be like that. It not really is "drawn" to your screen, but "drawn by the game with a unique image". So this can expose a DOS games internal framerate which can be interesting to see a bit behind the curtain but it isn't really relevant to the overall emulation.

The numbers shown on the detailed performance statistics:
- Speed: If the device is able to keep up with the emulated hardware (this can go below 100% if setting the `Emulated Performance` setting too demanding)
- DOS: Resolution and refresh rate of the emulated monitor (the emulated hardware will draw that many frames each second, but doesn't mean the DOS game will do so!)
- Actual: The framerate actually drawn on your screen (can be different if forcing 60FPS or when doing fast-forwarding or slow-down)
- Drawn: How many unique images were drawn in one second (if walking around in DOOM this number is 35 because DOOM runs internally runs at that framerate)
- Cycles: Basically the frequency of the emulated CPU (number will vary when using the `AUTO` (default) or `MAX` performance setting).

Hope this clarifies things :-)

**Comment by domportera** [comment]
thanks for clarifying some of that! so could this just be a raw performance problem? if that's the case it would be strange since im not experiencing this in another app (Magic DOSbox) using SVN

**Comment by schellingb** [comment]
Is there an actual performance problem? Or is just the number smaller than you'd expect?
Please ignore the number shown after "Drawn:", don't think about it.

**Comment by domportera** [comment]
i will ignore that number but there is a very noticeable difference in draw performance. let me take a video for you. also very sorry if this is totally user error here

**Comment by domportera** [comment]
still processing but here's a video: https://www.youtube.com/watch?v=P-l0D6uxK3Y

**Comment by PoloniumRain** [comment]
I'm pretty sure your cycles setting is too low at 3000. By default i think DOSBox-Pure uses 27000 cycles for Ultima Underworld, so maybe you changed it? But this is the emulated CPU speed. So right now with 3000 cycles you're basically using a CPU from around 1985 to run a game released in 1992.

If you go to Options > Performance Options > Emulated Performance and set it to AUTO it should fix the poor frame rate. AUTO should work well for most games so it's best to leave it on that. But if that doesn't work then try 486DX2 66MHz under the same setting.

**Comment by domportera** [comment]
thank you so much that did it! I was on Auto already and i had tried the most powerful AMD emulated CPU to little effect (it actually made it worse), but i did not try the 486DX2 and that did a great job. sorry for taking noob shit to the issue section here

**Comment by schellingb** [comment]
Ah good catch @PoloniumRain thanks for the input!

DOS games made before DOOM (around 1994) are often unable to detect the speed of the CPU and would end up running at an unplayable speed if the emulated CPU were running uncapped. So by default DOSBox runs such old games at a very low speed.

DOSBox Pure tries to detect the release date of the game and if it can it will default to a CPU that is appropriate for the year the game was released in. But if the game is not in the database it will fall back to the slow CPU.

There are older DOS games that are able to detect the speed of the CPU and don't just run at a crazy speed. A game made in 1992 is probably capable and there you can set the setting to "MAX".

**Comment by domportera** [comment]
thank you for clarifying! is there any way i can format/name my files to help ensure they find a match in the database?

**Comment by PoloniumRain** [comment]
There's a quality DOS game collection called eXoDOS which works well for me (i wont link it lol but it's really easy to find). I got Ultima Underworld from there and it's correctly detected (27000 cycles on AUTO). 

But for running Ultima on a phone it would be ideal to use 486DX2 66MHz and set the Performance Scale to 60% to get 16000 cycles, but it might be called 'Limit CPU Usage' if you're using an older version. This way it will use very little battery power but still be fast enough to run Ultima smoothly. But before doing that, if you go to Options > Manage Core Options > Save Game Options then these changes will only be saved to this game.

**Comment by domportera** [comment]
thank you so much for your help!! i will be using those tips :) needless to say you've provided me with the knowledge needed to dive head first into all of this unhindered by my ignorance :)

**Comment by schellingb** [comment]
No need to apologize my friend!

DOS emulation covering 20 years of video game history on a huge variety of original hardware can be a daunting thing for sure. This core tries to do as many things automatically as possible to simplify things not only for beginners but also for people like me who grew up fiddling with DOS and the computers of that era but now sometimes just want to enjoy the games in a way as convenient as possible.

For games not in the database to run with a CPU appropriate for the games release date you need to have the games release year in the path of the loaded game. So if your game is in a place like one of these:
- C:\DOS\Ultima Underworld - The Stygian Abyss (1992).zip
- C:\DOS\1992\Ultima Underworld - The Stygian Abyss.zip
- C:\DOS\1992\RPG\Ultima Underworld - The Stygian Abyss.zip

It should work as mentioned by @PoloniumRain. The important part is the `(1992)` in the file name or having `1992` as one of the parent folders. I should probably describe that in the documentation somewhere :-)

**Comment by domportera** [comment]
love that, i will make sure to label/sort my games to take advantage of this :) and thanks so much for making this core! it's a real game-changer (literally i suppose) for people like me who didn't grow up with DOS and are just trying to enjoy some old classics. this core makes it all so much more accessible which is critical to keep these games alive and appreciated. it's a real public service
