### ISSUE TITLE
Mounting a disc when another disc is already mounted will crash RetroArch

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#267]
Any game that has multiple CD-ROM discs will crash when mounting a second disc, but only if the current disc is not unmounted first. 

Grand Theft Auto has two discs so i'll use it as an example:

1. Run GTA and go to the Start Menu
2. Do **not** unmount the current disc. Just select the second disc and hit enter
3. RetroArch will now crash

This happens with 0.9.3 on Windows 10 with a clean install of RetroArch 1.10.3. But the crash doesn't happen with 0.26 or the 0.9.0 beta. So maybe it's related to the CD-ROM issue with #264?

**Comment by schellingb** [comment]
Ah, good catch. Yeah that broke together.
Again thanks for the report and the thorough testing in general! Much appreciated!

A bit of backstory why I modified how CDROM images are handled internally in the core. It's a preparation for an upcoming bigger update with some exciting new features. Hopefully out sooner than later :-)

This is less severe than the previous problem but maybe this fix should also be pushed to the Online Updater.

**Comment by PoloniumRain** [comment]
Just confirming that this issue is now fixed in 0.9.5.

And now i get to see what those "exciting new features" were... Yeah, very exciting! I'm trying out the OS installing/booting option and just got Win 98SE working with some 3dfx games. **Very. Fucking. Cool.** Previously i used PCem for this kinda thing, but DBP might be better, at least for most games due to the lower input delay (although PCem has Voodoo 2 and 3 support amongst other things). Looks like i'm going to be up late tonight messing around with this....
