### ISSUE TITLE
[Android] Touch mouse movement unresponsive at low speeds

### ISSUE THREAD

**Issue by domportera** [schellingb/dosbox-pure#269]
Here's a [video illustrating the problem](https://www.youtube.com/watch?v=KLzTCxVMEtc)

I'm not sure if this applies to other versions of the dosbox core on retroarch (as I haven't been able to get them running 😬) but at low speeds, the mouse movement becomes less-than-responsive.

On Magic DOSBox [I do get this symptom](https://youtu.be/Wq7ny5R8Ddw) but it's not as bad. 

Edit: just tried a DS emulator with RetroArch and found the same problem, so it's likely to be a RetroArch limitation. Not sure if anything can be done on your end about this, other than maybe #270

**Comment by domportera** [comment]
Raised an issue with RetroArch: https://github.com/libretro/RetroArch/issues/14011

**Comment by schellingb** [comment]
The core option Input -> Mouse Sensitivity would help with this
