### ISSUE TITLE
Gamename.save.zip not compatible with EmulationStation gameslist

### ISSUE THREAD

**Issue by XargonWan** [schellingb/dosbox-pure#27]
Can you please change the save name removing .zip?
In Emulationstation if I use .zip .ZIP as file extension for DosBox games I still see the save files in the games list.

Maybe a good naming may be gamename.save without the .zip, or maybe if you want to keep it recognizable as archives maybe .tar?

**Comment by XargonWan** [comment]
Renamed into .dosz

**Comment by schellingb** [comment]
I really would like to keep the ending .zip so it is clear for any user that they can just open it and modify it. All operating systems  offer easy ways to look into ZIPs and can modify them. A regular Windows user might not know what a .tar file is. They might even have file extensions not show in the OS yet still they can handle a ZIP file.

If you're fine with renaming all your games to .dosz then yeah that seems a solution. I guess there could be an advanced core option to change the save file ending if that is a problem many people run into. Can't emulation station just ignore the save directory? There's all kinds of stuff in there that should be irrelevant for it.

**Comment by XargonWan** [comment]
Yeah I am working on DosBox Pure to make it fit with [351Elec](https://github.com/fewtarius/351ELEC), it's a firmware for RG351P, we already have got DosBox Pure running and it's running like a charm.

Sonn(ish) I think the developer will move all the saves into a separate folder so I think this issue will be no more and we can support both .dosz and .zip.
