### ISSUE TITLE
The game 'Ripper' does not work unless it is unzipped

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#273]
So here's an odd one.... When trying to run Ripper from a .ZIP file it will not work. Or at least the eXoDOS version doesn't work, which might be pre-patched with a non-official patch/driver. Anyway here's all the steps needed to get this game working on DOSBox-Pure, and even then you will still be left with an unzipped game...

1. Run Ripper and on the Start Menu go on ripper.exe, it will say "The TAKE2 INI file is not valid. Please run SETUP".

2. So run setup.exe, set it to sound blaster, and now run ripper.exe. It will go straight to the games main menu screen, but this is wrong because it should have played a FMV first. And if you go on Start New Game you'll see "Error playing scene: baw1a.smk". So the game isn't playable.

3. Now unzip Ripper and go to the main directory with the 'cd' and 'ripper' folders.
 
4. Create a .BAT file which contains: 
```
CD RIPPER
SETUP.EXE
``` 

5. Place the .BAT file in the directory mentioned above, then run the .BAT with DBP (this step is just to make DBP find and mount the CD-ROM disc, maybe there's an easier way to do this?). 

6. Go through the setup again and then run ripper.exe. For some reason the game will now work properly.

7. Finally, zip the game again and run it. It still wont work even though the setup has been completed and the changes have been saved in the TAKE2.INI. The game needs to remain unzipped for it to work.

Tested on Windows 10 with both 0.9.3 and 0.16. Neither work. 

BTW Ripper is over 4GB, but you implemented ZIP64 ages ago, which i tested at the time and it worked with all other 4GB+ games, but Ripper is the one game i tested on the Start Menu but didn't actually play. Lol typical. I doubt this is related to that though being as the other games play ok.

**Comment by schellingb** [comment]
Thanks for the report! Found a bug with reading file data in ZIPs larger than 4GB. Indexing the ZIP worked fine, maybe even reading a file depending on the internal data layout of the ZIP file. In the next release it should correctly work after running setup which should set the CD-ROM drive letter to be used for all CDs to the correct D: drive.

**Comment by PoloniumRain** [comment]
Nice, i'll test it once the update is out and report back.

**Comment by PoloniumRain** [comment]
Sorry i took SO long (1.5 years lol) but i completely forgot to test this! I can confirm that Ripper now works perfectly, so i'll close this issue.

**Comment by schellingb** [comment]
Thank you for testing and confirming that this is now not a problem anymore.
And also thanks for being active here for multiple years, very much appreciated!
