### ISSUE TITLE
Request: default executable file within game.zip?

### ISSUE THREAD

**Issue by bigroy00** [schellingb/dosbox-pure#28]
Would it be possible to search for a default file on load that specifies the game executable?
e.g. Game.zip contains:
a.exe
b.bat
c.cmd
where b.bat is the executable that actually starts the game
We could add a text file called default_executable.txt to the root of the zip file which has one line e.g. : "c:\path\b.bat"
(if default-executable.txt is not found then proceed as currently)
This way the default can be packaged in the game zip, rather than in a seperate save file
Not a big issue but nice to have

**Comment by schellingb** [comment]
That is already supported!

Have you pressed right in the start menu?
It allows you to select the default item. If you press right multiple times, you can specify a number of 'skip frames', which can be used to skip up game start-up sequences or loading screens.

When you modify the auto start option in the menu, it is saved into the game save file (the original ZIP is always untouched).
But if you were to open the save file, you can find a file called "AUTOBOOT.DBP", you can move that over into your original ZIP then it will be independent of the save file.
The content of "AUTOBOOT.DBP" are what you described, just the full path of the file to execute. If there is a number on the second line of the file, that will specify the number of skip frames.

**Comment by Gaulent** [comment]
Awesome. I was thinking about doing that too. I wonder if it could be overridden by another copy on the save file.

**Comment by bigroy00** [comment]
> That is already supported!
> 
> Have you pressed right in the start menu?
> It allows you to select the default item. If you press right multiple times, you can specify a number of 'skip frames', which can be used to skip up game start-up sequences or loading screens.
> 
> When you modify the auto start option in the menu, it is saved into the game save file (the original ZIP is always untouched).
> But if you were to open the save file, you can find a file called "AUTOBOOT.DBP", you can move that over into your original ZIP then it will be independent of the save file.
> The content of "AUTOBOOT.DBP" are what you described, just the full path of the file to execute. If there is a number on the second line of the file, that will specify the number of skip frames.

Thats great! You have anticipated my request perfectly! Really good work on DosBox Pure

**Comment by shakeyourbunny** [comment]
I dread the coming wave of "DOS ROMs" with this in it.

**Comment by schellingb** [comment]
I made it as easy as possible through the start menu. No need to distribute the auto boot file really.

Btw. if you want to go back to the menu after setting an auto start, hold shift on the keyboard or L2 or R2 on the gamepad while selecting `Restart` in the core menu. As explained by the [README](https://github.com/schellingb/dosbox-pure#start-menu-with-auto-start).

**Comment by bigroy00** [comment]
Thanks for your quick response
