### ISSUE TITLE
Incomplete support for Windows installations on earlier RetroArch versions

### ISSUE THREAD

**Issue by PythonBlue** [schellingb/dosbox-pure#285]
I realize it's not optimal to not use the latest RetroArch versions with this core, and the only reason I am in this particular case is that a beta of another program, EmuVR, requires an installation of RetroArch 1.7.5. The EmuVR aspect seems to be trivial and irrelevant, however, beyond why I'm using 1.7.5 for this, as I confirmed it also happens in the same version of RetroArch on its own.

**Symtom:**
RetroArch 1.7.5 will not give one the option to "Boot Installed Operating System" on the core's startup screen, even if a properly formatted and installed disk image is in the directory it belongs in (the system folder).

**Fool-proof way to reproduce:**
1. Install Windows 98 onto a new disk image using a verbatim installer and RetroArch 1.7.5.
2. Restart the core after a successful install (aka when you see the standard Desktop for the first time and properly shut it down after). Content to start the core with is optional.

I realize this is a bit of an unusual issue in terms of whether it would be appropriate to fix, especially since I also confirmed that later versions of RetroArch, while incompatible with EmuVR, don't have this bug. Still, if you are able to at least figure out what exactly is causing this issue codewise, it would be appreciated.

**Comment by schellingb** [comment]
If there is a lot of stuff in the System folder, DOSBox Pure will stop to automatically look through everything on every startup. If the time to index the files ends up taking longer than 2 seconds, the core will store a list of files it uses and the user needs to manually refresh it.

Can you go to the core options under "Audio Options" and see if you are able to select "Scan System Directory" in the "MIDI Output" option? If so, select it then select something else to refresh the files. Then it should hopefully appear.

It's a bug and the next version will automatically do that when starting the [ Boot and Install New Operating System ] procedure.

If your problem isn't this system directory cache we might need to dig a bit deeper...

**Comment by PythonBlue** [comment]
Thanks for the quick response, first of all.

Trying the MIDI suggestion while running another fresh install of Windows. What I can say in advance of the result, however: I get no option to specify a different directory for MIDI output (only "frontend" or "off"), and even if I did, the only other file I have in the system folder at the present moment is specific to the Playstation cores.

**Comment by PythonBlue** [comment]
Yep, same result even after going through the process of installing 98 and nothing else on a new disk image.

**Comment by schellingb** [comment]
Ah, I know what is the issue.

For a libretro core to be able to evaluate the contents of a directory it needs libretro VFS API v3 support.
Turns out that was added [4 years ago](https://github.com/libretro/RetroArch/commit/e6fc4220fa03e8df6ae1331e16b5b63fb394b482) and first appeared in........... RetroArch 1.7.6

Looks like 1.7.5 is just a few months too old to support this, or other things contained in the system directory like sound fonts or MT32 roms.

**Comment by schellingb** [comment]
I was told EmuVR was able to overcome this problem so I'll go ahead and close this issue.
