### ISSUE TITLE
Fully Customizable Keyboard and Mouse Bindings

### ISSUE THREAD

**Issue by Shiftex** [schellingb/dosbox-pure#286]
I'd like to ask if you could add an option to fully customize a controller to both keyboard and mouse buttons as an extra device type.
To have all keys unlocked as well as mouse movements so that we could decide which buttons to assign where instead of using pre-existing configurations.

This is especially important in FPS and RTS games where mouse and keyboard are used on both analog sticks, for example: If I select [Custom keyboard + mouse on left stick and b/a/x] I can't bind L and R as mouse keys, if I select [Mouse with right / left analog stick] I can select mouse keys but my keyboard options are very limited, if I select [Custom keyboard bindings] I can bind any key but now I don't have any mouse support, etc'...

Up until now I managed to make things work somehow with game-specific premade bindings in some games but sometimes there are changes like in Shadow warrior for example where the spacebar key is now configured as attack whereas before it was left ctrl requiring me to rearrange the keys in the game itself, or in the lion king (before this latest update) where suddenly I couldn't jump for a similar reason.

Adding this will fix the need to check which preconfigured keys have been changed with every update, hopefully this is possible, thanks in advance ^^

**Comment by schellingb** [comment]
Do you know about the gamepad mapper? It was added in version 0.9.0 and is described in [the docs here](https://docs.libretro.com/library/dosbox_pure/#gamepad-mapper). It allows full customization of the first controller to anything. Customizing other controllers (2, 3, etc) should come in a future update.

**Comment by Shiftex** [comment]
Wow I guess I missed that, thank you !
I'll report back if there are any problems :3
