### ISSUE TITLE
[0.9.6] Quake 3 Arena could not load OpenGL subsystem

### ISSUE THREAD

**Issue by cbrunner83** [schellingb/dosbox-pure#289]
Hi there! :)

tried to testrun Q3demo as it was shown in the presentation video
and the Q3 startup console gave out "GLW_Start OpenGL () - could not load OpenGL subsystem"

Host OS
Win 10 64bit / Retroarch 1.10.3 / core 0.9.6

Installed
typical Win98SE with Voodoo Drivers 3.01.00
DirectX 9.0c

additional Note
I`ve tried my luck with NHL99 which automatically detects Voodoo Cards and uses them if possible. 
That works basically... stuttering sound in Menue when hovering buttons and "shooting triangles" while in the 3D playfield.

Cheers
Chris

**Comment by schellingb** [comment]
I had to copy the file "3dfxogl.dll" to "3dfxvgl.dll" under "C:\Windows\System" (after enabling showing all files and file extensions in the Windows Explorer options).

Not really sure why... The startup console mentions being unable to find said "3dfxvgl.dll" so I figured I'd try that and it worked :-)

**Comment by cbrunner83** [comment]
@schellingb 

ah allright, thanks for the info :)
i have a 3dfxogl.dll in Windows/System
and there is no "vgl" in the voodoo driver files
so you just renamed the file 
or am i missing that in my driver files?
