### ISSUE TITLE
[Feature Request] EAX Support for games

### ISSUE THREAD

**Issue by UserGit-2021** [schellingb/dosbox-pure#294]
Adding support for EAX audio for surround sound.

**Comment by ckeisc** [comment]
Probably has to make this kind of request in upstream Dosbox SVN.

**Comment by schellingb** [comment]
Please don't open multiple issues for the same request.

This is out of scope for this project. No variant of DOSBox has anything like this, and on top of that RetroArch/libretro doesn't support anything besides stereo audio. Unless someone is extremely dedicated  and talented to implement this, I don't think this will happen.
