### ISSUE TITLE
"Beauty and the Beast - Be Our Guest" doesn't work.

### ISSUE THREAD

**Issue by Gaulent** [schellingb/dosbox-pure#31]
It seems that the game can't find/read a file. I get the same output with a demo version I found. Weird!

Thanks for this core. It's already awesome. Congratulations!

![output](https://user-images.githubusercontent.com/25830176/103150918-37efa800-4779-11eb-9a0f-600e32aac22b.png)

**Comment by schellingb** [comment]
Oof, this fix required much more time than anticipated... hopefully there's other games out there that needed this :-)
Please try again with the latest 0.4 release!

**Comment by Gaulent** [comment]
Oh. I see! So it was looking for "SCENARIO." instead of just "SCENARIO". Funny how DOS used the filename extension. Thanks for the update! Not only does this game work perfectly now, but it has also fixed the last one I had broken "King of the Beach". I'm so happy :D
