### ISSUE TITLE
Gamepad Bindings Enable Harcoded Keyboard Binding

### ISSUE THREAD

**Issue by rtomasa** [schellingb/dosbox-pure#315]
When configuring gamepad controls, the same are also hardcoded to a keyboard key.
For example:
input_player1_btn_l = "14" bind gamepad L button to the on screen Keyboard, but it also bind the X key in the keyboard. This happens with all the gamepad bindings and makes impossible to play many games.

I know that Game Focus exists for the purpose of using "pure" Keyboard, but it has some drawbacks like making to use ScrLock to enable this mode which disable RA options via hotkeys and also disable the gamepad.
If the forced KB bindings could be removed, you would be able to play using both KB and gamepad simultaneously with only the RA Hotkeys that you defined.

**Comment by schellingb** [comment]
I'm not really sure I understand you correctly but do you want a core option so pressing keys on a real keyboard won't cause keypresses on the emulated computer?
If that's not it, maybe you can rephrase your problem and suggested solution and add some more details so I can help.

Currently pressing X on a real keyboard will always press X in the emulated keyboard. Maybe RetroArch could be enhanced so keyboard keys that have a hotkey set don't get forwarded to the emulator core. That would be great I think but it is out of my control.

**Comment by rtomasa** [comment]
Don't worry, I think you are right, because this is controlled from RA side and RA do not allow to unbind just keyboard keys from retropad. I think that was one of the reasons for creating the Game Focus instead of trying to over complicate the input manager. Closing this issue
