### ISSUE TITLE
ems driver

### ISSUE THREAD

**Issue by gig71** [schellingb/dosbox-pure#33]
some games requires to disable ems driver.
would be cool if this option is added.
in dosbox you can type in command line 
ems=false
and then start the game
it can be in a batch file too.
in dosboxpure,this give an error.

**Comment by schellingb** [comment]
Interesting, I did not know such games existed. Do you have an example so I can test things on my end?
Maybe this can be covered in the 'System > Memory Size' option with an additional 'No extended memory' setting.

**Comment by gig71** [comment]
Thanx a lot!
One game that have this issue is  SUPER TRIO a cute platform game from dong sung.

And congratulation for this emulator.
It's Awesome, a very simply way to play old games.
I love every feature that you put in it !
Go on this way !
Great great job!

**Comment by Tkcmd** [comment]
> Interesting, I did not know such games existed. Do you have an example so I can test things on my end?
> Maybe this can be covered in the 'System > Memory Size' option with an additional 'No extended memory' setting.

Zone 66 is another one.
It requires 

XMS FALSE
EMS FALSE

or else it will not run.
Pure does not support setting this neither from RA (not available as option) and setting it from dos prompt or batch files gives a "Illegal command: z:\config." error

**Comment by schellingb** [comment]
Please try out the [latest release](../releases/latest).
It has the new choice "Disable extended memory (no EMS/XMS)" under the core optoin "System > Memory Size". I tested the two games mentioned here and it works great for me.

**Comment by gig71** [comment]
I JUST TRIED.
IT WORKS!!!!
THANK YOU VERY MUCH.

Scarica Outlook per Android<https://aka.ms/ghei36>

________________________________
