### ISSUE TITLE
Diablo 2 lord of destruction 

### ISSUE THREAD

**Issue by UrusMax** [schellingb/dosbox-pure#330]
Hi! Please tell me if it is possible to start the game Diablo 2 lord of destruction?
Diablo 2 without addon works well. I can't understand why I can't run with аddon. I would be very grateful for a hint.

**Comment by Gaulent** [comment]
> Diablo 2 without addon works well.

How? How did you achieve this? I've been trying every combination of instalation methods, patches and settings without any luck. Either fails loading a library (fog.dll) or does nothing at all.

**Comment by UrusMax** [comment]
Возьмите старую версию игры.  Не старше версии 1.09 или 1.12, точно не помню, а лучше 1.0. Например отсюда:
https://www.old-games.ru/game/download/808.html
Устанавливается без проблем на Windows 95-98. Или используйте уже установленную, например отсюда:
https://disk.yandex.ru/d/f7bFzXehc8car (версия адаптирован для DosBox Turbo, но хорошо работает и в Magic DosBox, и в DosBox pure).
Точно могу сказать, что версии старше 1.13 требуют Windows NT/XP, аддон Lord of destruction соответствует 1.13, поэтому мне не удалось запустить на Windows 95-98.
Для игры в версию с аддоном использую Exagear Windows emulator, отсюда:
https://4pda.to/forum/index.php?showtopic=804309

Описанаая Вами проблема связана с более новой версией игры. Вам нужны самые первые версии.

**Comment by schellingb** [comment]
I removed links that looked to me like they contain piracy material. Please don't share piracy links here.
While your help is appreciated, please write in English so other people with the same or similar problems can benefit from your help. Use a translator if needed.

**Comment by Gaulent** [comment]
Just wanted to thank UrusMax. Sir, you saved my sanity. I don't know how but there is indeed -out there- versions prepared to run on DosBox Turbo that runs flawlessly on Pure. Awesome. Black voodoo magic.
