### ISSUE TITLE
[enhancement request] hard map a game focus key

### ISSUE THREAD

**Issue by Dahak66** [schellingb/dosbox-pure#354]
Currently, Dosbox Pure depends on using the scroll lock key of a keyboard to switch between game focus modes. This is great on laptops or other systems with physical keyboards. This breaks a lot of functionality on most handheld PCs (including the Steam Deck) and other handhelds that can run Dosbox Pure, however. In game focus mode, controllers run as expected, but the menu can't be accessed. If not in game focus mode, the menu is accessible, but controllers become unreliable as the left analogue stick mirrors the dpad in addition to its own functionality (regardless of whether or not the dpad is set to duplicate to an analogue stick). 

If the game focus mode is a necessary evil, could we get the option to map game focus to a button? Otherwise it forces a portable device to be tethered to a keyboard to make use of this core.

**Comment by parkerlreed** [comment]
You can set the game focus button under the retroarch settings input hotkeys. It can either be a keyboard or gamepad button.

**Comment by Dahak66** [comment]
Oh my. I completely missed the existence of that. Works as it should. Apologies for the false issue. Closing.
