### ISSUE TITLE
Ogg not playing music correctly

### ISSUE THREAD

**Issue by filevans** [schellingb/dosbox-pure#356]
Hello,
The music is not playing on all levels on super star dust 96, when using ogg format. The title screen doesn't play but the level select and first level play ok, then it stops playing again. I had edited the cue to point to all the oggs correctly

I've tested this on the original bin/cue and also using wav files instead and all the music plays perfectly. I've also tried VBR and CBR oggs both at stereo 128kb and both have the same problem

Thank you

**Comment by schellingb** [comment]
The newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader has a fix for this, so I'm closing this issue. Thanks for reporting!
