### ISSUE TITLE
Hypervisor core

### ISSUE THREAD

**Issue by Torinde** [schellingb/dosbox-pure#370]
For later Win9x/DOS games it'll be useful to get more CPU performance than emulation can provide - is it possible to add a hypervisor core, for example based on [virt86](https://github.com/StrikerX3/virt86) as discussed at https://github.com/joncampbell123/dosbox-x/issues/1089?

**Comment by schellingb** [comment]
This is out of scope for what this project is. If original DOSBox gets it, we will, too. But that seems unlikely. Personally platform exclusive features like this aren't too exciting to me.
