### ISSUE TITLE
7z support broken, unsure of when regression occurred

### ISSUE THREAD

**Issue by boomercore** [schellingb/dosbox-pure#378]
Tested the following cases: 
zip with complex name with complex folder inside of it: works
7z with complex name and complex folder inside: doesn't work
7z with simple short name and complex folder: doesn't work
7z  with simple name and simple folder: doesn't work
7z with no folder, just the contents: doesn't work. 
When a 7z is loaded, none of the contents show up as available.  Zip files are still fine.

**Comment by schellingb** [comment]
What are you talking about? There never was 7z support.

**Comment by boomercore** [comment]
Apologies.  Did some set converting and totally spaced on this, as some cores support it and some don't.
