### ISSUE TITLE
full throttle slows down

### ISSUE THREAD

**Issue by luigiplus** [schellingb/dosbox-pure#38]
Hello,I was testing some graphical adventures in this fantastic core and I have noticed that Full Throttle is slowing down even changing the options of cycles, cpu, etc.

**Comment by schellingb** [comment]
Can you write what hardware and operating system you are using? And is this slowdown noticeable during any gameplay or only during video cut scenes or dialog scenes?

**Comment by luigiplus** [comment]
I5 3570, r9 380, 8 GB ram, windows 10x64 Home. Retroarch 1.9.0
Slowdown in intro,gameplay,dialog scenes,all.

**Comment by altiereslima** [comment]
same problem...
i7 6700k, 2060 Super 8GB, Windows 10x64. Retroarch 1.9.0

**Comment by schellingb** [comment]
@luigiplus @altiereslima Can you recheck this with the latest version of the core? Recently there were big improvements how the core handles timing/video/audio synchronization and performance so that might resolve these issues.

**Comment by luigiplus** [comment]
Works fine I don't see slowdowns.
