### ISSUE TITLE
Mouse support for touch screen not working

### ISSUE THREAD

**Issue by toughguystudios** [schellingb/dosbox-pure#400]
Hey so, this isn't so much an issue, however compared to DOSbox standalone app on mobile devices (iDos), it is.
    Is there a way to move the mouse cursor using the touch screen of my iPad via drag my finger on the screen and it moves the mouse cursor?
    I saw I'm able to do this on iPad using the app "iDos" which is an Apple App store port of DOSbox. Exact same thing, I just figured that might be a valid option. 
    I'm running legacy hardware (iOS 8 on iPad 4) with retroarch 1.0.0.1 and DOSbox pure runs my PC games far better than DOSBox SVN, but because it's outdated Apple was yet to implement mouse capabilities, and I've tried installing BTC mouse & trackpad but after speaking with the Developer, he advised that no mouse events pass through the APK into applicatons themselves.
    So yeah, just curious, is it possible to move the mouse cursor in DOSBox Pure using my finger on the touch screen of a mobile device? thanks.

**Comment by schellingb** [comment]
Hey there
I recently gave this another shot and had some success in some games, less in others.

Games that worked correct with direct positioning of the mouse:
- Command & Conquer
- Syndicate
- Theme Park
- Master of Orion
- Master of Orion II
- Full Throttle
- Dune 2
- Burntime
- Jagged Alliance
- Island of Dr. Brain
- The Incredible Machine (mouse was a bit off on the Y position)

Games that did not work correct:
- Abuse
- The Secret of Monkey Island
- Monkey Island 2
- Indiana Jones and the Fate of Atlantis
- The Settlers
- Mad TV
- Windows 95/98

When it doesn't work, touching the screen/moving the mouse would either position the mouse wrong or not move the in-game mouse at all. Can you maybe try some of these games? Do you get better results on iDOS? I don't have an iOS device so please report back.

I think we can add an option for this though (probably disabled by default). Because when it works it's pretty nice.

**Comment by toughguystudios** [comment]
Thank you for looking further into this. I have only tried with 1 game Warcraft 2 on iDos and with DOSBox Pure in Retroarch. Here is what it looks like in iDos when I run Warcraft 2:

https://www.youtube.com/watch?v=eb-wpq0La7c

So in order to activate this ability, I figured there needs to be a way to configure it in Retroarch under Core Options? Maybe disable the gamepad overlay so that it's not in the way. Or allow for a Keyboard overlay to be turned on and off if needed, while still allowing this touch feature to be a thing? Thank you.

**Comment by schellingb** [comment]
Thanks for the video.
Warcraft 2 requires more than just left mouse clicks in the game. Two things that come to mind:
- Can you do the drag rectangle selection to select multiple units?
- Can you right-click to give units move orders?

Also to see if the compatibility is similar, could you try out this demo version of Monkey Island on iDOS? I'm really curious if you get the same behavior as I do whereas the mouse does not move like expected.
https://www.classicdosgames.com/files/games/lucasarts/mi1demo.zip

**Comment by toughguystudios** [comment]
Yep, with iDos you can do 2 finger touch to simulate right click:

https://youtu.be/vPVZZrpnd78

And as far as Monkey Island goes, it looks like it has no issues using the mouse:

https://youtu.be/96Uf9IVUTZc

**Comment by schellingb** [comment]
> Yep, with iDos you can do 2 finger touch to simulate right click:
Interesting! We maybe need something like this.

I'm thinking of adding a mode selection to the option.
- Default, similar to how it is currently, where the frontend (RetroArch) controls mouse
- Direct mouse movement, in games where supported the mouse moves where the real mouse or finger is
- Simulate touch pad with touch screen, this would be similar to how iDOS works
- Maybe another mode where the the mouse moves to where the finger is touched but still allow right click and drag & drop somehow

**Comment by toughguystudios** [comment]
Yeah that would be great! As I mentioned, I use the old iPad so there isn't really too much I can get out of this, even with the BTC mouse cydia tweak. I would rather use the touch screen/two finger touch method which is much more effective. I'm not even able to right click using BTC mouse cause it doesn't pick up the same.

**Comment by schellingb** [comment]
The newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader now uses the touch optimized mouse input mode by default on platforms that most likely have a touch screen over a physical mouse (like Android and iOS), so I'm closing this issue. If there are still input issues, please open a new ticket.
