### ISSUE TITLE
Wrong key mapping in Fatal Racing/Whiplash

### ISSUE THREAD

**Issue by litaniast** [schellingb/dosbox-pure#403]
Default Gear Up is 'R' and Gear Down is 'D', but both of them are 'D' key mapped in current dosbox-pure detected mapping.

![Fatal Racing-230616-184745](https://github.com/schellingb/dosbox-pure/assets/4857928/e2751f43-0519-460a-a5f1-f4b9e1f08f3e)

**Comment by schellingb** [comment]
Thanks for reporting this! Should be fixed in the next release.
