### ISSUE TITLE
DOSBox-Pure Firestick; Main device mouse arrow won't go away in the game

### ISSUE THREAD

**Issue by toughguystudios** [schellingb/dosbox-pure#405]
Hi, I'm running RetroArch for firestick with DOSBox-Pure, is there a way to hide the main mouse cursor in firestick after my bluetooth mouse syncs to my firestick, so that the mouse device can control the in-game mouse?
   I don't seem to have a problem at all with this on Mac or PC if I put Retroarch in Full Screen mode. The mouse cursor then disappears and I'm left with mouse functionality internally in the game menu moving the game cursor. But this doesn't seem to the be the case with Firestick. I even tried putting RetroArch into Full Screen mode but it didn't fix it. Any ideas? thank you.

**Comment by schellingb** [comment]
Looks like an issue report for it already exists on the RetroArch side:
https://github.com/libretro/RetroArch/issues/14016

**Comment by toughguystudios** [comment]
Thank you schellingb, I reviewed the stackoverflow post and the discord entry as well. It looks like this was submitted to the RetroArch Issues github a few weeks ago describing the issue:

https://github.com/libretro/RetroArch/issues/14016

**Comment by schellingb** [comment]
RetroArch for Android had a bunch of changes done regarding this recently. I'm closing this issue here now, if there's anything else we can start a new issue.
