### ISSUE TITLE
Compilation error since 91f3504

### ISSUE THREAD

**Issue by DrUm78** [schellingb/dosbox-pure#409]
A compilation error now occurs because of this commit: https://github.com/schellingb/dosbox-pure/commit/91f35042ce56b7c9b33b6fd282ad6e60611d4510
```
Compiling src/dbp_network.cpp ...
src/dbp_network.cpp: In function ‘void ModemBufAddS(CModemBuf&, const char*, ...)’:
src/dbp_network.cpp:781:26: error: ‘va_start’ was not declared in this scope
  781 |  char m[128]; va_list v; va_start(v, fmt); int len = vsnprintf(m, sizeof(m), fmt, v); va_end(v);
      |                          ^~~~~~~~
src/dbp_network.cpp:781:87: error: ‘va_end’ was not declared in this scope
  781 |  char m[128]; va_list v; va_start(v, fmt); int len = vsnprintf(m, sizeof(m), fmt, v); va_end(v);
      |                                                                                       ^~~~~~
make: *** [Makefile:235: build/release/src~dbp_network.cpp.o] Error 1
```

**Comment by schellingb** [comment]
Oh, thanks for noticing! I'm still a bit far from release of the next version so I've been testing mostly on Windows and Android. Interestingly both compile fine without including <stdarg.h> but it should be more correct now.

Thanks again for testing and reporting this. Are you going to try the new netplay stuff? If you do, you'll need a very recent version of RetroArch, too. The support for this was merged just 3 days ago. Please report back :-)

**Comment by DrUm78** [comment]
Compilation now works fine, thanks. 👍 

I cannot test the netplay stuff as my target platform does not support it (FunKey S handheld with no connectivity).
