### ISSUE TITLE
Force 60 FPS Output Audio Issue since commit a21746a

### ISSUE THREAD

**Issue by roslof** [schellingb/dosbox-pure#410]
Was trying to pin down an audio issue with dosbox-pure on my Raspberry Pi 4B, and determined the issue started with commit a21746a ([Move auto start logic from DBP_PureMenuState into new DBP_Run](https://github.com/schellingb/dosbox-pure/commit/a21746a9d80f37c85ce72e0bc2665367c245c7e3)).

Can test with Amnesia demo (which is a non-commercial software demo). I uploaded a version here:
https://drive.google.com/file/d/1Ow0NtFpR-2WHIv6-gPmzXlww5-gh13Hm/view?usp=drive_link

If Force 60 FPS Output is selected, audio becomes corrupt. While Force 60 FPS is unessential here, and the issue can be resolved by turning it off, it's worth noting that all prior commits did not exhibit this behavior. Several of my games which used 60 FPS exhibit the corrupt audio behavior, and turning off 60 FPS resolves the issue.

**Comment by schellingb** [comment]
Thank you both for reporting this and helping out with testing the main branch, very much appreciated!

The latest commit cbf3703 should revert one change introduced in the commit that broke things which wasn't really necessary anyway. Thanks again for catching this, glad it didn't make it into a release!

**Comment by roslof** [comment]
A pleasure, @schellingb
I confirmed that the fix appears to work. Thank you!

**Comment by roslof** [comment]
Verified fixed with multiple games including mentioned "Amnesia" demo.
