### ISSUE TITLE
MIDI Output won't work no matter what I do (Retroarch)

### ISSUE THREAD

**Issue by hello10293** [schellingb/dosbox-pure#413]
So I wanted to play some classic Windows 98 games using General MIDI via DOSBox Pure, but it just wouldn't work. I've looked for hours to find a solution, but it led me nowhere. I've tried multiple methods! Yes, DOSBox Pure is updated to the latest version, I've tried using sound fonts (and it's in the system directory in SF2 format), and I even tried to use the frontend midi driver in the settings, which didn't work at all. I also tried going into Windows 98's control panel to switch the output to general midi, but it only showed "Creative Music System". I have a Windows 11 PC, up to date. My midi output drivers still work, and can still output sound. I even used the midi mixer command (I forgot it) on the original version of DOSBox, and it showed the General Midi output. I need help.

**Comment by mtmrc** [comment]
Try going to Add New Hardware in Win98 Control Panel and detect, you should see MPU401, install it then select it in Multimedia instead of Creative Music System.

**Comment by hello10293** [comment]
I think this would've worked before I completely rebooted the virtual machine from scratch. Thank you anyway.
