### ISSUE TITLE
Feature request: Add swapstereo setting under [mixer]

### ISSUE THREAD

**Issue by InterClaw** [schellingb/dosbox-pure#415]
Some builds of DOSBox has the option to reverse the channels, but not the current main build. Would it be possible to add this option to DOSBox-Pure?

```
[mixer]
swapstereo=true
```

The game Terminal Velocity apparently shipped with the stereo channels reversed and there's no option to fix that in the game. I asked about this here, for reference:
https://www.vogons.org/viewtopic.php?f=33&t=95484

**Comment by schellingb** [comment]
@InterClaw I added a swap stereo audio option in 0.9.8, can you give it a try?

**Comment by InterClaw** [comment]
Tried it out in 0.9.9 now. Works great! Thank you!
