### ISSUE TITLE
Visual StudioCompilation in Visual Studio 2019 and newer

### ISSUE THREAD

**Issue by altiereslima** [schellingb/dosbox-pure#419]
I can compile successfully in Visual Studio, but it looks different (theme) and only runs some games.
![Sem título](https://github.com/schellingb/dosbox-pure/assets/18044879/1b33bb74-180a-4774-87c7-421ae1c1f083)

**Comment by schellingb** [comment]
Which games do not run?

**Comment by altiereslima** [comment]
Theme Park, Theme Hospital, FIFA Soccer 96

**Comment by altiereslima** [comment]
and more

**Comment by schellingb** [comment]
In what ways do these games not work? Describing the problem with more details would be much more helpful to actually fix it.

**Comment by altiereslima** [comment]
The games just don't open.
[dosbox_pure_libretro.zip](https://github.com/schellingb/dosbox-pure/files/12642834/dosbox_pure_libretro.zip)

**Comment by schellingb** [comment]
Using your DLL I get a crash upon game start. It does not happen with the version I compile with Visual Studio myself.
Can you open the project in your Visual Studio, switch the build configuration in the top menu bar from "Release" to "Debug" and leave the build platform at "x64" and then select "Build Solution" from the BUILD menu.

Then in your project directory, under \build\Debug_64bit\ you will find 2 files 'dosbox_pure_libretro.dll' and 'dosbox_pure_libretro.pdb' which you can ZIP up and upload here again. With this I can debug your build.

If instead you know yourself how to attach the debugger to RetroArch while running a debug build, you can see yourself where it crashes.

**Comment by altiereslima** [comment]
[Debug_64bit.zip](https://github.com/schellingb/dosbox-pure/files/12643801/Debug_64bit.zip)

**Comment by schellingb** [comment]
What Visual Studio version are you using? Looks like it generates broken code when it comes to the DOSBox dynamic recompilation core.
If you really want to use your own compiled build, you can switch the `Advanced > CPU Core` setting to `Normal (Interpreter)` in the Core Options > System menu.

**Comment by altiereslima** [comment]
I build it in Visual Studio 2019 and 2022. I'm not sure how to build it in MSYS2.

**Comment by schellingb** [comment]
Looks like DOSBox-X figured this one out, VS2019 and newer create broken code when compiling with optimizations. The latest version should work for you now. Thanks for reporting!
