### ISSUE TITLE
Double input from controller D-pad in start menu with "Custom Keyboard Bindings"

### ISSUE THREAD

**Issue by InterClaw** [schellingb/dosbox-pure#420]
I found this earlier issue, which corresponds pretty well with what I'm experiencing, but you said to log a new issue @schellingb if one had problems with the start menu, so here we are.
https://github.com/schellingb/dosbox-pure/issues/14#issuecomment-751023343

The problem:

- "Custom Keyboard Bindings" (CKB) always sends digital D-pad input to the DOSBox-pure start menu, regardless of your keyboard mappings. This leads to double input when you _have_ mapped your keyboard arrow keys to the D-pad.  
- "Generic Keyboard Bindings" (GBK) does not do this. This comes with the D-pad mapped to the arrow keys by default. If this is unmapped, then I get no input at all on the start menu (or in-game).

Settings:

- RetroArch 1.15.0 - DOSBox-pure (0.9.7)
- Bind Unused Buttons = Off
- Advanced > Automatic Game Pad Mappings = Off
- Analog to Digital Type = None

Experimentation:

- I get a notification that says "Detected keyboard and joypad being pressed at the same time" and that suggests to use Game Focus. However, Game Focus on/off does not change the behavior for the controller, but turning Game Focus on removes the problem for the physical keyboard, which is expected, since it then stops acting as a controller/hotkey combo.
- Only the start menu seems affected. I'm not getting this behavior in-game.
- Setting Analog to Digital Type to either Left Analog (Forced) or Right Analog (Forced) causes the same problem for that stick on the start menu. Left Analog or Right Analog does not.

Expected behavior:

- CKB should not send any extra arrow key input. It should only send what is mapped to it, like GBK does.

**Comment by unmacaque** [comment]
I am experiencing a similar issue with unexpected keyboard input _except_ that the problem also affects the game **but** it only occurs after opening RA menu once and do something, like loading a save state. The issue persists, until I fully close and load the content again. Should I open a new issue for this?

**Comment by schellingb** [comment]
Is this still an issue in 0.9.9 and are we sure that the core is at fault or is there a chance that the frontend is actually sending 2 double presses due to controller configuration or using the keyboard without entering "Game Focus" mode?

**Comment by InterClaw** [comment]
No it's not! You fixed it! Sweet! 😁

**Comment by nartahn** [comment]
> No it's not! You fixed it! Sweet! 😁

Is the only way to fix this behaviour to update to the latest core? I've been writing a python script to do custom keymaps only to come across an unfix-able double input issue.
My only way around it is to change it Automatic Keymapping and then change it back once in the game.
