### ISSUE TITLE
NBA Jam TE - In-Game Pausing Doesn’t Seem To Exist

### ISSUE THREAD

**Issue by martysept24** [schellingb/dosbox-pure#426]
Hi, 

There seems to be an inaccuracy with the automated keymapping for NBA Jam TE. It says you can pause by clicking Ctrl-P on the Dosbox Pure keyboard or whatever button the key combination is mapped to on your controller. But this has not worked for me. Is there a patch I need to download for Jam TE that includes the option to pause in-game? The lack of this ability in the Dos version of Jam TE has always puzzled/annoyed me (despite otherwise being a very good port).

**Comment by schellingb** [comment]
It's not easy to do mappings for 4000 games, the keyb2joypad project did a fantastic job nailing most of the games. There can be mistakes though, so maybe this is one of them? If you say Ctrl-P does absolutely nothing and there really is absolutely no way to pause the game (not even pressing ESC?) then I guess I can just remove that binding. I looked up the manual for the DOS version and it really does not mention a pause key, so maybe there just is none.
You can use the pause function of your emulator frontend (i.e. RetroArch) to pause any emulated game.
