### ISSUE TITLE
Regression - Some ZIP games no longer run after version 0.26

### ISSUE THREAD

**Issue by PoloniumRain** [schellingb/dosbox-pure#429]
It took me a while to track this one down... Since DBP version 0.9.0 some games in ZIP files no longer work. But they will work with the previous older version, 0.26.

So far i've found Screamer, Screamer 2, and Screamer Rally. There's probably more but i don't have time to look.

I have the eXoDOS versions (zipped) of all three Screamer games. When trying to run each game the DOS prompt will say it cannot find certain game files, or it will just go back to the Start Menu, and nothing you do there will be able to get the game to run. I've also had it crash back to the RA menu. But if i extract each game they will then work correctly. DBP 0.9.0 introduced this bug and it still exists in the latest 0.9.7.

Tested on Windows 10 with RA 1.16 and the latest RA nightly.

**Comment by schellingb** [comment]
This can get combined with #87 I think it's the same problem.

If the directory layout of the ZIP doesn't match with what is expected in the C: drive, then at the moment there isn't much that can be done except fixing the layout in the ZIP. My post from Jan 24, 2022 in #87 describes the overall issue, and why some ZIP files worked before that won't work anymore now, and also why some other ZIP files didn't work before which do work now.

Two potential "magical" solutions for this would be:
- Have the core detect the game and fake the layout of the C: drive to match what the game expects
- Have the core detect the game and force modify it's config files to match the layout in the C: drive

Both solutions are hard to implement and need game specific handling so I just haven't gotten around. In #87 I'm collecting a list of games that need to exist in a specific directory on the C: drive. We should add these to that list (if it's confirmed that this really is the problem).

**Comment by schellingb** [comment]
Improvements to this will be done via #87 so closing this.
