### ISSUE TITLE
Screamer 2 doesn't work.

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#433]
I tried to load all files available, nothing works.

Screamer 1 works fine using the .bat file. But the sequel does not.

**Comment by PoloniumRain** [comment]
Is this with a .ZIP file? If it is, see #429.

It should work if you change the .ZIP structure to look like this example with Screamer 1:

![layout](https://github.com/schellingb/dosbox-pure/assets/50634894/36c65650-535e-44c6-8d5b-80f6dd7bd0c3)
