### ISSUE TITLE
[Feature request] Allow mounted disc image to be stored/determined in AUTOBOOT.DBP

### ISSUE THREAD

**Issue by jroyvde** [schellingb/dosbox-pure#438]
This would really help for games with multiple discs, but needing a specific disc to be mounted when starting the game.

When choosing an .EXE with [SET AUTO START], the currently mounted disc image as selected at the top of the menu would also be stored in the AUTOBOOT.DBP, maybe on a second line. This would mean the correct disc image would always be mounted upon starting the game in future.

**Comment by schellingb** [comment]
Version 0.9.8 now does this so I mark this as closed. Thanks again for the request.
