### ISSUE TITLE
Save State Freeze Game "The Secret Agent"

### ISSUE THREAD

**Issue by liberodark** [schellingb/dosbox-pure#44]
I have issue from save state.
When i make save state that crash my game is ok but if you close and reopen the game and you restore save state the game freeze.

i have also change 16mb to 64mb but only work when game is open when you close game save state freeze the game "The Secret Agent"
log : [es_launch_stderr.log](https://github.com/schellingb/dosbox-pure/files/5757212/es_launch_stderr.log)

**Comment by schellingb** [comment]
Can you reproduce this or did this only happen once?

For Secret Agent, I think that is a pack with 3 episodes, each being launched with a different EXE file (SAM1.EXE, SAM2.EXE, SAM3.EXE). For a simple game like Secret Agent I don't think it should be a problem really, but try to make sure you run the same EXE when restoring as was running when the save state was made.
