### ISSUE TITLE
Sound font issues in 0.9.8

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#444]
I was using this soundfont in 0.9.7

[Roland SC-55_2.zip](https://github.com/schellingb/dosbox-pure/files/13633680/Roland.SC-55_2.zip)

And it worked fine in all games i tried. But in 0.9.8 it sounds wrong in DOOM II (didn't test many games yet so others might also have issues).

Did something change in the audio? Is it a bug? It's not an issue with the soundfont because it also sounds correct outside RetroArch.

**Comment by Tasosgemah** [comment]
Duke Nukem also sounds wrong, there are some annoying clicking sounds with some instruments.

0.9.7 sounds correct.

**Comment by PoloniumRain** [comment]
I also use that soundfont and have the same problem. 

Other soundfonts seem to sound ok (so far). Btw check out the [Arachno soundfont](https://www.arachnosoft.com/main/download.php?id=soundfont-sf2), Doom I and II sound great with it.

**Comment by Tasosgemah** [comment]
> Other soundfonts seem to sound ok (so far). Btw check out the [Arachno soundfont](https://www.arachnosoft.com/main/download.php?id=soundfont-sf2), Doom I and II sound great with it.

It sounds pretty bad IMO, but that's a matter of taste i suppose. That's why i avoid using custom/fan made soudfonts. I just want to use the "default" sound.

I also don't understand how the MT32 emulation works. When i use it, it sounds really bad. Then i found i have to use the "_control.rom" and "_pcm.rom". Ok so i found them, made sure the names are as shown in the "how to use" page and put them in the system folder. But there is no change, it sounds just as bad as before i even had the files.

**Comment by Tasosgemah** [comment]
> Other soundfonts seem to sound ok (so far). Btw check out the [Arachno soundfont](https://www.arachnosoft.com/main/download.php?id=soundfont-sf2), Doom I and II sound great with it.

It sounds pretty bad IMO, but that's a matter of taste i suppose. That's why i avoid using custom/fan made soudfonts. I just want to use the "default" sound.

**Comment by schellingb** [comment]
Thanks for reporting. It should be fixed again in 0.9.9. Can you give it a try?

**Comment by PoloniumRain** [comment]
Yep it sounds correct in 0.9.9.

Will version 1.0 be next? Out of beta?

**Comment by Tasosgemah** [comment]
Can confirm the soundfont now sounds correct in DOOM II and Duke Nukem 3D.
