### ISSUE TITLE
Disk Cycle freeze OS after update 0.9.8

### ISSUE THREAD

**Issue by emawind84** [schellingb/dosbox-pure#448]
When cycling disk on Windows 98, the OS freeze and stop working.
The disk cycle works fine with the previous 0.9.7 version of the core

**Comment by schellingb** [comment]
Hi there. I fixed this now and I'll try to get a new version out with this fix in the coming days. Thank you reporting this!!

**Comment by emawind84** [comment]
Awesome thanks!

**Comment by schellingb** [comment]
Can you try with the latest 0.9.9 release?
