### ISSUE TITLE
Content keeps running when RA menu is open

### ISSUE THREAD

**Issue by mrmatteastwood** [schellingb/dosbox-pure#45]
Hey, @schellingb, I noticed that games keep running in the background when I open the RetroArch menu, even though the following options are set to **ON** in RA:

- User Interface > Pause Content When Menu Is Active
- User Interface > Pause Content When Not Active

I encountered this issue on Linux Mint. No other cores (that I have installed) are affected. For instance, when running a Super Nintento Game in _Snes9x - Current_, or a PS game in _Beetle PSX_, they pause when I open the RA menu.

Also, this issue does not occur on Windows 10, where DOS games running in DOSBox Pure do pause when the RA menu is active.

I tried deleting retroarch.cfg and re-configuring RA from scratch, but the issue still occurs. Really odd, not sure what else to try.

**Comment by schellingb** [comment]
The [latest release](../releases/latest) should be better about this. I was able to get this on Windows by mashing the menu key. Now it better detects the frontend pausing. Can you retry on your Linux Mint installation?

**Comment by mrmatteastwood** [comment]
Yes! Works. Awesome :-)
