### ISSUE TITLE
Mouse movement is also keyboard at the same time in 0.9.9

### ISSUE THREAD

**Issue by Kensupen** [schellingb/dosbox-pure#451]
When left joystick is set to mouse movements and you play a game like Warcraft 2 where the arrow keys scroll the map and the mouse moves the cursor, in 0.9.7 the cursor moved on it's own. In 0.9.9 the screen scrolls with the mouse cursor movement.

Expected behavor: Mouse movement only moves cursor

**Comment by schellingb** [comment]
I don't get that behavior here. Did you select the mouse movement preset in the frontend or in the Gamepad Mapper? Did you set any additional mappings besides mouse movement? Also make sure to check the "Analog to Digital Type" option in RetroArch.

**Comment by Kensupen** [comment]
I found the error. The joystick was set to the stick direction and a key in RA input config. Once changed, it operated as expected. You can close this.
