### ISSUE TITLE
A is B and X is Y

### ISSUE THREAD

**Issue by InterClaw** [schellingb/dosbox-pure#454]
I noticed that in the Gamepad Mapper A is B and X is Y. It seems that DOSBox-Pure is using the classic SNES button layout, rather than the today more commonly used Xbox 360 layout.

Is this deliberately so? Is this a holdover from vanilla DOSBox perhaps? It _is_ different from how RetroArch has it at least, so it's a bit confusing until you understand what's going on, hehe.

![image](https://github.com/schellingb/dosbox-pure/assets/48981208/e264a88f-5e51-432b-97c0-fa3424fee109)

![image](https://github.com/schellingb/dosbox-pure/assets/48981208/8bbc9f48-7a72-435f-aade-944e09e08252)

**Comment by schellingb** [comment]
The core is not choosing this. We're using what libretro (the API) and the reference frontend RetroArch dictates. I think it would be much more confusing if we were to ignore that.

How did you get your RetroArch to use an XBox style button layout? I've never seen that, not do I know of an option to switch it.

![image](https://github.com/schellingb/dosbox-pure/assets/14200249/e8e42466-1af0-4903-8e8d-3054fdfde30f)

**Comment by InterClaw** [comment]
> Edit: Oh, I see, with a recognized controller plugged in, it will show the button names of the actual pad under `Quick Menu` -> `Controls` -> `Port X Controls`. Under `Settings` -> `Input` -> `RetroPad Binds` -> `Port X Controls` it always shows the image above.

I didn't investigate this properly I see now. 🤦 That's exactly it.

> 
> There's no way via libretro to figure out what kind of button layout the physical device that is assigned to a port has, so we can't really do anything here. Though we probably should change "A" to "A (Right)" to make it easier to understand.

Good idea! 👍
