### ISSUE TITLE
¿still no MMX support?

### ISSUE THREAD

**Issue by gordon81-afk** [schellingb/dosbox-pure#455]
Hello, first all i love your project, the last updates for me is the best christmas gift in years.

I have only a question, ¿why still not mmx support?,

**Comment by schellingb** [comment]
This is a libretro core of DOSBox and DOSBox does not have MMX support.

**Comment by schellingb** [comment]
#301 would get updated if there were any change to this.
It's not impossible, but it's not very high on my list of things I want for this core. If someone wants to contribute MMX support and it seems feasible (not too much added code complexity, working on all platforms we support and no downsides to any existing functionality) I'd certainly consider including it.
