### ISSUE TITLE
Some keyboard keys register with additional keys

### ISSUE THREAD

**Issue by Great-Dragon** [schellingb/dosbox-pure#46]
**Describe the bug**
W registers as W+2
S registers as S+SPACE
Q registers as Q+1
A registers as A+SHIFT
[ registers as [+SPACE
] registers as ]+SPACE

**It happens in all games**, but it works as expected during the setup for all of them (Doom, Duke, Descent). I don't have any issue in doxbox CLI as well.
So when I hit W key my character switches to a pistol during walking, Or he jumps during walking backward when I hit S.
My control is configured to "Generic Keyboard" and I have RetroArch hotkeys configured through Alt. So I don't think keys overlapping with RetroArch is the case (like space enables rewind)
Also I've disabled any gamapad detection just in case.

**To Reproduce**
Play any gave with the keyboard.
Also I found that the easiest way to check the keys is X-COM. As you have to type security code at the beginning of the game.

**Expected behaviour**
W should registers as W in games (and not W + 2)
S should registers as S (and not S + SPACE)

**Environment (please complete the following information):**
- Windows 10 2009

**Version of dosbox-pure:**
version 0.4

**Configuration parameters:**

**Additional context**

**Comment by schellingb** [comment]
Hey there, check the [chapter `Playing with keyboard and mouse` in the README](..#playing-with-keyboard-and-mouse) how to deal with the keyboard acting as both a keyboard and a gamepad (which is often mapped to keyboard keys).

Also the [newest version 0.5](../releases/latest) shows a message if both keyboard and gamepad gets pressed at the same time in the start menu in regards to this so it will be a bit more obvious.

Can this issue be closed with this?

**Comment by Great-Dragon** [comment]
Yes. Now with the "Game Focus" mode it works like a charm. Thanks
