### ISSUE TITLE
More system/CPU preset options?

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#476]
The available system/CPU presets are limited. There's only a single speed per CPU. And it's missing the most common 386DX/40 CPU.

It would be nice if you could use more CPUs, for a wider range of results. Or there could be a way to manually change the CPU cycles just like in regular DOSBox.

**Comment by schellingb** [comment]
It's important to note that the presets are really just very crude approximations. The DOSBox CPU emulation isn't accurate to real world CPU frequencies. The presets are just based on a few DOS benchmarks made with real CPUs and then the matching CPU cycles were chosen. But other benchmarks and games all do different kinds of work on the CPU so it won't really ever match up.

You did not mention the "Performance Scale" option which lets you increase or decrease the cycles set by the preset.

RetroArch/Libretro options are always only a selection from a list, so we can't present a number input. The other DOSBox cores choose to have multiple options to select multiplier factors to calculate a CPU cycle number but to me that is mind-bogglingly stupid. Even if I know an exact cycle number I'd want to input, it's annoying to enter that with these factors. Usually I just want to make things "a bit faster" or "a bit slower" so I always felt the performance scale via percentage we have was enough.

You can use `config -set cpu cycles 1234` to set a specific number in a batch file or directly in the command line.
