### ISSUE TITLE
Ecstatica hangs on Logo Screen

### ISSUE THREAD

**Issue by PittStone** [schellingb/dosbox-pure#480]
I can`t get "Ecstatica" to work on Dosbox Pure. It works fine with normal Dosbox, but on Dosbox Pure on Retroarch it still shows only the Logo Screen Title and does nothing. I testet many Versions, floppy, CD, French, Englisch, preinstalled. Nothing let me play the Game.

**Comment by PoloniumRain** [comment]
It worked for me on the first try. I have the eXoDOS version.

**Comment by PittStone** [comment]
> It worked for me on the first try. I have the eXoDOS version.
> 
> Extremely weird game btw....

Yes, thanks. eXoDOS Version works.
