### ISSUE TITLE
Sound broken on dune 

### ISSUE THREAD

**Issue by EricGuzmanSkotnitsky** [schellingb/dosbox-pure#482]
When I start dune from retroarch, It asks me to choose install.exe or DunePRG.exe. install.exe Causes dosbox to freeze while DunePRG launches the game successfully but sound is absent.

**Comment by schellingb** [comment]
For Dune, INSTLALL.EXE generates an executable file called DUNE.BAT which passes the selected sound settings to DUNERPG.EXE. So if you start DUNERPG.EXE directly you won't ever have sound. Can you try DUNE.BAT and report back if that fixes sound for you?

**Comment by EricGuzmanSkotnitsky** [comment]
Tried DUNE.bat. The only difference is the intro sequence is slightly longer, showing the cyro logo in addition to the virgin one. Still no sound

**Comment by schellingb** [comment]
Can you post the content of DUNE.BAT? For example, when you see DUNE.BAT listed in the start menu as `DUNE\DUNE.BAT`, can you select "Go to Command Line" and enter
```sh
TYPE C:\DUNE\DUNE.BAT
```
and write here what gets listed.

**Comment by EricGuzmanSkotnitsky** [comment]
I tried but half my keys won't work or are overridden by being dospure hotkeys

**Comment by schellingb** [comment]
I assume you use RetroArch? Check the documentation:
https://github.com/schellingb/dosbox-pure?tab=readme-ov-file#playing-with-keyboard-and-mouse
> To play not with a gamepad but with keyboard and mouse, be sure to use the 'Game Focus' mode available in RetroArch. By default you can toggle game focus by pressing the scroll lock key. While game focus is active, the hotkeys are disabled and keyboard will not cause retro pad button presses (which could cause multiple keys to be pressed at once).

**Comment by schellingb** [comment]
Another thing you probably could do is to run "INSTALL.EXE" like I mentioned in my first comment to generate a DUNE.BAT that enables sound output. That's how DOS games usually work.

**Comment by EricGuzmanSkotnitsky** [comment]
Tried that, didn't give me sound but here is what I got when I used type on the new file: 
@echo off
logo
duneprg ENG VGA EMS 386

**Comment by schellingb** [comment]
This is a configuration that is set to "Sound: No Sound" so there will be no sound in the game. Even though this isn't a support forum for how to run DOS games, here's what you need to do:
- Run INSTALL.EXE
- Select "Automatic configuration"
- Press ENTER
- It should say "Your selections have been saved."
- Run DUNE.BAT

If this doesn't work, try resetting the core options, maybe you somehow disabled the SoundBlaster.

**Comment by EricGuzmanSkotnitsky** [comment]
Done all that, did not work

**Comment by schellingb** [comment]
Do you see multiple INSTALL.EXE in the start menu?

**Comment by EricGuzmanSkotnitsky** [comment]
yes, I've tried both INSTALL.EXE and DUNE\INSTALL.EXE to no avail. They produce identical bat files as listed above

**Comment by schellingb** [comment]
When running INSTALL.EXE, after selecting "Automatic configuration", did it say "Your selections have been saved" or was there an error?

We can ignore the INSTALL program by writing DUNE.BAT ourselves. So if before you did `TYPE C:\XYZ\DUNE.BAT` now enter this into the command line:
```
echo duneprg ENG VGA SDB2207 EMS 386>C:\XYZ\DUNE.BAT
```
to manually generate the correct C:\XYZ\DUNE.BAT, then go into the start menu and launch that C:\XYZ\DUNE.BAT.

**Comment by EricGuzmanSkotnitsky** [comment]
Worked, thank you so much for your help and patience with me!
