### ISSUE TITLE
Ghostbusters II unrelentingly requesting disk 2 

### ISSUE THREAD

**Issue by SkyHighGam3r** [schellingb/dosbox-pure#49]
When loading up Ghostbusters 2 (eXoDOS release) after the intro-sequence the game requests disk 2. 
This happens regardless of the executable chosen, and also happens after running the install executable. 
This is happening with the RetroArch implementation, but (as with my other post) I was advised to post that here. 

(As a side note, It's entirely possible I'm doing something wrong with this game but I can find next to 0 documentation on this error in other DOSBox builds aside from 2 forum posts on ghostbusters related sites that mention they have the issue - but with no resolution posted)

**Comment by Solo187** [comment]
Had zero issues running eXoDOS stuff from the archives. No need to extract. I suspect that's where you're going wrong.

**Comment by SkyHighGam3r** [comment]
> 
> 
> Had zero issues running eXoDOS stuff from the archives. No need to extract. I suspect that's where you're going wrong.

I haven't had any 'general' issues with eXoDOS at all - Just this game in particular. 
I also haven't extracted anything, I'm running from the zip provided by their archives. 
The "Install" I mentioned is running the install executable after nothing else worked to see if it would fix the problem. 
Seemingly nothing will make this game run without asking for disk 2 at the end of the intro.

**Comment by Solo187** [comment]
Strange. All i need to do is select the run.bat after loading the archive with Dosbox pure and it just works. Are you using the Launchbox setup also? on windows?. If so, What i did was setup a seperate system called MS-DOS (Retroarch) & directly added the zips to that. Then put Retroarch in the Launchbox emulator folder. Then set Launchbox to use the Dosbox pure core to run them.

**Comment by SkyHighGam3r** [comment]
Is that when running this game specifically? or games in general?
I'm just running directly within RetroArch.
Navigate to the .zip, select DOSBox Pure, and Run. 
I can get games like DOOM, Duke Nukem, Elder Scrolls, Wolfenstein, Alone in the Dark, and tons of others running just fine.

It's just Ghostbusters II that gives this error.

**Comment by Solo187** [comment]
Just games in general. I run them through launchbox. But running them straight through retroarch is fine. Shouldn't make difference. Not sure what your issue could be. I just load the archive. Select run.bat from the file list. Select soundblaster and it's away.

**Comment by SkyHighGam3r** [comment]
I know Ghostbusters II has a glitch in the retail release regarding digital sound that causes a 'freeze' "during" the intro. I've tried running it in all the available sound modes though, and it's post intro with Venkman up on screen asking for disk 2 regardless of which setting. 

From everything I can tell this appears to be game specific, but I can't find any documentation online about running into this error with this game on DOSBox and a subsequent resolution.

**Comment by Solo187** [comment]
Here's what happens when i run it. Seems to work fine?

https://drive.google.com/file/d/128-0UwGRa-Rt9TsM9r_o5GpoQQrGPhz6/view?usp=sharing

**Comment by schellingb** [comment]
I can't see a request for disk 2 either.
The game runs fine here with `GB2.BAT`.
I tried some of the other executables and the closest to this report I get is with `SHELL.EXE` which plays a different cut-scene every time and sometimes the intro it seems but never proceeds to the game.

**Comment by SkyHighGam3r** [comment]
I tried every option dozens of times. I mean I can't over-emphasize the number of attempts I made to get this game going. Never-the-less, for some reason, GB2.BAT now runs as you guys describe. 

I don't know if something updated or what.

Anyway I appreciate your guys help though. It's more response than I've gotten regarding the game anywhere else on the internet, so thank you.
