### ISSUE TITLE
Midi soundfont use crash RetroArch in android 13

### ISSUE THREAD

**Issue by tails101** [schellingb/dosbox-pure#491]
Only RetroArch bugs should be filed here. Not core bugs or game bugs
This is not a forum or a help section, this is strictly developer oriented
Description

It seems google introduced a bug in android 13 from what I heard and some midi port are not working, a lot of midi apps found a fix to make midi work again. But it seems RetroArch still suffer from a crash when using a midi soundfont.
Setting the output to Roland mt32 (Munt) or opl3 emulation (mame or nuked) or gravis ultrasoud emulation fix the problem and sound work without crashing. But using any soundfont and midi mode just close RetroArch.
This is not a ram issue, I'm using a raspberry pi 4 with 8gb of ram and any size of soundfont just crash RetroArch. (Even the windows 3.1 soundfont of 5mb just crash RetroArch).
I have found the same issue in a few midi apps and there are discussion about it online.
I'm using for example the stand alone version of scummvm because it has a fix already implemented for this issue and work properly even with giant soundfont files like timbre of heaven.

Expected behavior

Not crash
[What you expected to happen]
Not crash

Actual behavior

RetroArch close without explanation
[What is actually happening]
RetroArch closes without explanation

Steps to reproduce the bug

Put a soundfont in system directory
Start dosbox pure
Select in core option the soundfont
In game option set the output to midi
RetroArch should close immediately when playing a sound.
Bisect Results

[Try to bisect and tell us when this started happening]

Version/Commit

RetroArch stable android 1.18.0

RetroArch: [version/commit]
Environment information

OS: android 13 lineage os
Compiler: [In case you are running local builds]

**Comment by jmaneyrol69** [comment]
@tails101 @schellingb I am having the same issue on my Retroid Pocket devices (RP3 and RP4), so this probably affects at least Android 11 and above; using SoundFont as midi output device crashes the core and RetroArch as soon as dosbox-pure tries to produce some midi sound.

Using MUNT (MT-32/CM-32L) or GUS for midi works.

I have tested several .sf2 soundfonts as well (from 3 to 64MB).

I am using RetroArch 1.19.1.

**Comment by schellingb** [comment]
Sorry everyone for not fixing this sooner. The opening message just had me confused with talk about other MIDI apps. This just straight up crashed on Android as soon as the first note is being played with any soundfont. This is fixed now with 87691af which will hopefully make it into a release soon.

Here's a build of the latest core for ARM64 Android: [dosbox_pure_libretro-android-arm64-0.9.9b-20240723.zip](https://github.com/user-attachments/files/16353535/dosbox_pure_libretro-android-arm64-0.9.9b-20240723.zip)
If you extract that ZIP onto the device, the core should be installable by selecting "Load Core" and then "Install or Restore a Core".

**Comment by jmaneyrol69** [comment]
@schellingb Just tested your build and it perfectly works so far :+1:
@tails101 just a word of advice for the future: you should add meta-information between brackets in the title of your issues so they are easily identifiable by a dev. For example: "[Crash][Android] Midi soundfont use crash RetroArch in android"

**Comment by tails101** [comment]
> @schellingb Just tested your build and it perfectly works so far 👍 @tails101 just a word of advice for the future: you should add meta-information between brackets in the title of your issues so they are easily identifiable by a dev. For example: "[Crash][Android] Midi soundfont use crash RetroArch in android"

Yea sorry will do.coudnt test sorry my android installation on the pi got corrupted soi moved to a Linux distro instead to emulate.but I'm glad the bug was fixed and it wasn't just my device.

**Comment by tails101** [comment]
Main one is not updated still so I'm using this version.
Works great!

**Comment by jmaneyrol69** [comment]
@schellingb just one question, a bit off-topic: is there a way to get Android builds from this branch without compiling ourselves? I am asking because this branch is way ahead of main :cry:

**Comment by schellingb** [comment]
The fix is now finally released in the newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader, thanks for waiting!
