### ISSUE TITLE
(0.9.9) Bug "Dos crashed: corrupt MCB chain"

### ISSUE THREAD

**Issue by Gamesirvictim** [schellingb/dosbox-pure#496]
I played queen the eye on RetroArch for Android. On version 0.9.7 the game was working great. After I downloaded version 0.9.9 the game keep crashing and a massage appear "Dos crashed: corrupt MCB chain " . I tried it with two different devices. I can confirm the problem only happens on version0.9.9 . Thanks. Update: I tried core ver 0.9.8 and it has the same error as 0.9.9 .

**Comment by schellingb** [comment]
The fix is now released in the newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and on the RetroArch online core downloader.
