### ISSUE TITLE
Resolution: Original?

### ISSUE THREAD

**Issue by chinagreenelvis** [schellingb/dosbox-pure#499]
Testing using regular Dosbox on an old laptop that has VGA out to a CRT, output set to overlay, fullscreen res set to original, and the scaler set to normal2x, I get the best results, basically an exact match to running the game from Freedos on a similar machine.

What's the best way to get Doxbox Pure to run the same way, graphics-wise, instead of just using my desktop resolution and scaling up? Is it even possible while still using Retroarch?

**Comment by schellingb** [comment]
RetroArch has a first-class post-processing system for video output that is leaps beyond the capabilities of regular DOSBox. But it also works a bit different and has endless customizability to get the exact look you want on the type of display you have. This is not a RetroArch support forum so there won't be too much I can help you with but look into the documentation of RetroArch like:
- https://www.retroarch.com/?page=shaders
- https://www.youtube.com/watch?v=YyZ6IrmsNgY
- Various other web results when searching for "retroarch shaders"

The standard shader pack of RetroArch comes with a plethora of scaling shaders, maybe you can try "scalenx/scale2x", "scalehq/2xScaleHQ" or "scalefx". You could also try to ask on the RetroArch Discord if you need help with further customization.

**Comment by chinagreenelvis** [comment]
More than familiar with shaders, which are mostly unimpressive. What I'm trying to do is to get Dosbox Pure games to run at their native resolution on a CRT - which is easily done in regular Dosbox.

I thought the CRT switchres option might have something to do with it but I haven't managed to get anything to work right.

I forget, is there a way to use .conf files to override the Retroarch output settings?

**Comment by schellingb** [comment]
No a core can't do anything specific with how things are output by RetroArch or any frontend. It reports the emulated screen resolution, orientation and aspect ratio, and the frontend does the rest. RetroArch has plethora of options how to act in full screen including CRT switchres. Again I don't know much about RetroArch, you really should ask them.

**Comment by chinagreenelvis** [comment]
Cool, thanks!
