### ISSUE TITLE
Master of Orion 2. Cannot override previous save file

### ISSUE THREAD

**Issue by geng074** [schellingb/dosbox-pure#502]
![IMG_7825](https://github.com/schellingb/dosbox-pure/assets/139104911/40571836-107b-4248-976e-5297f125b2b6)

I am playing master Orion 2 on Retroarch on iOS. 

I can save game. 
but when I try to override older save game with new save. 
the new content will not be saved. 

I can click the old save and rename it. But the new save content will not be saved. 

(Referring to the screen shot. I can no longer save any game once the save file slots are filled )

**Comment by geng074** [comment]
I can over ride the save games initially (when game is first launch from RetroArch)

But after that I can’t. 

I suspect I can over ride the first time because the new save file are created in the newly created save game zip file in RetroArch which can over ride the old save game in the dos directory. 

but once this RetroArch save game zip file is created. I can’t over ride the saves anymore.

**Comment by geng074** [comment]
I managed to get it working. 
instead of loading a zipped up the game.  

I load the game without zipping up. 

The saving works perfectly now. 
(because dosbox can modify the directory directly instead of needing to over ride with save zips )

**Comment by alexb3d** [comment]
Tengo dos dudas. 
@geng074 are you using eXoDOS?

@schellingb this fix is already in the core? because I'm testing and I don't get the error.

**Comment by geng074** [comment]
I am using retroarch 
Anyway I have stopped playing the game. 

So may be the bug is already fixed.

**Comment by schellingb** [comment]
> @schellingb this fix is already in the core? because I'm testing and I don't get the error.

The fix is in fc44a23 which has not been released in a versioned number yet. It works to some degree but the game shows the dates wrong if I remember correctly.

**Comment by alexb3d** [comment]
> I am using retroarch

I think I can guess that. 

eXoDOS is a pre-configured package of the games and sometimes gives errors, such as not saving games.



> It works to some degree but the game shows the dates wrong if I remember correctly.

I'm going to check this well, although it may be a native bug in the game.
The game has an official patch 1.31, but there is also an [unofficial patch 1.50](https://moo2mod.com/) that fixes many graphic errors (exodos has it included).

**Comment by schellingb** [comment]
The fix is now released in the newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader, so I'm closing this issue.
