### ISSUE TITLE
[Feature request] BASSMIDI

### ISSUE THREAD

**Issue by Torinde** [schellingb/dosbox-pure#508]
[BASSMIDI](https://www.un4seen.com/), a MIDI software synthesizer that supports SF2/SFZ soundfonts.

[Explanation](https://github.com/dosbox-staging/dosbox-staging/issues/324#issuecomment-620109803):
> a large number of soundfonts having been designed with BASSMIDI in mind and as a result they sound wrong with fsynth. Whenever you use a soundfont with fsynth that has distortion/clipping issues with some instruments while others are barely audible, or some of them just sound completely broken, you use BASSMIDI instead and it sounds completely fine. That usually means the soundfont's author was using BASSMIDI.
>
> On Windows, people simply use some kind of BASSMIDI driver. There's no such thing on Linux (at least not without resorting to Wine) and macOS, so that's why this was added directly into dosbox.

**Comment by schellingb** [comment]
Bassmidi is closed source so it doesn't really fit this project.
Ideally the soundfont library we use would be improved via contributions to that project so we reach more compatibility and audio quality.

**Comment by schellingb** [comment]
Not a fan of SFZ, I've ranted about it here https://github.com/schellingb/TinySoundFont/issues/71#issuecomment-983655354
Also I don't think SFZ is meant to be used with General MIDI, which is what we need in DOS games.
Chance of BASSMIDI support is certainly higher than direct SFZ support :-)
