### ISSUE TITLE
How to avoid Scan Disk when shutdown windows 98 by close content directly?

### ISSUE THREAD

**Issue by guozanhua** [schellingb/dosbox-pure#516]
When I closed Windows 98, I used an abnormal shutdown method. For example, while playing a Windows 98 game, clicking "Close Content" directly from RetroArch may result in scanning the disk the next time Windows 98 is launched. Is there any way to avoid it?

**Comment by leilei-** [comment]
Start>Run>msconfig, advanced>Disable Scandisk after bad shutdown

**Comment by schellingb** [comment]
Keep in mind pressing "Close Content" when running Windows 98 inside DOSBox is equal to unplugging the power of a real computer running Windows 98. It can cause file system errors (some fixable by ScanDisk and some not).

The core can be configured to discard any changes made to the C: drive. Then "Close Content" is much less likely to cause problems. Though some games or procedures will probably not work if changes to C: are discarded.

**Comment by alexb3d** [comment]
I do not recommend to disable the scandisk, it is a system protection system. 

Pure has the option 'Discard' in System/OS Disk Modifications. This freezes the C disk, you can close it as you want. Keeping in mind that if you want to install a new game, you must disable the Discard.

Before activating it, I recommend you to start windows, reboot, close windows and before closing the core, activate the option.

**Comment by i30817** [comment]
It's possible to do a adhoc discard to system modifications even on the original dosbox if you do Linux tricks, namely using the dosbox autoexec section to copy a (in effect unmodifiable after setup) OS image to /dev/shm (a Linux filesystem that holds a representation of your free memory where you can place or delete files).

Then copy the OS image there and mount and boot that alongside the actual game drive.

This has the problem this doesn't prevent your games _drive_ from initiating scandisk in a hard shutdown so it's mostly useless, but that's the only way to have save games or config modifications unfortunately. It's possible to protect the game drive too using a copy on write filesystem, but those still show the scandisk, it's just you can delete the modifications to get back to the original image.
