### ISSUE TITLE
MIDI output issue in "Road Rash" (Windows 98 + MPU-401)

### ISSUE THREAD

**Issue by Ric-82** [schellingb/dosbox-pure#518]
Hi, 

I'm having a weird problem with the 1996 Windows game "Road Rash". The game plays midi files during the levels, so it benefits greatly from the ability to use Soundfonts instead of the standard Creative Music Synt output. Setting the Roland MPU-401 option as a midi output device in Windows actually allows me to load and correctly use all the Soundfonts present inside my "System" subfolder.

However, unlike Creative Music Synth, when game music is played through the MPU-401 it keeps playing in a loop, even after exiting the levels and returning to the main menu. The only way to stop it is to exit the game (and even then, it continues to play for a few seconds before stopping).

I did some research and saw that the game exhibits this same behavior with external MIDI mappers such as Coolsoft VirtualMIDISynth. From what I understood reading [this thread on Vogons](https://www.vogons.org/viewtopic.php?t=87487), the problem seems to be related to the lack of support for the midiOutSetVolume function, which is not implemented in synthesizers such as MPU-401.

Eventually, Coolsoft's technical support managed to bypass the problem in VirtualMIDISynth (as you can see from [his post on Vogons](https://www.vogons.org/viewtopic.php?p=1064063#p1064063): "I suppose the game does not really need for a full implementation of midiOutSetVolume() function, but it only needs that its calls to modMessage() to return MMSYSERR_NOERROR instead of the current MMSYSERR_NOTSUPPORTED. That said, I've built a test version with this change: the modMessage() function of MIDIMapper now always returns MMSYSERR_NOERROR (even if it does nothing at all with the given data)."). 

Do you think it is possible to solve this problem in the same way on DosBox Pure?

**Comment by schellingb** [comment]
It looks like the issue isn't in the hardware emulated, but rather in the software. The set volume function is not implemented in the Roland MPU-401 that ships with Windows 98. You would need a different driver with more capabilities that still sends MIDI commands to the same MPU-401 port. Maybe such a driver is out there somewhere?

**Comment by Ric-82** [comment]
I have no idea.

I can only hope for the advice of someone more experienced than me.
