### ISSUE TITLE
[Suggestion] Add midiconfig option from .conf file

### ISSUE THREAD

**Issue by KainXVIII** [schellingb/dosbox-pure#52]
For some of us who have hardware midi synthesizers.

**Comment by schellingb** [comment]
This is on my TODO list. But instead of it using a .conf file or accessing the hardware directly, the core will use the Midi driver of the libretro frontend. In RetroArch you can find the settings for it under `Settings > Driver > MIDI` and `Settings > Audio > MIDI`.

**Comment by KainXVIII** [comment]
> This is on my TODO list. But instead of it using a .conf file or accessing the hardware directly, the core will use the Midi driver of the libretro frontend. In RetroArch you can find the settings for it under `Settings > Driver > MIDI` and `Settings > Audio > MIDI`.

Thanks!

**Comment by schellingb** [comment]
On Linux there's an Alsa MIDI driver as well. But yeah, it's certainly missing a coremidi/coreaudio driver for OSX and maybe Linux could use an OSS driver. But on Windows I think winmm is all you'd need, no?

**Comment by KainXVIII** [comment]
> On Linux there's an Alsa MIDI driver as well. But yeah, it's certainly missing a coremidi/coreaudio driver for OSX and maybe Linux could use an OSS driver. But on Windows I think winmm is all you'd need, no?

No, you can't choose which midi device to use, like in plain dosbox. With mixer /listmidi command you can see which midi you have in system (by default its using MS soft synth sadly) and change it to which you want through midiconfig settings in .conf file.
![dosbox](https://user-images.githubusercontent.com/16922126/103463269-538c1d00-4d3c-11eb-9f19-4bcb778e7835.jpg)

**Comment by schellingb** [comment]
It works somewhat similar in RetroArch.
For it to work, you need to enter the full midi device name into `Settings > Audio > MIDI > Output`.
I'm aware that there is no text pasting in RetroArch and it doesn't even list the midi device names anywhere but it works. Hopefully once more cores use the MIDI functionality of RetroArch there's incentive to make it a bit more userfriendly.
External tools like [midienum.exe](https://matthewvaneerde.wordpress.com/2012/09/21/enumerating-midi-devices/) would list the names like `mixer /listmidi` in native DOSBox.

**Comment by schellingb** [comment]
You can check it out with the [latest release](../releases/latest).
When selecting "Frontend MIDI driver" in the option "Audio > MIDI Output" it should go through the MIDI driver of the frontend. If the MIDI output is not set up correctly in the frontend, it shows a message on startup "The frontend MIDI output is not set up correctly".

**Comment by KainXVIII** [comment]
> You can check it out with the [latest release](../releases/latest).
> When selecting "Frontend MIDI driver" in the option "Audio > MIDI Output" it should go through the MIDI driver of the frontend. If the MIDI output is not set up correctly in the frontend, it shows a message on startup "The frontend MIDI output is not set up correctly".

Excellent, works for me!

**Comment by mrmatteastwood** [comment]
Hey guys, this fix only works if one has an actual hardware MIDI device hooked up to their computer, correct? There's no way to use MIDI emulation through this new feature?

**Comment by KainXVIII** [comment]
> Hey guys, this fix only works if one has an actual hardware MIDI device hooked up to their computer, correct? There's no way to use MIDI emulation through this new feature?

I also used Roland Sound Canvas VSTi plugin (SCVA on my screenshot above) in dosbox-pure

**Comment by mrmatteastwood** [comment]
Was that in Windows or Linux? I did some digging today (being on Linux Mint 20), and I ended up installing Timidity++ on my system and launching it as a server, and lo and behold, Timidity showed up as an output device with 3 ports in Retroarch Settings > Audio > MIDI. However, when I ran DOS games with Roland sound (e.g. Cannon Fodder or Speedball II), no sound played.

**Comment by KainXVIII** [comment]
> Was that in Windows or Linux? I did some digging today (being on Linux Mint 20), and I ended up installing Timidity++ on my system and launching it as a server, and lo and behold, Timidity showed up as an output device with 3 ports in Retroarch Settings > Audio > MIDI. However, when I ran DOS games with Roland music (e.g. Cannon Fodder or Speedball II), no music played.

Win10.

**Comment by Tasosgemah** [comment]
Midi device doesn't work for me properly. In Duke Nukem setup 'm choosing "general midi" and in RA sound options i choose the midi player of my sound card. Then i do a restart and go to test music. I can hear the music playing. But when i go to the game itself, music is muted. I then go to the setup, test music again and it's muted.

I have to set my midi device to "off" then enable it again for the music to work in the setup but then it mutes again ingame. It's pretty weird, i don't know what to do for it to work properly.

**Comment by schellingb** [comment]
It seems weird to me that it works in setup but then - without restarting the core or RetroArch at all - it doesn't work directly after by doing "Save and launch". Nothing should have changed emulation wise since setup and the game there.
Do other setup options apply to the game? Maybe it isn't saving the settings or something...

**Comment by Tasosgemah** [comment]
I tried everything. For 2 hours i'm trying every option combination. I can hear the sound in the setup utility but not in game.

Here's another weirdness. I run the setup and test the music, i can hear it clearly. Then i run the game, i hear no music. If i exit RA and open it again and run the setup, i hear the music normally.

Now the weird part. If i exit the game (where i can't hear any music), without closing RA (i select the restart option) and then run the setup, i can't hear the music there also! It's as if running the game changes something and i have to restart the whole thing. But even then, i can only hear music in the setup/test area.

I was waiting for the midi option just for this game, lol. But this weird issue is way above my head.

**Comment by Tasosgemah** [comment]
Aaaan DOOM also has the same issue.

So i guess it's not the game but the core itself...

**Comment by schellingb** [comment]
Have you tried the alternative of using a .sf2 sound font file?
For example, you can place the file https://github.com/coelckers/gzdoom/raw/master/soundfont/gzdoom.sf2 into the RetroArch `system` sub-directory, restart DOSBox Pure and then it should be selectable in the `Audio > MIDI Output` besides "Frontend MIDI driver".

**Comment by Tasosgemah** [comment]
Yes, fonts work, they did before the update, but i can't find one that sounds as good as Midi. Regular dosbox works fine but Pure gives me these issues.

Ok so here's some new findings:

While playing the game (and hear no music) i go to the midi options in RA and change the midi device to OFF and ON again, _without closing the game_ in real time. This seems to wake up the device and i can hear music. But, there is more weirdness... Sometimes when i do it, the instruments are all over the place. Instead of hearing the regular instrument i hear... piano music. DOOM with piano, that's fun. Other times the music is fine. It's a matter of luck or timing.

**Comment by schellingb** [comment]
Do you have the RetroArch option
`Settings` → `Video` → `Threaded Video`
set to ON?
I recently realized that this could potentially cause weird issues but have not yet investigated much into it.

**Comment by Tasosgemah** [comment]
No, that option is OFF

**Comment by KainXVIII** [comment]
Only noticed now (because i only tested on one game, sorry), that MIDI not playing in Doom 2 or Lost Vikings for example, only works in Duke Nukem 3d for some reason..

**Comment by Tasosgemah** [comment]
I was hoping Version 0.8 would fix the issue with midi music not loading because it says something on that topic in the change log. Unfortunately, i'm getting the exact same behavior with version 0.7. Midi music in Duke Nukem and Doom doesn't load. 

It works in the setup menu because you press a button to manually load the music. But when a game has to load the music automatically, it doesn't.

**Comment by KainXVIII** [comment]
> I was hoping Version 0.8 would fix the issue with midi music not loading because it says something on that topic in the change log. Unfortunately, i'm getting the exact same behavior with version 0.7. Midi music in Duke Nukem and Doom doesn't load.
> 
> It works in the setup menu because you press a button to manually load the music. But when a game has to load the music automatically, it doesn't.

Anecdotally, i'm actually have music in Duke3d (but not in Doom 2). 
Proof attached
![midi](https://user-images.githubusercontent.com/16922126/104245454-5a6e0a80-5475-11eb-9a1f-eeeff8d7a20a.jpg)

**Comment by Tasosgemah** [comment]
I have no music in either game, unless i do something to manually force it to start. Disalbling/re-enabling the midi device in RA audio options, forces the music to start. However, if i do this in Duke Nukem, the music plays with the wrong samples/instruments (it uses piano samples for whatever reason).

**Comment by KainXVIII** [comment]
> I have no music in either game, unless i do something to manually force it to start. Disalbling/re-enabling the midi device in RA audio options, forces the music to start. However, if i do this in Duke Nukem, the music plays with the wrong samples/instruments (it uses piano samples for whatever reason).

Yes! Exactly my problem (but in Doom 2, Duke3d starts normally)! Btw, when music changes sample starts to play properly.
PS - found that i don't need to type manually midi output lol, just press right or left arrow keys to select them..
![20210112105338_1](https://user-images.githubusercontent.com/16922126/104285700-0c80f300-54c5-11eb-9ef0-cf42f51e587c.jpg)
![20210112105357_1](https://user-images.githubusercontent.com/16922126/104285704-0db22000-54c5-11eb-9931-3b203a0b812c.jpg)

**Comment by schellingb** [comment]
@KainXVIII Wow I wish I knew about that! I noticed that in code there are ways to list the device names but I thought selection wasn't implemented properly in the RetroArch menu. Thanks for posting about this :-)

I'll try again with some more games tonight.
Btw. the discussion about this remaining issue is in #70.

**Comment by KainXVIII** [comment]
> @KainXVIII Wow I wish I knew about that! I noticed that in code there are ways to list the device names but I thought selection wasn't implemented properly in the RetroArch menu. Thanks for posting about this :-)
> 
> I'll try again with some more games tonight.
> Btw. the discussion about this remaining issue is in #70.

Thanks, moving to #70 then =)
