### ISSUE TITLE
[Reques] Option to disable/enable touchscreen emulated mouse in Android to avoid double input press when using retropad.

### ISSUE THREAD

**Issue by demodanza** [schellingb/dosbox-pure#53]
Hi! Amazing job on the core, seems super promising!

As the title says, an option to disable touchscreen mouse input in Android would be ideal. As it is now, when using a gamepad overlay to press, for example, up, also registers as a mouse click or movement, which makes almost impossible to play some games with double input per button press, even moving down at the boot screen to get to the exe to start a game was a chore with all the previous options getting clicked before getting there.

With an option to disable it, one could just emulate mouse with the analog stick (virtual), option which already exits in the controller bindings, without a second input in the way plus the benefit of binding more keys to other joystick buttons.

**Comment by schellingb** [comment]
hmm, yeah I think this needs a new option.
`Input > Advanced > Disable Mouse Input`
`Disable input handling from a mouse or a touchscreen (emulated mouse through joypad will still work)`
Kinda like this?
Should this perhaps be enabled on Android by default? Is there anyway to use the touchscreen as the mouse as is now? Does swiping move the mouse around properly in mouse games?

**Comment by demodanza** [comment]
Yeah, that's why it's annoying, it's like that by default. Sliding through the screen moves the mouse, and tapping it does a click, but the movement is kinda sluggish and imprecise and gets in the way of any other input.
Looked around on the settings to see if was something toggleable in Retroarch, but didn't find an option to disable it, there's only an option to enable/disable touch input on menus, but doesn't affect input ingame, that's why assumed it was a setting specific to the core.
