### ISSUE TITLE
AUTOBOOT.DBP should allow forward slashes for command switches; it does not currently

### ISSUE THREAD

**Issue by SpiralBrad** [schellingb/dosbox-pure#531]
Current behavior: AUTOBOOT.DBP does not allow forward slashes for command-line parameters.

Expected behavior: AUTOBOOT.DBP allows the use of forward slashes for command-line parameters.

(Using DOSbox-pure 0.9.9)

---------

Essentially, I am trying to have an AUTOBOOT.DBP for Wolfenstein 3-D that runs it with the /GOOBERS cheat parameter.

Command-line parameters DO work for other games; for example, Tetris Classic lets you specify video and sound parameters on the command-line, and launching without ANY parameters causes it to prompt you.

An AUTOBOOT.DBP for Tetris Classic that contains: `C:\TETRISC\TETRISC.EXE` will prompt you.  If it contains 
`C:\TETRISC\TETRISC.EXE V A`, it does not prompt, and uses VGA and AdLib, as you specified them.  This confirms that AUTOBOOT.DBP does allow command-line parameters.  (This does not seem to be documented.)

For Wolfenstein 3-D, if AUTOBOOT.DBP contains `C:\WOLF3D\WOLF3D.EXE /GOOBERS`, all that happens is a blinking cursor and nothing happens further; no errors or anything.  The proper behavior seems like it should launch just fine.  I am unsure what causes the blinking cursor.

**Comment by SpiralBrad** [comment]
Cheers, @schellingb!

**Comment by alexb3d** [comment]
You can run `wolf3d -goobers` or `wolf3d goobers` with the same result.

The "/" parameter is intended for Batch files.

Additionally, you can create a GOOBERS.BAT file and write inside `WOLF3D /GOOBERS`, (or any of the above) place it next to the executable and start that batch with the AUTOBOOT. This works for any game.

**Comment by alexb3d** [comment]
A trick. 

With the _'echo xxx >file.txt '_ command you can create a simple one-line batch, without exiting PURE.

At Command Line C:\> (and with Game Focus set to On) is written:

`echo CHESS /COMP >CGACOMP.BAT `

Press enter to save, the file is created in the game save.zip and can be started from PUREMENU.

![Captura de pantalla de 2024-09-11 19-00-57](https://github.com/user-attachments/assets/4651a934-6a56-4907-82ae-25f803b4cd54)

**Comment by schellingb** [comment]
This was now fixed in the newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader, so I'm closing this issue.
