### ISSUE TITLE
No sensitivity with Xbox Controller 

### ISSUE THREAD

**Issue by reignerdeustcher** [schellingb/dosbox-pure#539]
I have an xbox serie s controller and i noticed that in racing games the analog behaves like a normal button of the keyboard, in the joystick calibration is like on or off, no progressive movement, is there anything to change this??

**Comment by schellingb** [comment]
By default it will be mapped to keyboard keys and the emulated DOS joysticks are disabled.

But when you switch the input preset to one of the following:
- First 2 Button Joystick
- Second 2 Button Joystick
- Thrustmaster Flight Stick
- Both DOS Joysticks

The DOS joystick(s) will become active and should be available in games that support them with full analog axes. You can select the preset either in RetroArch under `Controls` -> `Port X` -> `Device Type`, or via the Gamepad Mapper available in the start menu or the on-screen keyboard. 

Another option you have in the Gamepad Mapper is to define a custom mapping which lets you assign any analog input (including things like analog triggers) to the 4 analog DOS joystick axes.

**Comment by reignerdeustcher** [comment]
> By default it will be mapped to keyboard keys and the emulated DOS joysticks are disabled.
> 
> But when you switch the input preset to one of the following:
> 
>     * First 2 Button Joystick
> 
>     * Second 2 Button Joystick
> 
>     * Thrustmaster Flight Stick
> 
>     * Both DOS Joysticks
> 
> 
> The DOS joystick(s) will become active and should be available in games that support them with full analog axes. You can select the preset either in RetroArch under `Controls` -> `Port X` -> `Device Type`, or via the Gamepad Mapper available in the start menu or the on-screen keyboard.
> 
> Another option you have in the Gamepad Mapper is to define a custom mapping which lets you assign any analog input (including things like analog triggers) to the 4 analog DOS joystick axes.

it really works, thanks
