### ISSUE TITLE
Enhancement - allow binding of full keyboard with Keyboard+Right Mouse

### ISSUE THREAD

**Issue by romadu** [schellingb/dosbox-pure#54]
Hi,
I'm trying to configure Elder Scrolls - Daggerfall on RG351P. The best device type seems to be Mouse with Right, but this has a very restricted list of keyboard keys that can be assigned. Mouse-look works well on the right analog, and swinging the weapon (R1 + right analog), but left / right slide (strafe) isn't possible because Right Shift cannot be bound to Right, and similarly Jump / Crouch / Cast Spell / Abort Spell cannot be assigned to B, X, R2, L2 respectively. Is it possible to enhance so that any keyboard key can be assigned to a button, which is possible in Custom Keyboard, but that doesn't provide the mouse support, which is important for this game.
DosBox SVN provides the key and mouse customisation, but the game doesn't seem to load with that core.
Many thanks.

**Comment by schellingb** [comment]
I'm a bit torn on how to solve this.
It's either more core options or more control device types.

I could add 2 more custom keyboard device types:
- Custom Keyboard (No Mouse)
- Custom Keyboard (Mouse on Left Analog)
- Custom Keyboard (Mouse on Right Analog)

But then what to do about the mouse buttons? Do you think they should be customizable or assign them fixed?
Fixed would use L/R/X for Left Analog and B/A/X for Right Analog.
To make them customizable would be a bit complicated but we could decide the keyboard keys F13/F14/F15 are left/right/middle buttons. Not really easy to understand. So probably fixed is the way to go.

**Comment by romadu** [comment]
Hi

Actually I inadvertently seem to have found a solution. I used DOSBox SVN,
which has a keyboard + mouse option and closely matches your custom
keyboard option. I loaded the remap folder into DOSBox Pure and all the
button mappings worked plus the mouse was assigned to the right analog.
DOSBox SVN has fixed assignments for the mouse buttons L + R shoulder
buttons, and ironically they are the opposite of DOSBox Pure (R1 is
assigned to primary mouse button ie left mouse button in DOSBox SVN), and
neither allows mouse button reassignment so I changed a setting in the game
controls to use M1 instead of M2 to use the weapon. It works pretty much
perfectly.

Maybe it’s something that the libretro part of the core controls so that
custom keyboard includes a mouse as well, or maybe specific to the RG351P
ArkOS. In Doxbox Pure I can access the virtual keyboard, which isn’t
working in Dosbox SVN.

To answer your question, it would be nice to be able to configure mouse
onto L or R analog, and which button is used for mouse button to 1 & 2, but
it’s sufficient to assign it to R analog and to assign the mouse buttons to
the two shoulders, as that provides the required functionality to play
games with keyboard and mouse combo.

Thank you

**Comment by Faerch** [comment]
> I'm a bit torn on how to solve this.
> It's either more core options or more control device types.
> 
> I could add 2 more custom keyboard device types:
> 
> * Custom Keyboard (No Mouse)
> * Custom Keyboard (Mouse on Left Analog)
> * Custom Keyboard (Mouse on Right Analog)
> 
> But then what to do about the mouse buttons? Do you think they should be customizable or assign them fixed?
> Fixed would use L/R/X for Left Analog and B/A/X for Right Analog.
> To make them customizable would be a bit complicated but we could decide the keyboard keys F13/F14/F15 are left/right/middle buttons. Not really easy to understand. So probably fixed is the way to go.

I just tested DosBox Pure on my Nvidia Shield and it works great. But in some games, I really want to customize the controls for both the keyboard and the mouse.

So I would love if the extra custom keyboard device types were added. I would prefer if the mouse buttons were customizable.
