### ISSUE TITLE
Key next to left-shift does not work on ISO keyboards

### ISSUE THREAD

**Issue by carlosefr** [schellingb/dosbox-pure#544]
The key next to left-shift of ISO keyboards (`KBD_extra_lt_gt`) doesn't work with a physical keyboard (but works with the on-screen keyboard). This means on the "Portugal" layout that I use, I can't type `<` or `>`. On a UK layout this means not being able to type `|` or `\`.

It seems no matter the layout, the keyboard is assumed to be ANSI, where the affected key doesn't exist.

I'm experiencing this on Linux (Ubuntu 22.04 x86_64) with the latest `main` branch, but it has been an issue since at least 0.9.9.

![image](https://github.com/user-attachments/assets/8d0ebb0a-4682-4886-87e6-1511ecf89f10)

**Comment by schellingb** [comment]
Hmm, I wonder if this is a shortcoming of the libretro keyboard callback or if there is something we can do about it.

Can you add a bit of logging into `keyboard_event` to see what codes you get for these keys?

On https://github.com/schellingb/dosbox-pure/blob/main/dosbox_pure_libretro.cpp#L3336 add something like

```c
		static void RETRO_CALLCONV keyboard_event(bool down, unsigned keycode, uint32_t character, uint16_t key_modifiers)
		{
			log_cb(RETRO_LOG_INFO, "[DBP KEYBOARD] Down: %d - Keycode: %u - Character: %u - Modifier: %u\n", (int)down, keycode, character, key_modifiers);
```

And see what it logs when you press the keys in question.

**Comment by carlosefr** [comment]
This is what I get:
```
[DBP KEYBOARD] Down: 1 - Keycode: 323 - Character: 60 - Modifier: 0
[DBP KEYBOARD] Down: 0 - Keycode: 323 - Character: 0 - Modifier: 0
```
And here's my `/etc/default/keyboard` if it helps:
```
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="pt"
XKBVARIANT=""
XKBOPTIONS="lv3:ralt_switch"

BACKSPACE="guess"
```

**Comment by schellingb** [comment]
hmm, can you try adding one more entry to the `keymap` list at https://github.com/schellingb/dosbox-pure/blob/main/dosbox_pure_libretro.cpp#L3324 like
```c
		{RETROK_BACKQUOTE, KBD_grave}, {RETROK_OEM_102, KBD_extra_lt_gt}
	};
```
and see if this makes the key work like you'd expect?

**Comment by carlosefr** [comment]
It works. 🎉

Opened PR #545 with that change.

**Comment by schellingb** [comment]
Woohoo, great, thanks for reporting testing and fixing :-)

**Comment by PoloniumRain** [comment]
> On a UK layout this means not being able to type `|` or `\`

I mentioned this problem years ago in issue #197. It's been a real pain not having a working `\` key in particular...

Just tested out the fix on Windows 11 with a UK keyboard and the `\` and `|` keys now work, so i'll close #197 :)

**Comment by schellingb** [comment]
Oh, that is great to hear! Looking at my comment in #197 it seems like I got stuck thinking only about the on-screen-keyboard and not actual real keyboards. Sorry about that! 🙏
