### ISSUE TITLE
Lands of Lore 1 - dosbox-pure 0.21 VS dosbox-pure 0.9.7 major drop in performance

### ISSUE THREAD

**Issue by cb109** [schellingb/dosbox-pure#546]
Hi,

I am trying to play **Lands of Lore 1** within the RetroArch app on Onion OS 4.3 on the Miyoo Mini Plus, which requires to combine mapping mouse input to the dpad as well as needing some custom keybinds.

![](https://images.gog-statics.com/df99e892b2ee89e4105f42516b777842572f7177ca094f7b0005665687304cea.jpg)

Onion OS 4.3 comes with the dosbox-pure 0.21 core as  the default for DOS games, and it runs the game quite well, unfortunately there's no way to do the desired button mapping, which forces me to maneuver via mouse aka dpad. The pad mapping introduced in dosbox-pure 0.9.x solves that (allowing me to bind numpad buttons for movement to L/R/L2/R2), and 0.9.7 is even pre-packaged on the Miyoo, but choosing that core ends up with an extreme loss of performance when running the game, unfortunately, rendering it unplayable.

I played around with all the performance, emulation, video, audio settings within RetroArch that I could find. The only noticeable change can be seen when changing the Performance option from default to Max: This speeds up the game overall, including mouse movement and audio playback, but only for some things, while still encountering major stutter and lags e.g. when opening/closing the map, so it doesn't solve the issue yet.

I am not sure what I can do to debug this situation further or maybe workaround it, and just wanted to check if this is maybe a known problem with a known solution or if there are any pointers for me to follow up?

Thank you for your work on this software, I am having a blast looking into these old games!

Cheers

**Comment by cb109** [comment]
I gave it another go and I think I fumbled together a working setup now. Here's a quick summary for others finding their way here with similar problems:

- From GitHub you can download the precompiled cores to use on the Miyoo Mini Plus named like ` dosbox_pure_libretro-linux_arm7-<version>.zip`  e.g. I used 0.9.0 and placed it on my SDCard in `RetroArch/.retroarch/cores`. 
  - You may want to edit the `.info` file so that the `display_name` attribute contains the version number so you can tell it apart from the other dosbox-pure cores later.
- You can then launch the RetroArch app separately, `Load Content > DOS / Lands of Lore 1 > Choose Core` and then try to choose the one that you just downloaded.
- Afterwards the game ran, but was very slow. Turns out on this core trying to figure out the emulated performance automatically did not work properly for me as indicated by toggling detailled performance statistics, as the emulator would try to run way too many cycles resulting in poor fps.
  - Within RetroArch what worked for me was to go to `Core Options > Performance Options > Emulated Performance` and choose either `386`or `386DX`.
  - Afterwards it seems I had to turn on VSync and Audio Sync within RetroArch's settings.
- I also saved Core Options and Game Overrides individually so they are remembered. 
- Not sure how to define the new core as the default for the game...

With 0.9.0 I was then able to use the pad mapping for the numpad keys plus mouse bindings, very nice. 

Cheers

**Comment by schellingb** [comment]
Cheers for figuring things out.

You do have a good point though. I've noticed on low spec hardware the automatic performance scaling does not always work well. It somehow is not satisfied until it clocks the emulated system down very low. A version as old as 0.21 of course was very different but maybe I can take a look back on how it did better on low-spec devices and improve what we have now.
