### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by rtissera** [schellingb/dosbox-pure#549]
REG Linux maintainer here !
Is a 0.9.10 or 1.0.0 release planned soon ?
We try to stay on official releases instead of random commits and would like to know what to do as last release is now soon one year old and I can see a lot of improvements / fixes since last release.

**Comment by reignerdeustcher** [comment]
i hope it comes on christmas or new year's eve

**Comment by schellingb** [comment]
[0.9.9](../releases/tag/0.9.9) was posted exactly 365 days ago so here is [1.0-preview1](../releases/tag/1.0-preview1). Thank you for waiting!

**Comment by reignerdeustcher** [comment]
> [0.9.9](../releases/tag/0.9.9) was posted exactly 365 days ago so here is [1.0-preview1](../releases/tag/1.0-preview1). Thank you for waiting!

oh my gowwd, thanksss

if all core developers were so great like this retroarch would be a better place to play

**Comment by klyon0517** [comment]
Yay!
