### ISSUE TITLE
DOSBox Pure on Retropie - won't read core.

### ISSUE THREAD

**Issue by comchia430** [schellingb/dosbox-pure#55]
Hey everyone! I seem to be having an issue trying DOSBox Pure on Retropie (with my Raspberry Pi 400). I've dumped the .so and .info files into the RetroArch core file, but I can't seem to actually access DOSBox Pure through Retropie, just regular DOSBox. Am I supposed to be able to access it from Retropie as I would regular DOSBox? What might I be doing wrong? Sorry for the possibly simple question, but I appreciate any help I can get. 

-comchia

**Comment by georgiptr** [comment]
Google is your friend.

https://retropie.org.uk/forum/topic/28486/i-hope-we-are-getting-dosbox-pure-at-some-point/20?_=1609615347460&lang=en-US

**Comment by schellingb** [comment]
@comchia430 Is this issue still ongoing?
I don't really know anything about Retropie so I'd need more concrete details on what to improve on the core side.
Alternative to having .zip files, you can rename them to .dosz as [explained by the README](..#zip-files-can-be-renamed-to-dosz). Maybe this helps?

**Comment by cmitu** [comment]
It's not a core issue, but an installation problem - RetroPie distributes Libretro cores in a separate location, it's not a problem with the core.As @georgiptr mentioned, follow the instructions to install the core posted in the RetroPie forums if you wish to use Dosbox Pure core with RetroPie's frontend.

**Comment by schellingb** [comment]
Thank you @cmitu for the additional information. I'll close this issue then for now.
