### ISSUE TITLE
open tdc-based retroarch playlist archives

### ISSUE THREAD

**Issue by md0-code** [schellingb/dosbox-pure#56]
Opening Total Dos Collection (TDC) zip archives from a Retroarch playlist fails because of the extra "#" parameter specifying the executable file to be run.

Would it be possible to read this parameter and autmatically lauch these games?

Thank you

**Comment by schellingb** [comment]
@md0-code I published a [new release](../releases/latest) that should handle playlist entries with the '#' separator. Please try it out.
