### ISSUE TITLE
Issue with Dosbox.bat and cdrom games

### ISSUE THREAD

**Issue by sergiohf** [schellingb/dosbox-pure#567]
I dont know if i am doing something wrong, but i cant use dosbox.bat inside the zip file if the game has a cdrom image. The issue is that when dosbox.bat is loaded the cd image dont mount. 
What i did: normally inside the zip file there is a run.bat file. In the dosbox menu the cd is loaded normally and the run.bat runs fine. So i created a copy of the run.bat and renamed it to dosbox.bat and put inside the zip file. When i load the zip file again, the dosbox.bat runs (sound card selection),  but the game dont start since the cdrom is not mounted.
Tried with no cdrom games, and worked normally, but with cd rom games dont work or ask to insert the cdrom.

**Comment by toniosj** [comment]
If you are using eXodos pack, try with .conf files.

https://github.com/BenoitBounar/Pack-Conf-eXoDOS6.0r2-for-DosBOX-Pure-RECALBOX

**Comment by sergiohf** [comment]
I know that exists some alternatives, like setting auto start and loading the conf files, but i think , since this is a feature, that should work correctly, but thanks anyway.

**Comment by schellingb** [comment]
When using DOSBOX.BAT, that batch file is in charge of mounting disks. So you need to use the IMGMOUNT command to mount the right CD/floppy image and so on. Perhaps it's easier for you to keep it as "RUN.BAT" and use the autostart option. You can enable autostart of a program by pressing the RIGHT key/button while selecting it in the DOSBox Pure Start Menu, then next time you launch the same content, it will automatically start with the selected program (hold SHIFT or L2 or R2 while selecting "Restart" in the Quick Menu, or use the on-screen keyboard with the tabs at the bottom to get back to the start menu if needed).

**Comment by sergiohf** [comment]
Thanks! mounting the image in dosbox.bat worked great. Is pretty useful in games like pandora directive, because i can mount 6 cds at once.
