### ISSUE TITLE
[Request] Support 4 or 6 button game controller for 2nd gamepad in libretro

### ISSUE THREAD

**Issue by litaniast** [schellingb/dosbox-pure#61]
A few game can't play 2 players game simultaneously only keyboard.
for example, Tyrian needs mouse or joystick for 2 players game.
But mouse control lacks the enough button. If it can map 4 button joystick in 2nd gamepad, it should be awesome (and play 2 players game of Tyrian properly in DOSBox Pure)

**Comment by schellingb** [comment]
Please try again with the [latest version](../releases/latest). Now all joystick types are available for all ports (still port 1 defaults to Gravis Gamepad or automapping and port 2 defaults to the second DOS Joystick).

**Comment by litaniast** [comment]
Tested in Tyrian 2000 and works well. Thanks.
