### ISSUE TITLE
Escape key doesn't work in custom keyboard bindings mode

### ISSUE THREAD

**Issue by litaniast** [schellingb/dosbox-pure#62]
Many games use escape key to back to menu, exit to DOS and so on.

But when I tried to map escape key to a button in custom keyboard binding mode, that button doesn't work. (works well in automatic mapping or generic keyboard bindings mode)

**Comment by schellingb** [comment]
I get an escape key press by pushing the B button on the game pad with this:
![image](https://user-images.githubusercontent.com/14200249/103890025-b873b880-512a-11eb-9fe9-ddd4fa21a491.png)
Is this different from what you are trying?

**Comment by litaniast** [comment]
Sorry. It didn't work in 0.4 version. When I updated 0.7, Escape key binded in custom keyboard bindings works well.
