### ISSUE TITLE
Save State issue in version 0.7

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#63]
Save states/loading don't work properly in 0.7.

**Comment by mrmatteastwood** [comment]
Hey @Tasosgemah, which games have you tried and what exactly isn't working? I just tried saving and loading states in DOSBox Pure 0.7 in Duke Nukem 1 and Crazy Drake, and I had no issues. I also tried loading a state that was saved in DOSBox 0.5 in Commander Keen 1 ep 2, and that worked too.

**Comment by schellingb** [comment]
I think we need to tackle @Tasosgemah 's problems one-by-one.
This one #52 and #26 are all quite mysterious. Additionally, unrelated to this core, the screenshots posted in #26 getting weirdly cut off is also quite baffling.

Maybe! Maybe you are out of disk space??
That could explain a few of the problems.
- save states can't be written
- setup changes in duke3d not getting written
- screenshots somehow get only partially saved

**Comment by Tasosgemah** [comment]
I only tried 7th Guest, Duke Nukem 3D and Street Fighter 2. And i can't use save states in any of those.

I have 30GB left on the SSD.

I think my issues are caused by a broken RetroArch nightly. Can't explain it otherwise. I will update when a new one comes out and report again.

"screenshots somehow get only partially saved" was always an issue. I have a widescreen monitor and setup everything in 4:3. That means black bars left and right. When you save a screenshot it only takes into account the game area, not the black bars. So when something is drawn over the black bars (like the statistics), it gets cut.

**Comment by Tasosgemah** [comment]
If i make a fresh setup, with a fresh retroarch config, the save states work. So i need to find what option is causing problems to DosBox pure.
