### ISSUE TITLE
Hard GPU - ON option prevents Save States from working

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#64]
I could not save-state with my setup and i finally found out that if GPU-sync is enabled, save states won't work.

You have to enable GPU-Sync, save the config and restart RetroArch to reproduce the problem. Enabling GPU-Sync on the fly without exiting may not prevent save states from working.

This only happens with Dos-Box pure. So i made an override for it to disable GPU-Sync.

**Comment by schellingb** [comment]
Does this still apply to the current version? With the big changes from #184 this might have been resolved as well. @Tasosgemah can you recheck or comment on how this is now?

**Comment by Tasosgemah** [comment]
TBH, i completely forgot about this. I had GPU Sync disabled since i opened the issue and don't remember which version was affected.

I removed the config that disables GPU Sync and i don't seem to have issues saving or loading states. So whatever the issue was, it affected some older version.

**Comment by schellingb** [comment]
Nice, good enough for me to close this :-) Thanks!
