### ISSUE TITLE
Screen Tearing & Keyboard blinking

### ISSUE THREAD

**Issue by XargonWan** [schellingb/dosbox-pure#66]
I am using dosbox-pure on the RG351P console (linux-aarm64) and I got a lot of screen tearing. 

Moreover the keyboard is blinking. 

Are these issues device specific on this devices?
Are those solvable?

Thanks in advance.

**Comment by schellingb** [comment]
Can you tell me what video driver is used on your device (seen under RetroArch menu Settings -> Driver -> Video)?

Also do you mean the on-screen keyboard is flickering on screen or something else?

**Comment by wn2000** [comment]
I also see blinking on-screen keyboard with my RK3328 aarch64 build.
RetroArch video driver is "gl" and driver context is "drm".

**Comment by mrmatteastwood** [comment]
Have you guys tried the "glcore" driver in RA Settings > Video?

**Comment by wn2000** [comment]
My RK3328 only has GLES 2.0 support, so I doubt "glcore" can be used.

**Comment by iconoclusterdotexe** [comment]
I've got the same problem with RPi 4 (gl video driver only available). Tried with Lakka and 0.8 dosbox-pure.
With "Threaded Video Off" on Video settings, screen tearing and on-screen keyboard blinking disappeared and no frame skipping.

**Comment by iconoclusterdotexe** [comment]
I've got the same problem with RPi 4 (gl video driver only available). Tried with Lakka and 0.8 dosbox-pure.
With "Threaded Video Off" on Video settings, screen tearing and on-screen keyboard blinking disappeared and no jerky movements or frame dropping.

**Comment by schellingb** [comment]
A little while ago I noticed that threaded video could introduce all kinds of problems including input events getting ignored (or even lead to crashes) but I hoped in real-world scenarios it wouldn't be that bad. Also I think I was hoping that no one uses threaded video :-)
Thanks for the heads-up @iconoclusterdotexe , I have a Pi 4 and will spend some time with threaded video enabled then. Not sure how much I can improve things really though, maybe just work around the existing problems.

**Comment by wn2000** [comment]
Thanks @iconoclusterdotexe and @schellingb . I'll have to use threaded video on my system, as once turned off even simple games have sound glitch. So I'd appreciate it very much if this could be resolved with threaded video on.

**Comment by XargonWan** [comment]
> Can you tell me what video driver is used on your device (seen under RetroArch menu Settings -> Driver -> Video)?
> 
> Also do you mean the on-screen keyboard is flickering on screen or something else?

I can confirm, it's gl

**Comment by n1ghttrap** [comment]
GL/Vulkan/GLcore has no tearing for me, but D3D11/12 are broken for me.  This is an unfortunate thing as save states don't work in GL.

**Comment by schellingb** [comment]
Version 0.21 released half a year ago should have improved emulation timing and added a "Force 60 FPS" core option. Both should help mitigate the issues described here. If there are still timing related problems, please post about it in #184 where the discussion about the engineering of that update took place. Thanks! Closing this now.
