### ISSUE TITLE
Problem loading some kind of images

### ISSUE THREAD

**Issue by CafeteroCordoba** [schellingb/dosbox-pure#69]
Hi, wonderful job with this fork. I found something interesting.
I have a .IMG file which I was able to use in DOSBox SVN Core for Retroarch, with the boot command in a .conf file.
But if I use the DoxBox Pure Core it does not load it. It says that it can not load it, and in the screen where I can select the file for boot, do not appear any file.
It's not a big deal, since I can get another kind of file, but it caught my attention this behaviour.
If you need the exact .IMG file, let me know. 
Thanks in advance.

**Comment by schellingb** [comment]
The only way to boot images is to switch to the commandline and run the boot command.
As of 0fbb2e0 (to be included in the next release) it is now easier as relative paths can be used, so when for example a ZIP with just one file DISK.IMG is loaded, running the command `BOOT DISK.IMG` from the C: drive will boot it successfully.

I still want to add better support for such boot image games. Maybe if there is no executable, and just one disk image, and that disk image is either not mountable or there are no executables inside of it either, then (try to) auto boot it.

**Comment by schellingb** [comment]
The startmenu in [0.9.0 beta](../releases/tag/0.9.0) can now directly boot from disk images and swapping disks at runtime with RetroArch's "Disc Control" menu and hotkeys is also supported. Here's the startup of some weird obscure game which requires disk swapping:

![DOSBox_Pure_SevenCitiesOfGold](https://user-images.githubusercontent.com/14200249/164047628-450b6891-f270-4d74-a2cf-ae6a23974a2f.gif)

 Please reply in #102 for feedback on it.
