### ISSUE TITLE
Image .cue .bin

### ISSUE THREAD

**Issue by altiereslima** [schellingb/dosbox-pure#7]
No mount .cue + .bin?

**Comment by schellingb** [comment]
Have you tried it? It should be able to load CUE files from inside ZIPs, directly launching with a CUE file, when loading a M3U/M3U8 file with references to CUE files, or when adding a CUE file through RetroArch's Disc Control menu.

**Comment by paivaleonardo** [comment]
Here the .cue images mount perfectly.

**Comment by altiereslima** [comment]
![image](https://user-images.githubusercontent.com/18044879/102935263-93bde680-4484-11eb-86a7-70ed8fc00ca8.png)

**Comment by altiereslima** [comment]
![image](https://user-images.githubusercontent.com/18044879/102935497-07f88a00-4485-11eb-922f-e13f1dde7f62.png)

**Comment by Svipur** [comment]
@altiereslima Had the same problem. This happens with .zip files containing an installed game and a CD image in .bin + .cue format when the CD image is **in the root folder** of the .zip file. 

For some reason, DosBox Pure reports that MSCDEX is missing in this case.

**Solution** - just put the .cue and ,bin file **in a folder inside the .zip file**. (Doesn't have to be named 'CD', any name will do.)

**Comment by altiereslima** [comment]
@Svipur, Thanks, now it worked.

**Comment by BlackLotus** [comment]
Trying to get this working with the Tomb Raider 1 GOG release. Got a cue file name GAME.DAT und a bin file named GAME.GOG and tracks as mp3.
```
mkdir CD
mv GAME.DAT CD/GAME.CUE
mv GAME.GOG CD/
mv *.mp3 CD/
```
Zipping everything and trying to open the game with dosbox-pure results in it trying to load GAME.GOG in the execution folder instead loading it from the zip. When operating from within the CD folder it loads the GAME.GOG file but still produces the `[ERROR] [Environ]: SET_MESSAGE_EXT: Unable to open image file: $C:\CD\GAME.CUE` error. Maybe this is related to #18?

**Comment by schellingb** [comment]
Please try again with version 0.3, it should be better about various things related to CUE file loading.

**Comment by altiereslima** [comment]
> Please try again with version 0.3, it should be better about various things related to CUE file loading.

Confirmed. Works perfectly!

**Comment by Allanon41** [comment]
This doesn't work. I put cue bin files in a folder, zipped it. Loaded that zip as content, get error unable to mount cd rom img.

**Comment by schellingb** [comment]
Can you open the .CUE file in a text editor like Notepad and see if something wrong with how it refers to the BIN file? Can you paste the content of the .CUE file here?
