### ISSUE TITLE
Frontend MIDI silence when selected prior to game booting.

### ISSUE THREAD

**Issue by sweatypickle** [schellingb/dosbox-pure#70]
Win 10 64
Tested Games: Doom (GM), Leisure Suit Larry 6 (GM), Leisure Suit Larry 3 (MT-32)

When using the Frontend MIDI option, no sound is heard when loading a game with Frontend MIDI selected prior to loading the game.  To function as intended, a sf2 must be selected and then switched to Frontend MIDI once the **game** is loaded.  Loading the core to the boot menu with a soundfont and switching to Frontend MIDI before booting the game does not work.  I've tried this with both software MIDI synths (MUNT, Virtual Midi Synth as well as a borrowed Roland SC-88 through USB-MIDI).  The same occurs in all instances.

**Comment by schellingb** [comment]
Please try again with the [latest version](../releases/latest). Hopefully I got it right this time :-)
Thanks for reporting

**Comment by sweatypickle** [comment]
Unfortunately, the commit didn't fix the issue. :(  Same problem exists.

**Comment by schellingb** [comment]
What OS are you on?

All I have is Windows and the built-in "Microsoft GS Wavetable Synth" to test. DOOM does run fine now for me.
I noticed MIDI output breaking when trying to play a game with MT-32 output through it, which I assumed is because the MT-32 specific messages somehow break that MIDI synth or otherwise make it silent. But maybe it's something else...

**Comment by sweatypickle** [comment]
Win 10 64.

I removed all software synths and unplugged the Roland so we're troubleshooting on even ground.  Even using "Microsoft GS Wavetable Synth" as the lone synth to test I get the same results.

**Comment by Tasosgemah** [comment]
I also test on "Microsoft GS Wavetable Synth" and have similar issues as i mentioned in the other topic.

**Comment by sweatypickle** [comment]
Phenomenal work Bernhard! Testing with the latest commit and fixed RetroArch all games seem to be working as expected.

**Comment by schellingb** [comment]
Oh man, you're way ahead. Really happy to hear that you could test it so quickly. Thanks for reporting and testing!

**Comment by Tasosgemah** [comment]
Wait, there is a new version? I still only see version 0.8 in the release section.

**Comment by sweatypickle** [comment]
No I built it. I'm sure he'll put one out soon.

**Comment by Tasosgemah** [comment]
> 
> 
> No I built it. I'm sure he'll put one out soon.

0.9 is released but i'm having the exact same issues with Fontend Midi not producing music in either Ultimate DOOM or Duke Nukem 3D.

**Comment by sweatypickle** [comment]
Make sure your Retrorarch is updated to the latest nightly.

**Comment by Tasosgemah** [comment]
Oh, it works now! I wonder what's changed, the version i was using was only a couple of days old.

Still though, it's not 100% perfect. The music works and it's the quality i'm used to from the standalone DosBox but i notice in some parts there might be an instrument missing, a drum missing a hit or a weird sound here and there. Seems like RetroArch is pretty finicky with it's Midi handling. Can't explain otherwise why it's so hard to nail this.

**Comment by Tasosgemah** [comment]
One thing i'd like to ask, is the "MPU-401" option in the standalone DosBox the same as choosing "Frontend Midi" in DosBox pure? Or are those two different things?

In the Standalone DosBox the music is perfect, there are no glitches or anything when i use General midi. And this might be a placebo but i feel like the overall quality is better (now that i'm testing it again). So i wonder if that elusive MPU-401 is the reason why DosBox pure isn't as perfect sound wise?

**Comment by schellingb** [comment]
You don't have to wonder what changed, the patch I submitted to RetroArch "winmm_midi: Recover from MIDI messages not handled by the device" is linked a few lines above your post :-)

In theory the native DOSBox MPU-401 MIDI output (on Windows) should be equal to Frontend Midi with the winmm MIDI driver selected in RetroArch. They end up using the same Windows API to do MIDI output.
But... RetroArch has some additional layers of buffering and processing things. It doesn't introduce any delay or anything, but code-wise there are a few more steps involved between the emulated DOS game writing the MIDI message and it being processed by Windows.
Additional steps means more chance of bugs. So what you're feeling can't be ruled out I think. But it's rather hard to debug for sure. 
I can try to read through the RetroArch code once more and see if something sticks out that could result in something like that.

One could use OBS to record the resulting audio of both DOSBox Pure and native DOSBox and line the wave data up next to each other in Audacity to find differences. Once a difference is found, it needs to be seen that it is repeatable or if it's randomly different.  Knowing a reproducible wrong output would certainly help.

**Comment by Tasosgemah** [comment]
I just realized, this was a RetroArch fix, not a core fix. I just tested the older version of the core (0.8) and the midi music works there too.

As for reproducing the music bugs, the first thing i can say at the moment is that one could test the first level in Duke Nukem 3D (the song is called "stalker"). This seems to have 3 or 4 parts where some weirdness is heard compared to the perfect music in the standalone DosBox. If one is familiar with the song the same way i am, he will notice those instances immediately. Even without familiarity, one should tell there is something odd here and there like a drum beat missing or a note suddenly not following the rhythm for one second.

Your post makes sense. RetroArch having extra steps to produce the sound seems like the most logical source for these issues.

**Comment by Tasosgemah** [comment]
I found another way to track this issue. It's 100% reproducible and very easy to spot.

When you load Duke Nukem 3D, it plays it's iconic main theme. It sounds fine but the moment you press a button to bring up the menu, you can hear the music freezing for a split second. Like it's having trouble to keep up with the menu appearing so it lags.

This doesn't happen in the standalone so this might be a good sound sample to debug.

**Comment by KainXVIII** [comment]
> I found another way to track this issue. It's 100% reproducible and very easy to spot.
> 
> When you load Duke Nukem 3D, it plays it's iconic main theme. It sounds fine but the moment you press a button to bring up the menu, you can hear the music freezing for a split second. Like it's having trouble to keep up with the menu appearing so it lags.
> 
> This doesn't happen in the standalone so this might be a good sound sample to debug.

I have even worse problem - menu music just hangs at 1 note after some time. And this continues even after you start first level, just this hanging note.
