### ISSUE TITLE
Duke Nukem 3D and Atomic Edition glith

### ISSUE THREAD

**Issue by paivaleonardo** [schellingb/dosbox-pure#73]
Both games have constant graphical flaws and crashs.

**Comment by schellingb** [comment]
The graphical glitches and flickering is a known DOSBox issue. You can work around it by setting the core option `Video > SVGA Mode` to `S3 Trio64 no-line buffer hack (reduces flickering in some games)` or by limiting the emulated performance to a fixed amount of cycles.
You can find a big discussion about it [here](https://www.google.com/search?q=%22SVGA+S3+Trio+emulation+is+faulty+for+games+using+VESA+LFB%22+site%3Agithub.com).

But besides flickering, there should be no crashes. At what point does it crash?

**Comment by paivaleonardo** [comment]
Thanks, that solved!
