### ISSUE TITLE
Can Not Figure Out How To Change Discs

### ISSUE THREAD

**Issue by appollo147** [schellingb/dosbox-pure#74]
I am using DOSBOX Pure 0.8 and games are running great I just can't figure out how to swap discs when playing or installing multi-disc games. Could someone help me with this? I would really appreciate any assistance anyone could give me with this issue.

**Comment by 71knight** [comment]
Go to retroarch quick menu while dosbox pure is running and then scroll to the bottom where it says disc control and select some of those options and read the instructions.

**Comment by thehype1234** [comment]
Maybe it will be helpful to share some more info on the .m3u8 topic? I couldn’t find anything on this except for video files!? 😉

**Comment by schellingb** [comment]
While the Disc Control menu still works perfectly fine to switch the mounted CD or floppy image, the newest version [1.0-preview1](../releases/tag/1.0-preview1) available here and from the RetroArch online core downloader now additionally allows easy access to the start menu while running a game by opening the On-Screen Keyboard where the mounted CD can also be swapped. With this, I will close this issue.
