### ISSUE TITLE
Analog Deadzone in version 0.9 increased?

### ISSUE THREAD

**Issue by Tasosgemah** [schellingb/dosbox-pure#84]
I noticed that the analog deadzone in 0.9 has been increased. There is a small delay when i turn around in FPS games. 

I understand that some older gamepads don't have perfect analog sticks, the XBOX 360 controllers do have deadzone issues being too sensitive or drifting a bit. But these issues could be fixed by increasing the deadzone value from the RetroArch options. 

The problem with fixing these deadzone issues internally, by default, is that when you use an actual decent analog stick (like the ones on XBOX one pads) you get a very high deadzone default and you can't fix it in the RA options because they are already at zero (you can't go -1).

Maybe a deadzone option would be better in the core options instead of a very high deadzone default value?

EDIT: I think the cursor in the virtual keyboard needs to have it's own, separate deadzone value. Because when you try to fix that so it doesn't move by itself, because it's too sensitive, the deadzone in games also gets dragged along with it. In games it's not as sensitive so when you increase it for the virtual keyboard you just add more lag in games.

**Comment by schellingb** [comment]
See #77, there is a new core option now 'Input > Joystick Analog Deadzone' that defaults to 15% which I was told is in line with a few other cores. The benefit of having a core option in addition to the frontend input option is that it's easier to find and easier to customize per game. Personally I'm not a fan of duplicating frontend functionality but if many cores that deal with analog sticks have such an option it might be expected by some users.

**Comment by Tasosgemah** [comment]
Damn, i completely missed that extra option. Seems you had this covered already.
