### ISSUE TITLE
[Enhancement] Set limit hz from Dosbox Core

### ISSUE THREAD

**Issue by gordon81-afk** [schellingb/dosbox-pure#91]
Greetings, first all thank you for bring us the project.

Most Dos games have 70hz, but 60hz monitors have many problems of stutter, tearing with games like Dangerous Dave, Commander Keen, Epic Pinball.

The solution is g-sync or freesync with 70hz hz capped monitor, but mostly people don´t have these expensive technologies.

Is possible get and option to force ModeX/VESA? games that operate in 320x240, 320x480, 360x480 and 640x480
since they're 60hz.

Or get and core option hz limiter. I have the vsync forced in nvidia panel and 60.98hz with custom resolution utility (for most retroarch cores but dosbox pure).

Super StarWars detects 55 hz display in setup.

In dosbox config (windows version) it can select range of hz

_output=opengl

.

.

.

vsyncmode=on

vsyncrate=60_

Vsync broken most Dos games, what is the recomended configuration to get flawles smoth scroll in Dos games with 60hz monitors?.

Thank you, i love your project.

**Comment by schellingb** [comment]
@gordon81-afk Can you close this if this has been resolved with the changes done in #184?
