### ISSUE TITLE
Lands of Lore Controls

### ISSUE THREAD

**Issue by gordon81-afk** [schellingb/dosbox-pure#92]
Greetings.

I would like set f1, f2, f3 attacks in xbox 360 pad, but i don´t know how set it.

Another remapping keys is about turn pnj, the strafe keys works well but not keys "7" and "9".

How can i remapp these keys.

Thanks you!

**Comment by OrsV** [comment]
Hi,

You can do that in the controls menu (https://youtu.be/yfulKe7U5aE?t=242). Launch the game, bring up the menu->Controls->Port1 Controls->Device Type: Custom Keyboard Bindings (if it was disabled back out and back in after selection) and select the xbox 360 pad button you want to be assigned to those and set it to Keyboard Numpad7, Keyboard Numpad9, Keyboard F1, etc. Once you are done go back and do Save Game Remap File (to have this saved for the specific game).

Hope this helps.

**Comment by schellingb** [comment]
This should be solved by the new gamepad mapper released in [0.9.0 beta](../releases/tag/0.9.0). Please reply in #57 for feedback on it.
