### ISSUE TITLE
Ogg/mp3/wav file cd tracks not supported?

### ISSUE THREAD

**Issue by krank** [schellingb/dosbox-pure#94]
The regular version of DOSBox supports having a cue file that loads up some ogg/wav/mp3 files as audio tracks. Very nice for those of us who want to save space and don't mind lower audio quality.

This is the error message I get:

![image](https://user-images.githubusercontent.com/277268/105076640-9879b880-5a8b-11eb-8053-21cd9617beb7.png)

This is an example of a CUE file it refuses:

```FILE "chasm_mini.iso" BINARY
  TRACK 01 MODE1/2048
    INDEX 01 00:00:00
FILE "chasm02.ogg" MP3
  TRACK 02 AUDIO
    INDEX 01 00:00:00
FILE "chasm03.ogg" MP3
  TRACK 03 AUDIO
    INDEX 01 00:00:00
FILE "chasm04.ogg" MP3
  TRACK 04 AUDIO
    INDEX 01 00:00:00
FILE "chasm05.ogg" MP3
  TRACK 05 AUDIO
    INDEX 01 00:00:00
FILE "chasm06.ogg" MP3
  TRACK 06 AUDIO
    INDEX 01 00:00:00
FILE "chasm07.ogg" MP3
  TRACK 07 AUDIO
    INDEX 01 00:00:00
FILE "chasm08.ogg" MP3
  TRACK 08 AUDIO
    INDEX 01 00:00:00
FILE "chasm09.ogg" MP3
  TRACK 09 AUDIO
    INDEX 01 00:00:00
FILE "chasm10.ogg" MP3
  TRACK 10 AUDIO
    INDEX 01 00:00:00
```

I've tried converting all tracks to mp3 or wav, editing the cue file accordingly. Nothing.
I tried removing all tracks but the first – nothing.

cue, iso and audio files are in the root of the zip file.

The only way I could get the cue to work was by removing all the audio tracks, only keeping the iso.

Games tried: Worms, Chasm: The Rift.
Platform: Windows 10
Core used: DOsbox-pure 0.9

**Comment by schellingb** [comment]
Yeah for now no compressed audio formats are supported.

The only format support that I have considered adding is OGG Vorbis, due to the existence of [stb_vorbis](http://www.nothings.org/stb_vorbis/) (a public domain single-source-file OGG Vorbis decoding library). Other formats like MP3 and FLAC, which are sometimes supported with .cue file loading, usually means adding rather large external library dependencies for each format. Which personally is most undesired.

For now I added the enhancement label because I certainly like the size saving aspects of it and I want to add support for some format(s) some day.

**Comment by krank** [comment]
Are any _uncompressed_ formats supported? Or is it just monolithic plain bin files for now? Plain wave (WAV) files seem to not work either right now – would those require external libraries as well?

**Comment by schellingb** [comment]
Ah, didn't think about that one :-)
Uncompressed WAV I can do without libraries, that would certainly be the easiest one. Also a good starting point to add more complex formats further down the line. I'll see if I can do that in the next few days. Shouldn't need much code so there's no downside really.

**Comment by Solo187** [comment]
You could use the method in the link below to convert your cue mp3/ogg/wav to chd & then back again. You will be left with a single bin cue with all relevant audio intact. It obviously won't save any space but it will atleast work. All info here https://forum.recalbox.com/topic/16504/how-to-batch-process-psx-images-with-multiple-bins-per-cd I've successfully used this method before for multi bin saturn games.

**Comment by krank** [comment]
> You could use the method in the link below to convert your cue mp3/ogg/wav to chd & then back again. 

I opted to just rip my original CDs again instead. But I'd still love to be able to use something a little… smaller, at some point in the future.

**Comment by toniosj** [comment]
Hopefully this improvement will be incorporated soon. My OGG isos are eager to run on the wonderful DOSBOX-Pure.

**Comment by mrmatteastwood** [comment]
Hey @schellingb or anybody, really... I was wondering how to get CD-ROM games working in the first place? As far as I remember, back in the original DOS days, one would need to insert the CD, then run an installer/setup program from the CD to install a part of the game on the hard drive, then run the game with the CD inserted.

In DOSBox Pure, if I understand correctly, the CD ROM ISO gets auto-mounted if it's in the same ZIP as the portion of the game that was originally installed on a hard disk. But how do I get that portion if all I have is an ISO?

**Comment by alonsocr23** [comment]
The same thing happens to me, games with audio in OGG do not work for me either. Thanks.

**Comment by schellingb** [comment]
Has anyone tested the support for WAV and OGG audio tracks?
Is there a big need for MP3 and FLAC? Both formats are much more cumbersome compared to OGG (technical implementation and maintenance wise). Otherwise we could close this issue :-)

**Comment by toniosj** [comment]
> Has anyone tested the support for WAV and OGG audio tracks?
> Is there a big need for MP3 and FLAC? Both formats are much more cumbersome compared to OGG (technical implementation and maintenance wise). Otherwise we could close this issue :-)

I'm on holidays. I would like to test it when I come back on 30th august.

**Comment by toniosj** [comment]
> Has anyone tested the support for WAV and OGG audio tracks?
> Is there a big need for MP3 and FLAC? Both formats are much more cumbersome compared to OGG (technical implementation and maintenance wise). Otherwise we could close this issue :-)

Tested on 0.15, and .ogg tracks are working fine. Thanks!!!

**Comment by filevans** [comment]
> > Has anyone tested the support for WAV and OGG audio tracks?
> > Is there a big need for MP3 and FLAC? Both formats are much more cumbersome compared to OGG (technical implementation and maintenance wise). Otherwise we could close this issue :-)
> 
> Tested on 0.15, and .ogg tracks are working fine. Thanks!!!

Do you know if ogg is supported in dosbox-pure on Retroarch? As it's not mentioned anywhere in the readme here
