### ISSUE TITLE
Can't Save on Simfarm

### ISSUE THREAD

**Issue by TradeDraft** [schellingb/dosbox-pure#95]
When I try and save it says Not Enough Disk Space

Screenshot:

https://i.ibb.co/JQt0f49/Sim-Farm-1993-210121-202703.png

Is this Fixable or some Bug with the Core?

**Comment by schellingb** [comment]
Thank you very much for reporting this.
I was able to fix this, hopefully I can get around making a new release in the coming days.

**Comment by schellingb** [comment]
@TradeDraft Should be fixed in version 0.10, if you have some time, please check it out.

**Comment by TradeDraft** [comment]
Checked @schellingb and Saved and Loaded Fine Now.

Thanks for Fixing that Mate
