### ISSUE TITLE
Feature Request: Option to suppress "Emulated CPU is overloaded" message

### ISSUE THREAD

**Issue by john-parton** [schellingb/dosbox-pure#96]
Feature Request: Option to suppress "Emulated CPU is overloaded" message

Some solutions:

* Add an option to completely suppress the message OR
* Only show the message once OR
* Rate limit or throttle the message show it doesn't spam multiple times in a row

**Comment by Tkcmd** [comment]
I'd also like to see an option to be able to disable it. On my platform (rk3326 based handheld) it seems to trigger a bit to eagerly in some games which is quit annoying.

**Comment by schellingb** [comment]
This message does not exist anymore as of version 0.21. Discussion about the new timing handling which eliminated that message can be found in #184. Closing this now.
