### ISSUE TITLE
Unable to find IndyCar.exe in ''.

### ISSUE THREAD

**Issue by Panderner** [schellingb/dosbox-pure#98]
When i tried to launch IndyCar Racing 2 it refuses to launch and the error screen appear.

![INDYCAR-210123-193253](https://user-images.githubusercontent.com/37503397/105577024-e0614e00-5db1-11eb-8289-2cbcd6716289.png)

**Comment by schellingb** [comment]
IndyCar Racing 2 does not run form `C:\INDYCAR.EXE` it needs to be somewhere that isn't the root of the drive (for example `C:\ICR2\INDYCAR.EXE`).

DOSBox Pure by default mounts a lonely directory in the root of the loaded ZIP as the `C:` drive. To work around this, you can open the ZIP file and add an empty text file to the root of the ZIP.
This comment from me is related to this: https://github.com/schellingb/dosbox-pure/issues/87#issuecomment-764865994

There are a bunch of ideas floating in my head how this can be improved but I have not yet decided which way to go, hopefully I can tackle this soon.
Thanks for reporting this, the more games I know that can have path related problems like this will help in finding a good solution.

**Comment by Panderner** [comment]
I tried to open empty exe file for NEXT next to ICR2 and it worked.
